/-
Copyright (c) 2026 Samuel Schlesinger. All rights reserved.
Released under MIT license as described in the file Complexitylib/Algebraic/LICENSE.
Authors: Samuel Schlesinger
-/

module
public import Tengoku.Complexitylib.Complexitylib.Algebraic.LowerBound.Cutwidth.Extractor.Condenser.Modulus.Binary.Defs
public import Tengoku
import Tengoku.Complexitylib.Complexitylib.Algebraic.LowerBound.Cutwidth.Extractor.Condenser.Modulus.Binary.Internal
import Tengoku.Complexitylib.Complexitylib.Algebraic.LowerBound.Cutwidth.Extractor.Condenser.Modulus.Binary.Internal.Basic
import Tengoku.Complexitylib.Complexitylib.Algebraic.LowerBound.Cutwidth.Extractor.Condenser.Modulus.Binary.Internal.Irreducible

/-!
# The sparse binary trinomial modulus

The monic irreducible trinomial `X^(2 * 3^s) + X^(3^s) + 1` defines a binary
field of cardinality `2^(2 * 3^s)`. Its named quotient root is a noncube, so it
can supply the next binomial modulus coefficient without an existence choice.

Irreducibility uses Mathlib's `Polynomial.irreducible_comp`, the four-element
field generated by the base quadratic, and the Kummer theorem documented in
`Binomial`. The root's noncube property follows from the irreducibility of
the next trinomial and Mathlib's finite-module minimal-polynomial degree bound:
https://leanprover-community.github.io/mathlib4_docs/Mathlib/FieldTheory/Minpoly/Finite.html.
These are semantic algebraic facts. `Binary.Codec` supplies the fixed-width
quotient representation, and `Binary.Encoding` connects a uniform modulus
generator and modular-squaring program. `Binary.Extension` identifies the
larger quotient used by the complete evaluator in `Condenser.Encoding.Correctness`.
-/

public section

namespace Algebraic.Cutwidth.Extractor

/-- Every binary trinomial in the family is monic. -/
theorem binaryModulus_monic (s : Nat) : (binaryModulus s).Monic :=
  Internal.binaryModulus_monic s

/-- The leading exponent gives the exact degree. -/
theorem binaryModulus_natDegree (s : Nat) : (binaryModulus s).natDegree = 2 * 3 ^ s :=
  Internal.binaryModulus_natDegree s

/-- The quotient has exactly as many elements as a binary vector of the modulus degree. -/
theorem card_adjoinRoot_binaryModulus (s : Nat) :
    Nat.card (AdjoinRoot (binaryModulus s)) = 2 ^ (2 * 3 ^ s) :=
  Internal.card_adjoinRoot_binaryModulus s

/-- Substituting a cube passes to the next member of the same explicit family. -/
theorem binaryModulus_comp_cube (s : Nat) :
    (binaryModulus s).comp (Polynomial.X ^ 3) = binaryModulus (s + 1) :=
  Internal.binaryModulus_comp_cube s

end Algebraic.Cutwidth.Extractor
