/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan

# Bundled CLM lift of the projection operator `T` and its adjoint

This file defines the **bounded-linear-operator** layer needed by the
spectral discharge of the Tikhonov bias bound.  The function-level operator
`OperatorSystem.T : Lp ℝ 2 μ → Lp ℝ 2 μ` defined in
`Causalean/Estimation/NPIV/Operator.lean` is here re-packaged as a bundled
`ContinuousLinearMap`

    `S.Tlin : L²(σ(X)) →L[ℝ] L²(σ(Z))`

obtained by including `L²(σ(X))` into ambient L², applying the
conditional-expectation CLM `condExpL2 ℝ ℝ S.m_Z_le`, and composing with the
orthogonal-projection CLM `Qbar_L2.starProjection` inside `L²(σ(Z))`.

We then expose the **ambient-space adjoint** `Tadjoint := S.Tlin.adjoint` and
the self-adjoint composite `Tstar_T := Tadjoint.comp Tlin`, which is the
operator the source condition refers to. Its primal endpoint is the full
`L²(σ(X))`, not the candidate submodule `Hbar_L2`. Self-adjointness follows from
`IsSelfAdjoint.star_mul_self` once we identify `Tadjoint` with `star Tlin`
in the C⋆-algebra `Lp ℝ 2 μ →L[ℝ] Lp ℝ 2 μ`.

All declarations in this file are fully proved.
-/

module
public import Tengoku.Causalean.Causalean.Estimation.NPIV.Operator
public import Tengoku

/-!
Builds the bundled continuous-linear-map representation of the NPIV operator
and its adjoint. These operator-theoretic objects feed Tikhonov regularization
and spectral arguments.
-/

@[expose] public section

namespace Causalean
namespace Estimation
namespace NPIV

namespace OperatorSystem

open MeasureTheory ContinuousLinearMap

variable {Ω : Type*} [m₀ : MeasurableSpace Ω] {μ : Measure Ω}

/-! ## Bundled CLM `Tlin` -/

/-- For [an NPIV operator system](hyp:S), [the bundled conditional-expectation operator is the continuous linear map sending each ambient $L^2$ random variable to its conditional expectation given the σ-algebra generated by the instrument](goal).

The conditional-expectation step `f ↦ E[f | σ(Z)]`, viewed as a
continuous real-linear map from `L²(σ(X))` to `L²(σ(Z))`.

This is `condExpL2 ℝ ℝ S.m_Z_le` pre-composed with the canonical inclusion
of `L²(σ(X))` into ambient `L²(μ)`. -/
noncomputable def condExpStepL (S : OperatorSystem Ω μ) :
    S.PrimalL2 →L[ℝ] S.InstrumentL2 :=
  haveI := S.isFiniteMeasure
  (MeasureTheory.condExpL2 ℝ ℝ S.m_Z_le).comp S.PrimalL2.subtypeL

/-- For [an NPIV operator system](hyp:S), [the bundled NPIV operator is the
continuous linear map on the full primal space that conditions an
`L²(σ(X))` element on the instrument and then orthogonally projects it onto
the closed dual candidate space](goal).

The bundled continuous-linear-map version of `OperatorSystem.T`:

    `Tlin = Qbar_L2.starProjection ∘L condExpStepL`.

`starProjection` (from `Mathlib.Analysis.InnerProductSpace.Projection.Basic`)
bundles the orthogonal projection into `Qbar_L2` followed by the subtype
inclusion, both as one CLM `Lp ℝ 2 μ →L[ℝ] Lp ℝ 2 μ`. -/
noncomputable def Tlin (S : OperatorSystem Ω μ) :
    S.PrimalL2 →L[ℝ] S.InstrumentL2 :=
  haveI := S.Qbar_L2_hasProj
  S.Qbar_L2.starProjection.comp S.condExpStepL

/-- Coherence: applying the bundled CLM `Tlin` to `f` agrees with the
function-level operator `T` from `Causalean/Estimation/NPIV/Operator.lean`.
The proof unfolds both sides and uses
`Submodule.starProjection_apply = orthogonalProjectionFn`.
@isnad1 id=eq.0h4v.s15.36906e5bdb8e from=translated src=- shape=ff141c95 vocab=24b44e93
-/
lemma Tlin_apply (S : OperatorSystem Ω μ) (f : S.PrimalL2) :
    S.Tlin f = S.T f := by
  rfl

/-! ## Adjoint and the self-adjoint composite `T*T` -/

/-- For [an NPIV operator system](hyp:S), [the adjoint operator is the Hilbert-space adjoint of its bundled NPIV projection operator](goal).

The adjoint operator `T† : L²(σ(Z)) →L[ℝ] L²(σ(X))`.

Defined via Mathlib's `ContinuousLinearMap.adjoint` between the two closed
`lpMeas` Hilbert spaces. -/
noncomputable def Tadjoint (S : OperatorSystem Ω μ) :
    S.InstrumentL2 →L[ℝ] S.PrimalL2 :=
  letI : Fact (S.m_X ≤ m₀) := ⟨S.m_X_le⟩
  letI : Fact (S.m_Z ≤ m₀) := ⟨S.m_Z_le⟩
  ContinuousLinearMap.adjoint S.Tlin

/-- For [an NPIV operator system](hyp:S), [the self-adjoint positive-semidefinite composite is its bundled NPIV operator followed by its Hilbert-space adjoint](goal).

The self-adjoint, positive-semidefinite composite `T† T`.  This is
the operator the β-source condition refers to:
`h₀ = (T*T)^{β/2} w₀` is interpreted via Mathlib's continuous functional
calculus on this CLM. -/
noncomputable def Tstar_T (S : OperatorSystem Ω μ) :
    S.PrimalL2 →L[ℝ] S.PrimalL2 :=
  S.Tadjoint.comp S.Tlin

/-- [For any NPIV operator system](hyp:S), [the composite operator `T† T`, obtained by
composing the second-stage conditional-expectation operator with its adjoint, is
self-adjoint](goal).

Follows from `IsSelfAdjoint.star_mul_self` in the C⋆-algebra `Lp ℝ 2 μ →L[ℝ] Lp ℝ 2 μ`, after
identifying `Tadjoint` with `star Tlin` and `comp` with `*` (`ContinuousLinearMap.mul_def`).
@isnad1 id=isselfad.0h3v.s14.c8f5c8d196c8 from=translated src=- shape=f8b603fe vocab=66c7d9f1
-/
lemma Tstar_T_isSelfAdjoint (S : OperatorSystem Ω μ) :
    IsSelfAdjoint S.Tstar_T := by
  letI : Fact (S.m_X ≤ m₀) := ⟨S.m_X_le⟩
  letI : Fact (S.m_Z ≤ m₀) := ⟨S.m_Z_le⟩
  have h :=
    (IsSelfAdjoint.one (S.InstrumentL2 →L[ℝ] S.InstrumentL2)).adjoint_conj S.Tlin
  simpa [Tstar_T, Tadjoint, ContinuousLinearMap.one_def] using h

/-! ## Isometric trimmed-measure realization -/

/-- For [an NPIV operator system](hyp:S), [the canonical isometric identification of
`L²(σ(X))` with ordinary L² under the measure trimmed to σ(X)](goal) is Mathlib's
`lpMeasToLpTrimLie`. -/
noncomputable def primalTrimEquiv (S : OperatorSystem Ω μ) :
    S.PrimalL2 ≃ₗᵢ[ℝ] Lp ℝ 2 (μ.trim S.m_X_le) :=
  lpMeasToLpTrimLie ℝ ℝ 2 μ S.m_X_le

/-- For [an NPIV operator system](hyp:S), [the trimmed-measure realization of its NPIV
operator](goal) first maps ordinary L² under the σ(X)-trimmed measure back to `L²(σ(X))`
and then applies `T`. -/
noncomputable def TlinTrim (S : OperatorSystem Ω μ) :
    Lp ℝ 2 (μ.trim S.m_X_le) →L[ℝ] S.InstrumentL2 :=
  S.Tlin.comp S.primalTrimEquiv.symm.toContinuousLinearEquiv.toContinuousLinearMap

/-- For [an NPIV operator system](hyp:S), [the adjoint of the trimmed-measure realization
of its NPIV operator](goal) maps `L²(σ(Z))` to ordinary L² under the σ(X)-trimmed measure. -/
noncomputable def TadjointTrim (S : OperatorSystem Ω μ) :
    S.InstrumentL2 →L[ℝ] Lp ℝ 2 (μ.trim S.m_X_le) :=
  ContinuousLinearMap.adjoint S.TlinTrim

/-- For [an NPIV operator system](hyp:S), [the transported normal operator on ordinary L²
under the σ(X)-trimmed measure](goal) is the adjoint-product of the transported NPIV
operator. -/
noncomputable def Tstar_T_trim (S : OperatorSystem Ω μ) :
    Lp ℝ 2 (μ.trim S.m_X_le) →L[ℝ] Lp ℝ 2 (μ.trim S.m_X_le) :=
  S.TadjointTrim.comp S.TlinTrim

/-- For [an NPIV operator system](hyp:S), [the transported normal operator is
self-adjoint](goal).
@isnad1 id=isselfad.0h3v.s12.9cf14306b0c3 from=translated src=- shape=83ebfe72 vocab=8e633e62
-/
lemma Tstar_T_trim_isSelfAdjoint (S : OperatorSystem Ω μ) :
    IsSelfAdjoint S.Tstar_T_trim := by
  have h :=
    (IsSelfAdjoint.one (S.InstrumentL2 →L[ℝ] S.InstrumentL2)).adjoint_conj S.TlinTrim
  simpa [Tstar_T_trim, TadjointTrim, ContinuousLinearMap.one_def] using h

end OperatorSystem

end NPIV
end Estimation
end Causalean
