/-
Copyright (c) 2026 Jiedong Jiang, Christian Merten. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiedong Jiang, Christian Merten
Changed for Tengoku: copied from Mathlib (leanprover-community/mathlib4 at 85e3a25e006c); import paths rewritten.
-/
module

public import Tengoku.Seed.AlgebraicGeometry.Morphisms.UniversallyOpen
public import Tengoku.Seed.AlgebraicGeometry.Morphisms.WeaklyEtale
public import Tengoku.Seed.AlgebraicGeometry.Sites.Etale
public import Tengoku.Seed.AlgebraicGeometry.Sites.QuasiCompact
public import Tengoku.Seed.AlgebraicGeometry.Sites.Fpqc
public import Tengoku.Seed.CategoryTheory.Comma.Over.StrictInitial
public import Tengoku.Seed.CategoryTheory.MorphismProperty.CommaSites
public import Tengoku.Seed.CategoryTheory.Sites.Subcanonical
public import Tengoku.Seed.CategoryTheory.Sites.SubcanonicalOver

/-!

# The pro-étale site

In this file we define the big and small pro-étale site. The big pro-étale site is
the category of schemes equipped with the pro-étale topology, which is the topology
generated by fpqc covers of weakly étale morphisms.

We prefer to work with weakly étale morphisms instead of pro-étale morphisms, since the property
of being pro-étale is not well-behaved: it is not local on the target.

We also define the small pro-étale site of a scheme `S` to be the category of schemes weakly-étale
over `S` and equip it with the induced topology.

## References

- [Bhatt, Bhargav and Scholze, Peter, The pro-étale topology for schemes][proetale2015]

-/

@[expose] public section

universe v u

open CategoryTheory MorphismProperty Limits

namespace AlgebraicGeometry.Scheme

set_option backward.isDefEq.respectTransparency.types false in
/--
Big pro-étale site: the pro-étale precoverage on the category of schemes given
by fpqc covers of weakly étale morphisms.
[Definition 4.1.1][proetale2015]
-/
def proetalePrecoverage : Precoverage Scheme.{u} :=
  propQCPrecoverage @WeaklyEtale
  deriving Precoverage.IsStableUnderBaseChange, Precoverage.IsStableUnderComposition,
    Precoverage.HasIsos

/--
@isnad1 id=le.0h0v.s4.e5890a01440c from=seed src=0 shape=0ab70a54 vocab=0c1931be
-/
lemma proetalePrecoverage_le_precoverage_weaklyEtale :
    proetalePrecoverage ≤ MorphismProperty.precoverage @WeaklyEtale :=
  le_trans inf_le_right inf_le_right

/--
@isnad1 id=le.0h0v.s4.dc3e0ed35d44 from=seed src=0 shape=836e6cbb vocab=ca287012
-/
lemma proetalePrecoverage_le_fpqcPrecoverage : proetalePrecoverage ≤ fpqcPrecoverage :=
  propQCPrecoverage_monotone fun _ _ _ _ ↦ inferInstance

/-- Big pro-étale site: the pro-étale topology on the category of schemes is
generated by the pro-étale precoverage. -/
abbrev proetaleTopology : GrothendieckTopology Scheme.{u} :=
  proetalePrecoverage.toGrothendieck

/--
@isnad1 id=eq.0h0v.s2.09154a8a3da1 from=seed src=0 shape=95347b04 vocab=8bdb2ae0
-/
lemma proetaleTopology_eq_propQCTopology : proetaleTopology = propQCTopology @WeaklyEtale := rfl

set_option backward.isDefEq.respectTransparency.types false in
/--
@isnad1 id=le.0h0v.s4.94377911e6a7 from=seed src=0 shape=836e6cbb vocab=95794e2d
-/
lemma etalePrecoverage_le_proetalePrecoverage : etalePrecoverage ≤ proetalePrecoverage := by
  rw [proetalePrecoverage, propQCPrecoverage, etalePrecoverage, le_inf_iff]
  refine ⟨precoverage_le_qcPrecoverage_of_isOpenMap fun X Y f hf ↦ f.isOpenMap, ?_⟩
  apply precoverage_mono
  intro X Y f hf
  infer_instance

/--
@isnad1 id=le.0h0v.s3.42561dd9c9de from=seed src=0 shape=836e6cbb vocab=0cdf278e
-/
lemma etaleTopology_le_proetaleTopology : etaleTopology ≤ proetaleTopology :=
  Precoverage.toGrothendieck_mono etalePrecoverage_le_proetalePrecoverage

/--
@isnad1 id=le.0h0v.s3.f2fda738094d from=seed src=0 shape=836e6cbb vocab=e018dbe4
-/
lemma proetaleTopology_le_fpqcTopology : proetaleTopology ≤ fpqcTopology :=
  Precoverage.toGrothendieck_mono proetalePrecoverage_le_fpqcPrecoverage

instance : proetaleTopology.Subcanonical :=
  .of_le proetaleTopology_le_fpqcTopology

instance {S : Scheme.{u}} (𝒰 : S.Cover (precoverage @WeaklyEtale)) (i : 𝒰.I₀) :
    WeaklyEtale (𝒰.f i) :=
  𝒰.map_prop i

set_option backward.isDefEq.respectTransparency.types false in
/--
The (small) pro-étale site of a scheme `S`: Its objects are the schemes weakly étale over `S`.
We prefer to work with weakly étale morphisms instead of pro-étale morphisms, since the property
of being pro-étale is not well-behaved: it is not local on the target.
[Definition 4.1.1][proetale2015]
-/
@[stacks 098K]
protected def ProEt (S : Scheme.{u}) : Type _ :=
  MorphismProperty.Over @WeaklyEtale ⊤ S
  deriving Category, HasFiniteLimits

namespace ProEt

variable (S : Scheme.{u})

instance (U : S.ProEt) : WeaklyEtale U.hom := U.prop

variable {S} in
/-- Construct an object of the pro-étale site of `S` by giving a weakly étale morphism
`f : X ⟶ S`. -/
@[simps!]
protected def mk {X : Scheme.{u}} (f : X ⟶ S) [WeaklyEtale f] : S.ProEt :=
  MorphismProperty.Over.mk _ f ‹_›

/-- The forgetful functor the pro-étale site of `S` to schemes over `S`. -/
@[simps!]
protected def forget : S.ProEt ⥤ Over S :=
  MorphismProperty.Over.forget @WeaklyEtale ⊤ S

/-- The forgetful functor from the pro-étale site of `S` to schemes over `S` is fully faithful. -/
def forgetFullyFaithful : (ProEt.forget S).FullyFaithful :=
  MorphismProperty.Comma.forgetFullyFaithful _ _ _

set_option backward.isDefEq.respectTransparency.types false in
instance : (ProEt.forget S).Full :=
  inferInstanceAs <| (MorphismProperty.Over.forget _ _ _).Full

set_option backward.isDefEq.respectTransparency.types false in
instance : (ProEt.forget S).Faithful :=
  inferInstanceAs <| (MorphismProperty.Over.forget _ _ _).Faithful

set_option backward.isDefEq.respectTransparency.types false in
instance : PreservesFiniteLimits (ProEt.forget S) :=
  inferInstanceAs <| PreservesFiniteLimits (MorphismProperty.Over.forget _ _ _)

instance : RepresentablyFlat (ProEt.forget S) :=
  flat_of_preservesFiniteLimits _

set_option backward.isDefEq.respectTransparency.types false in
instance : (ProEt.forget S).LocallyCoverDense (proetaleTopology.over S) := by
  apply MorphismProperty.locallyCoverDense_forget_of_le
  exact proetalePrecoverage_le_precoverage_weaklyEtale

/-- The pro-étale precoverage on the small pro-étale site. -/
def precoverage : Precoverage S.ProEt :=
  proetalePrecoverage.comap (ProEt.forget S ⋙ Over.forget S)

/-- The pro-étale topology on the small pro-étale site. -/
abbrev topology : GrothendieckTopology S.ProEt :=
  (precoverage S).toGrothendieck

set_option backward.isDefEq.respectTransparency.types false in
instance : (ProEt.forget S).IsContinuous (topology S) (proetaleTopology.over S) := by
  rw [Functor.isContinuous_iff_coverPreserving]
  exact coverPreserving_comap_forget _ proetalePrecoverage_le_precoverage_weaklyEtale

set_option backward.isDefEq.respectTransparency.types false in
/--
@isnad1 id=eq.0h1v.s4.08cdfe3f8d52 from=seed src=0 shape=765ccd16 vocab=d4142355
-/
lemma topology_eq_inducedTopology :
    topology S = (ProEt.forget S).inducedTopology (proetaleTopology.over S) :=
  MorphismProperty.toGrothendieck_comap_forget_eq_inducedTopology
    _ proetalePrecoverage_le_precoverage_weaklyEtale

instance : (ProEt.forget S ⋙ Over.forget S).IsContinuous (ProEt.topology S) proetaleTopology :=
  Functor.isContinuous_comp _ _ _ (proetaleTopology.over S) _

instance : (topology S).Subcanonical :=
  GrothendieckTopology.subcanonical_of_full_of_faithful (ProEt.forget S) _ (proetaleTopology.over S)

set_option backward.isDefEq.respectTransparency.types false in
/-- If `S` is the empty scheme, the pro-étale site over `S` is a point. -/
noncomputable def equivOfIsEmpty [IsEmpty S] : S.ProEt ≌ Discrete PUnit :=
  MorphismProperty.overEquivOfIsInitial _ _ _ isInitialOfIsEmpty

set_option backward.defeqAttrib.useBackward true in
variable {S} in
set_option backward.isDefEq.respectTransparency false in
/--
@isnad1 id=mem.0h2v.s8.49a5c07be246 from=seed src=0 shape=10f8149d vocab=01c423f0
-/
lemma bot_mem_topology (X : S.ProEt) [IsEmpty X.left] : ⊥ ∈ topology S X := by
  rw [topology, ← Sieve.generate_bot]
  refine Precoverage.generate_mem_toGrothendieck ?_
  simp [precoverage, proetalePrecoverage, bot_mem_propQCPrecoverage]

/--
@isnad1 id=eq.0h1v.s6.03a2eae613b9 from=seed src=0 shape=48744792 vocab=990339ce
-/
lemma topology_eq_top_of_isEmpty [IsEmpty S] : topology S = ⊤ := by
  rw [GrothendieckTopology.eq_top_iff]
  intro X
  have : IsEmpty X.left := X.hom.base.1.1.isEmpty (β := S)
  exact bot_mem_topology _

end ProEt

end AlgebraicGeometry.Scheme
