module

public import Tengoku

public section

variable {α β : Type*} {mα : MeasurableSpace α} {mβ : MeasurableSpace β} {p : Prop}

-- TODO: Protect `Measurable.dite`
@[fun_prop]
lemma Measurable.dite_const [Decidable p] {f : p → α → β} {g : ¬ p → α → β}
    (hf : ∀ h, Measurable (f h)) (hg : ∀ h, Measurable (g h)) : Measurable (_root_.dite p f g) := by
  split <;> simp [*]

-- FIXME: Get this generated by `to_fun`
@[fun_prop]
lemma Measurable.fun_dite_const [Decidable p] {f : p → α → β} {g : ¬ p → α → β}
    (hf : ∀ h, Measurable (f h)) (hg : ∀ h, Measurable (g h)) :
    Measurable fun a ↦ if h : p then f h a else g h a := by
  split <;> simp [*]

-- TODO: Protect `Measurable.ite`
@[fun_prop]
lemma Measurable.ite_const [Decidable p] {f g : α → β} (hf : Measurable f) (hg : Measurable g) :
    Measurable (_root_.ite p f g) := by
  split <;> simp [*]

-- FIXME: Get this generated by `to_fun`
@[fun_prop]
lemma Measurable.fun_ite_const [Decidable p] {f g : α → β} (hf : Measurable f) (hg : Measurable g) :
    Measurable fun a ↦ if p then f a else g a := by
  split <;> simp [*]
