/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan

# Concrete projection operator for the TRAE rate theorem

This file defines the concrete projection operator
    `T h := Π_{Q̄} ∘ E[· | σ(Z)]`
used in the simplified rate theorem of
`doc/basic_concepts/po/estimation/trae_inverse_problems.tex` (lines 250–384).

## Design

`Setup.lean` keeps `Hbar`, `Qbar` as plain function sets without
Hilbert structure, since the mixed-bias proof only needs algebraic linearity.
The rate theorem requires the two different Hilbert spaces used in NPIV:
`L²(σ(X))` for primal functions and `L²(σ(Z))` for instrument functions.
They are represented by Mathlib's `lpMeas` subspaces of ambient `L²(μ)`.
The algebraic candidate submodules `Hbar_L2` and `Qbar_L2` live inside these
respective spaces. Only `Qbar_L2` is equipped with an orthogonal-projection
witness here, which in particular supplies the closedness needed by `T`.

The sigma-algebras generated by `X` and `Z` are encoded as the corresponding
comaps along `xOf ∘ W` and `zOf ∘ W`, with proofs that both are below the
ambient sigma-algebra.

The operator `T : L²(σ(X)) → L²(σ(Z))` is defined on the full primal
Hilbert space: it includes its input into ambient L², applies conditional
expectation given σ(Z), and projects inside the closed instrument candidate
space. Its adjoint likewise returns to the full `L²(σ(X))`, not to the
candidate submodule `Hbar_L2`. Thus this operator and the downstream spectral
construction are an ambient-primal-space specialization, not the paper's
general operator restricted between two closed candidate subspaces.

The single population identity exported here, `T_inner_eq_integral`, is what
the rate theorem consumes.  Its proof combines `condExpL2` self-adjointness
with the orthogonality characterization of `Qbar_L2`-projection; it is fully
proved.

The adjoint `T*` and the self-adjoint composite `T†T` are bundled in
`Operator/Adjoint.lean`; this file focuses on the unbundled projection operator
and the population identity needed by the DR rate argument.
-/

module
public import Tengoku.Causalean.Causalean.Estimation.NPIV.Setup
public import Tengoku

/-!
Extends the inverse-problem system with population operators for NPIV
estimation. The module defines the operator interface connecting structural
functions, instruments, and conditional-moment equations.
-/

@[expose] public section

namespace Causalean
namespace Estimation
namespace NPIV

open MeasureTheory
open scoped InnerProductSpace

/-! ## Operator-system extension of `InverseProblemSystem` -/

/-- An **operator system**: an `InverseProblemSystem` enriched with the L² data needed to
define the concrete population projection operator `T = Π_{Q̄} ∘ E[· | σ(Z)]`. On top of the
base system it packages [the sigma-algebras generated by the covariate `X` and instrument
`Z`](hyp:m_X,m_Z), with the facts that [both are coarser than the ambient sigma-algebra on
the sample space](hyp:m_X_le,m_Z_le) and [coincide with the sigma-algebras pulled back along
`X` and `Z`](hyp:m_X_eq,m_Z_eq), that [the ambient probability measure is
finite](hyp:isFiniteMeasure), and [candidate submodules of `L²(σ(X))` and
`L²(σ(Z))`](hyp:Hbar_L2,Qbar_L2), with the instrument-side space [having an orthogonal
projection](hyp:Qbar_L2_hasProj);
finally, every candidate primal or dual function is [square-integrable once composed with the
covariate or instrument map](hyp:toHbarL2,toQbarL2), with [its `L²` class coherently landing
inside the primal submodule](hyp:hbar_mem_L2) and the analogous coherence on the instrument
side. -/
structure OperatorSystem
    (Ω : Type*) [m₀ : MeasurableSpace Ω] (μ : Measure Ω)
    extends InverseProblemSystem Ω μ where
  /-- The σ-algebra generated by `X = xOf ∘ W : Ω → 𝒳`. -/
  m_X : MeasurableSpace Ω
  /-- `m_X` is coarser than `m₀`. -/
  m_X_le : m_X ≤ m₀
  /-- `m_X` is the pullback sigma-algebra generated by `X`. -/
  m_X_eq : m_X =
    @MeasurableSpace.comap Ω 𝒳 (fun ω => xOf (W ω)) inst𝒳
  /-- The σ-algebra generated by `Z = zOf ∘ W : Ω → 𝒵`. -/
  m_Z : MeasurableSpace Ω
  /-- `m_Z` is coarser than `m₀`. -/
  m_Z_le : m_Z ≤ m₀
  /-- (Optional consistency:) `m_Z = comap (zOf ∘ W) inst𝒵`.  This pins the
  σ-algebra to the one generated by `Z`. -/
  m_Z_eq : m_Z =
    @MeasurableSpace.comap Ω 𝒵 (fun ω => zOf (W ω)) inst𝒵
  /-- `μ` is finite (sufficient for the conditional-expectation identities
  used in the rate proof). -/
  isFiniteMeasure : IsFiniteMeasure μ
  /-- L² realization of `Hbar`, as a submodule of `L²(σ(X))`. -/
  Hbar_L2 : Submodule ℝ (@lpMeas Ω ℝ ℝ _ _ _ m_X m₀ 2 μ)
  /-- L² realization of `Qbar`, as a submodule of `L²(σ(Z))`. The
  following projection field supplies its closedness. -/
  Qbar_L2 : Submodule ℝ (@lpMeas Ω ℝ ℝ _ _ _ m_Z m₀ 2 μ)
  /-- `Qbar_L2` has an orthogonal projection (in particular, is closed). -/
  Qbar_L2_hasProj : Qbar_L2.HasOrthogonalProjection
  /-- Embedding witness: for every `h ∈ Hbar`, the function
  `ω ↦ h (X ω) = h (xOf (W ω))` is square-integrable. -/
  toHbarL2 : ∀ h ∈ Hbar, MemLp (fun ω => h (xOf (W ω))) 2 μ
  /-- Embedding witness: for every `q ∈ Qbar`, the function
  `ω ↦ q (Z ω) = q (zOf (W ω))` is square-integrable. -/
  toQbarL2 : ∀ q ∈ Qbar, MemLp (fun ω => q (zOf (W ω))) 2 μ
  /-- Coherence: the `Lp` class of `h ∘ X` lies in the submodule
  `Hbar_L2`. -/
  hbar_mem_L2 :
    ∀ h (hh : h ∈ Hbar),
      let hLp := (toHbarL2 h hh).toLp _
      let hMeas : hLp ∈ @lpMeas Ω ℝ ℝ _ _ _ m_X m₀ 2 μ := by
        rw [mem_lpMeas_iff_aestronglyMeasurable]
        exact ((meas_of_Hbar h hh).comp
          (by rw [m_X_eq]; exact comap_measurable _)).aestronglyMeasurable.congr
            (toHbarL2 h hh).coeFn_toLp.symm
      (⟨hLp, hMeas⟩ : @lpMeas Ω ℝ ℝ _ _ _ m_X m₀ 2 μ) ∈ Hbar_L2
  /-- Coherence: the `Lp` class of `q ∘ Z` lies in `Qbar_L2`. -/
  qbar_mem_L2 :
    ∀ q (hq : q ∈ Qbar),
      let qLp := (toQbarL2 q hq).toLp _
      let qMeas : qLp ∈ @lpMeas Ω ℝ ℝ _ _ _ m_Z m₀ 2 μ := by
        rw [mem_lpMeas_iff_aestronglyMeasurable]
        exact ((meas_of_Qbar q hq).comp
          (by rw [m_Z_eq]; exact comap_measurable _)).aestronglyMeasurable.congr
            (toQbarL2 q hq).coeFn_toLp.symm
      (⟨qLp, qMeas⟩ : @lpMeas Ω ℝ ℝ _ _ _ m_Z m₀ 2 μ) ∈ Qbar_L2

namespace OperatorSystem

variable {Ω : Type*} [m₀ : MeasurableSpace Ω] {μ : Measure Ω}

/-- For [an NPIV operator system](hyp:S), [the primal Hilbert space](goal) is the space of
square-integrable random variables measurable with respect to the sigma-algebra generated by
the covariate `X`. -/
noncomputable abbrev PrimalL2 (S : OperatorSystem Ω μ) :=
  @lpMeas Ω ℝ ℝ _ _ _ S.m_X inferInstance 2 μ

/-- For [an NPIV operator system](hyp:S), [the instrument Hilbert space](goal) is the space of
square-integrable random variables measurable with respect to the sigma-algebra generated by
the instrument `Z`. -/
noncomputable abbrev InstrumentL2 (S : OperatorSystem Ω μ) :=
  @lpMeas Ω ℝ ℝ _ _ _ S.m_Z inferInstance 2 μ

/-- For [an NPIV operator system](hyp:S), [its primal Hilbert space is complete](goal).
@isnad1 id=complete.0h3v.s12.fdbbeeec6480 from=translated src=- shape=50ad2fa2 vocab=1280dd34
-/
noncomputable instance instCompleteSpacePrimalL2 (S : OperatorSystem Ω μ) :
    CompleteSpace S.PrimalL2 := by
  letI : Fact (S.m_X ≤ m₀) := ⟨S.m_X_le⟩
  infer_instance

/-- For [an NPIV operator system](hyp:S), [its instrument Hilbert space is complete](goal).
@isnad1 id=complete.0h3v.s12.c62b9d94e829 from=translated src=- shape=50ad2fa2 vocab=84c326dc
-/
noncomputable instance instCompleteSpaceInstrumentL2 (S : OperatorSystem Ω μ) :
    CompleteSpace S.InstrumentL2 := by
  letI : Fact (S.m_Z ≤ m₀) := ⟨S.m_Z_le⟩
  infer_instance

/-- For [an NPIV operator system](hyp:S) and [a covariate function belonging to its primal candidate set](hyp:hh), [the lifted primal candidate is its equivalence class in `L²(σ(X))`](goal).

Lift `h ∈ Hbar` to its L² class
`(h ∘ X)_{Lp} ∈ Lp ℝ 2 μ`.  This is just a name. -/
noncomputable def hL2 (S : OperatorSystem Ω μ) {h : S.𝒳 → ℝ}
    (hh : h ∈ S.Hbar) : S.PrimalL2 :=
  let hLp := (S.toHbarL2 h hh).toLp _
  have hX : @Measurable Ω S.𝒳 S.m_X S.inst𝒳 (fun ω => S.xOf (S.W ω)) := by
    rw [S.m_X_eq]
    exact comap_measurable _
  have hm : hLp ∈ S.PrimalL2 := by
    rw [mem_lpMeas_iff_aestronglyMeasurable]
    exact ((S.meas_of_Hbar h hh).comp hX).aestronglyMeasurable.congr
      (S.toHbarL2 h hh).coeFn_toLp.symm
  ⟨hLp, hm⟩

/-- For [an NPIV operator system](hyp:S) and [an instrument function belonging to its dual candidate set](hyp:hq), [the lifted dual candidate is its equivalence class in `L²(σ(Z))`](goal).

Lift `q ∈ Qbar` to its L² class
`(q ∘ Z)_{Lp} ∈ Lp ℝ 2 μ`. -/
noncomputable def qL2 (S : OperatorSystem Ω μ) {q : S.𝒵 → ℝ}
    (hq : q ∈ S.Qbar) : S.InstrumentL2 :=
  let qLp := (S.toQbarL2 q hq).toLp _
  have hZ : @Measurable Ω S.𝒵 S.m_Z S.inst𝒵 (fun ω => S.zOf (S.W ω)) := by
    rw [S.m_Z_eq]
    exact comap_measurable _
  have hm : qLp ∈ S.InstrumentL2 := by
    rw [mem_lpMeas_iff_aestronglyMeasurable]
    exact ((S.meas_of_Qbar q hq).comp hZ).aestronglyMeasurable.congr
      (S.toQbarL2 q hq).coeFn_toLp.symm
  ⟨qLp, hm⟩

/-! ## The projection operator `T`

We define `T` from `L²(σ(X))` to `L²(σ(Z))`. Composition order:
`T = orthogonalProjectionFn Qbar_L2 ∘ condExpL2 ℝ ℝ m_Z_le ∘ inclusion`. -/

/-- For [an NPIV operator system](hyp:S), [the conditional-expectation operator maps every ambient $L^2$ random variable to its conditional expectation given the σ-algebra generated by the instrument](goal).

The conditional-expectation step `E[· | σ(Z)]`, viewed as a self-map
of `Lp ℝ 2 μ` (via the canonical inclusion of the σ(Z)-measurable
subspace).

This is the composition
`Lp 2 μ →L[ℝ] lpMeas ℝ ℝ m_Z 2 μ → Lp 2 μ`
where the second arrow is the structural inclusion (each `lpMeas` element
*is* an `Lp` element). -/
noncomputable def condExpStep (S : OperatorSystem Ω μ) :
    S.PrimalL2 → S.InstrumentL2 :=
  haveI := S.isFiniteMeasure
  fun f => MeasureTheory.condExpL2 ℝ ℝ S.m_Z_le (f : Lp ℝ 2 μ)

/-- For [an NPIV operator system](hyp:S) and [an element of the full primal
space `L²(σ(X))`](hyp:f), [the NPIV projection operator is the orthogonal
projection onto the closed dual candidate space of that element's conditional
expectation given the instrument](goal).

The concrete projection operator
`T = Π_{Q̄} ∘ E[· | σ(Z)]`.

Its domain is all of `L²(σ(X))`, rather than the subtype `Hbar_L2`; the
rate theorem applies it to
`S.hL2 hh - S.hL2 hh' = (S.hL2 hh) - (S.hL2 hh')`. -/
noncomputable def T (S : OperatorSystem Ω μ) (f : S.PrimalL2) : S.InstrumentL2 :=
  haveI := S.Qbar_L2_hasProj
  S.Qbar_L2.orthogonalProjectionFn (S.condExpStep f)

/-! ## Linearity helpers for `T`

`T = Π_{Q̄} ∘ condExpL2` is a composition of two ℝ-linear maps:

* `condExpL2 ℝ ℝ S.m_Z_le : Lp 2 μ →L[ℝ] (lpMeas ℝ ℝ S.m_Z 2 μ)`, then
  embedded into `Lp 2 μ` (linear by definition of `condExpStep`).
* `Submodule.orthogonalProjectionFn` agrees with the bundled
  `Submodule.orthogonalProjection : E →L[ℝ] K` followed by the
  subtype embedding (`Submodule.orthogonalProjectionFn_eq`), so it is
  ℝ-linear too.

We expose the two basic linearity lemmas the rate proof consumes
(`T_add`, `T_sub`); a `LinearMap` form is not needed at this stage. -/

/-- `condExpStep` distributes over subtraction (linearity of
`condExpL2`).
@isnad1 id=eq.0h5v.s14.357d6d05c0b4 from=translated src=- shape=cade7323 vocab=42cc1527
-/
lemma condExpStep_sub (S : OperatorSystem Ω μ) (f g : S.PrimalL2) :
    S.condExpStep (f - g) = S.condExpStep f - S.condExpStep g := by
  haveI := S.isFiniteMeasure
  unfold condExpStep
  simp [map_sub]

/-- `T` distributes over subtraction.
@isnad1 id=eq.0h5v.s14.038d266ff2de from=translated src=- shape=cade7323 vocab=b516cea1
-/
lemma T_sub (S : OperatorSystem Ω μ) (f g : S.PrimalL2) :
    S.T (f - g) = S.T f - S.T g := by
  haveI := S.Qbar_L2_hasProj
  unfold T
  rw [S.condExpStep_sub]
  -- Reduce `orthogonalProjectionFn (a - b)` to
  -- `orthogonalProjectionFn a - orthogonalProjectionFn b` via the
  -- rfl-equality `orthogonalProjectionFn = ((orthogonalProjection ·) : _)`
  -- and `map_sub` on the bundled CLM `orthogonalProjection`.
  change ((S.Qbar_L2.orthogonalProjectionOnto (S.condExpStep f - S.condExpStep g)) : S.InstrumentL2)
        = ((S.Qbar_L2.orthogonalProjectionOnto (S.condExpStep f)) : S.InstrumentL2)
            - ((S.Qbar_L2.orthogonalProjectionOnto (S.condExpStep g)) : S.InstrumentL2)
  rw [map_sub]
  rfl

/-- `T` distributes over addition (companion to `T_sub`).
@isnad1 id=eq.0h5v.s14.1f4f0d43417f from=translated src=- shape=cade7323 vocab=bd5dad5d
-/
lemma T_add (S : OperatorSystem Ω μ) (f g : S.PrimalL2) :
    S.T (f + g) = S.T f + S.T g := by
  haveI := S.Qbar_L2_hasProj
  haveI := S.isFiniteMeasure
  unfold T condExpStep
  change ((S.Qbar_L2.orthogonalProjectionOnto
            (MeasureTheory.condExpL2 ℝ ℝ S.m_Z_le ((f + g : S.PrimalL2) : Lp ℝ 2 μ))) : S.InstrumentL2)
        = ((S.Qbar_L2.orthogonalProjectionOnto
            (MeasureTheory.condExpL2 ℝ ℝ S.m_Z_le (f : Lp ℝ 2 μ))) : S.InstrumentL2)
          + ((S.Qbar_L2.orthogonalProjectionOnto
            (MeasureTheory.condExpL2 ℝ ℝ S.m_Z_le (g : Lp ℝ 2 μ))) : S.InstrumentL2)
  simp [map_add]

/-! ## Population identity

The rate theorem (`trae_inverse_problems.tex` lines 250–384) needs exactly
one population identity for `T`:

    ⟨T (h - h'), f⟩_{L²(μ)}
      = ∫ ω, (h (X ω) - h' (X ω)) · f (Z ω) ∂μ

for `h, h' ∈ Hbar` and `f ∈ Qbar`.  Sketch of proof:

1.  By `Submodule.orthogonalProjectionFn_inner_eq_zero` applied to
    `S.Qbar_L2` and `S.qL2 hf ∈ S.Qbar_L2`, the projection step is
    invisible in the inner product:
        ⟨T u, qL2 hf⟩ = ⟨condExpStep u, qL2 hf⟩.

2.  By `MeasureTheory.inner_condExpL2_left_eq_right` (self-adjointness of
    `condExpL2`) and the fact that `qL2 hf` is already
    σ(Z)-measurable (so `condExpL2 (qL2 hf) = qL2 hf`), we get
        ⟨condExpStep u, qL2 hf⟩ = ⟨u, qL2 hf⟩.

3.  Unwinding `Lp` inner products to integrals (`L2.inner_def`) yields
    the right-hand side.

Step 2 needs `S.qL2 hf` to actually live in the σ(Z)-measurable subspace;
that is the content of `qbar_aestrongly_measurable_mZ` below (proven from
`m_Z_eq` and `meas_of_Qbar`, no extra hypothesis required). -/

/-- For [an NPIV operator system](hyp:S), [every instrument function belonging to its critic
space is almost-everywhere strongly measurable after composition with the instrument map](goal).

This property is derivable from `m_Z_eq` and `meas_of_Qbar`; see
`qbar_aestrongly_measurable_mZ` below. It remains a definition so existing
call sites can pass it as a separate hypothesis. -/
def QbarAEMeasurableMZ (S : OperatorSystem Ω μ) : Prop :=
  ∀ f, ∀ g : f ∈ S.Qbar,
    AEStronglyMeasurable[S.m_Z] (fun ω => f (S.zOf (S.W ω))) μ

/-- `q ∘ zOf ∘ W` is `m_Z`-strongly measurable for every `q ∈ Qbar`.
Direct consequence of `m_Z_eq : m_Z = comap (zOf ∘ W) inst𝒵` and
`meas_of_Qbar`: the canonical map `(zOf ∘ W) : Ω → 𝒵` is measurable from
`comap (zOf ∘ W) inst𝒵` to `inst𝒵` (`comap_measurable`), so its
composition with the `inst𝒵`-measurable `q : 𝒵 → ℝ` is
`m_Z`-measurable, hence `m_Z`-strongly measurable into ℝ.
@isnad1 id=qbaraeme.0h3v.s4.5ca6660f80d2 from=translated src=- shape=e4514752 vocab=431ce9e5
-/
lemma qbar_aestrongly_measurable_mZ (S : OperatorSystem Ω μ) :
    S.QbarAEMeasurableMZ := by
  intro q hq
  have hZ : @Measurable Ω S.𝒵 S.m_Z S.inst𝒵 (fun ω => S.zOf (S.W ω)) := by
    rw [S.m_Z_eq]
    exact comap_measurable _
  have hq_meas : @Measurable S.𝒵 ℝ S.inst𝒵 _ q := S.meas_of_Qbar q hq
  have h_meas :
      @Measurable Ω ℝ S.m_Z _ (fun ω => q (S.zOf (S.W ω))) :=
    @Measurable.comp Ω S.𝒵 ℝ S.m_Z S.inst𝒵 _ q
      (fun ω => S.zOf (S.W ω)) hq_meas hZ
  exact h_meas.aestronglyMeasurable

/-- **Population identity for `T`.** Consider an operator system `S` — an inverse-problem
system enriched with an L² realization of the candidate sets — and fix [two primal candidate
functions `h`, `h'` in the primal candidate set `Hbar`](hyp:hh,hh') together with [a dual
candidate function `f` in the dual candidate set `Qbar`](hyp:hf). Writing `T` for the operator
that conditions on the σ-algebra generated by the instrument `Z` and then orthogonally
projects onto the L² realization of `Qbar`, [the `L²(μ)` inner product of `T` applied to the
lifted residual `h − h'` against the lifted `f` equals the expectation of the pointwise
product `(h(X) − h'(X))·f(Z)`](goal).

    ⟨T (hL2 hh - hL2 hh'), qL2 hf⟩_{L²(μ)}
      = ∫ ω, (h (X ω) - h' (X ω)) · f (Z ω) ∂μ.

This is the only identity the simplified TRAE rate proof requires from `T`.
The proof composes:

* invisibility of `Π_{Q̄}` against a `Q̄`-element
  (`Submodule.orthogonalProjectionFn_inner_eq_zero` on the residual);
* self-adjointness of `condExpL2` and idempotence on σ(Z)-measurable
  L² classes (uses `qbar_meas_mZ`);
* unwinding `Lp` inner products to Bochner integrals.
@isnad1 id=eq.3h6v.s14.39771035ab8e from=translated src=- shape=631c38a0 vocab=7bceeb22
-/
theorem T_inner_eq_integral
    (S : OperatorSystem Ω μ)
    {h h' : S.𝒳 → ℝ} (hh : h ∈ S.Hbar) (hh' : h' ∈ S.Hbar)
    {f : S.𝒵 → ℝ} (hf : f ∈ S.Qbar) :
    inner ℝ (S.T (S.hL2 hh - S.hL2 hh')) (S.qL2 hf)
      = ∫ ω, (h (S.xOf (S.W ω)) - h' (S.xOf (S.W ω))) *
              f (S.zOf (S.W ω)) ∂μ := by
  haveI := S.isFiniteMeasure
  haveI := S.Qbar_L2_hasProj
  let u : S.PrimalL2 := S.hL2 hh - S.hL2 hh'
  have hq_mem : S.qL2 hf ∈ S.Qbar_L2 := S.qbar_mem_L2 f hf
  have h_proj :
      inner ℝ (S.T u) (S.qL2 hf) =
        inner ℝ (S.condExpStep u) (S.qL2 hf) := by
    have h_zero :
        inner ℝ (S.condExpStep u - S.Qbar_L2.orthogonalProjectionFn (S.condExpStep u))
          (S.qL2 hf) = 0 :=
      S.Qbar_L2.starProjection_inner_eq_zero (S.condExpStep u) (S.qL2 hf) hq_mem
    have h_eq :
        inner ℝ (S.condExpStep u) (S.qL2 hf) =
          inner ℝ (S.Qbar_L2.orthogonalProjectionFn (S.condExpStep u)) (S.qL2 hf) := by
      rw [inner_sub_left] at h_zero
      exact sub_eq_zero.mp h_zero
    simpa [OperatorSystem.T] using h_eq.symm
  have hq_meas :
      AEStronglyMeasurable[S.m_Z] (S.qL2 hf : Ω → ℝ) μ :=
    (S.qbar_aestrongly_measurable_mZ f hf).congr (S.toQbarL2 f hf).coeFn_toLp.symm
  have h_cond :
      inner ℝ (S.condExpStep u) (S.qL2 hf) =
        inner ℝ ((u : S.PrimalL2) : Lp ℝ 2 μ)
          ((S.qL2 hf : S.InstrumentL2) : Lp ℝ 2 μ) := by
    change inner ℝ
        ((S.condExpStep u : S.InstrumentL2) : Lp ℝ 2 μ)
        ((S.qL2 hf : S.InstrumentL2) : Lp ℝ 2 μ) =
      inner ℝ ((u : S.PrimalL2) : Lp ℝ 2 μ)
        ((S.qL2 hf : S.InstrumentL2) : Lp ℝ 2 μ)
    simpa [OperatorSystem.condExpStep] using
      (MeasureTheory.inner_condExpL2_eq_inner_fun (E := ℝ) (𝕜 := ℝ)
        S.m_Z_le (u : Lp ℝ 2 μ)
          ((S.qL2 hf : S.InstrumentL2) : Lp ℝ 2 μ) hq_meas)
  have h_inner :
      inner ℝ ((u : S.PrimalL2) : Lp ℝ 2 μ)
          ((S.qL2 hf : S.InstrumentL2) : Lp ℝ 2 μ) =
        ∫ ω, (h (S.xOf (S.W ω)) - h' (S.xOf (S.W ω))) *
              f (S.zOf (S.W ω)) ∂μ := by
    rw [MeasureTheory.L2.inner_def]
    refine integral_congr_ae ?_
    filter_upwards [Lp.coeFn_sub
        ((S.hL2 hh : S.PrimalL2) : Lp ℝ 2 μ)
        ((S.hL2 hh' : S.PrimalL2) : Lp ℝ 2 μ),
      (S.toHbarL2 h hh).coeFn_toLp, (S.toHbarL2 h' hh').coeFn_toLp,
      (S.toQbarL2 f hf).coeFn_toLp] with ω hu hhω hh'ω hfω
    calc
      ⟪((u : S.PrimalL2) : Lp ℝ 2 μ) ω,
          ((S.qL2 hf : S.InstrumentL2) : Lp ℝ 2 μ) ω⟫_ℝ
          = ⟪((S.hL2 hh : S.PrimalL2) : Lp ℝ 2 μ) ω
                - ((S.hL2 hh' : S.PrimalL2) : Lp ℝ 2 μ) ω,
              ((S.qL2 hf : S.InstrumentL2) : Lp ℝ 2 μ) ω⟫_ℝ := by
            have huω : ((u : S.PrimalL2) : Lp ℝ 2 μ) ω =
                ((S.hL2 hh : S.PrimalL2) : Lp ℝ 2 μ) ω
                  - ((S.hL2 hh' : S.PrimalL2) : Lp ℝ 2 μ) ω := by
              simpa [u, Pi.sub_apply] using hu
            rw [huω]
      _ = ⟪h (S.xOf (S.W ω)) - h' (S.xOf (S.W ω)),
            f (S.zOf (S.W ω))⟫_ℝ := by
            simp [OperatorSystem.hL2, OperatorSystem.qL2, hhω, hh'ω, hfω]
      _ = (h (S.xOf (S.W ω)) - h' (S.xOf (S.W ω))) *
            f (S.zOf (S.W ω)) := by
            change f (S.zOf (S.W ω)) *
                (h (S.xOf (S.W ω)) - h' (S.xOf (S.W ω))) =
              (h (S.xOf (S.W ω)) - h' (S.xOf (S.W ω))) *
                f (S.zOf (S.W ω))
            ring
  calc
    inner ℝ (S.T (S.hL2 hh - S.hL2 hh')) (S.qL2 hf)
        = inner ℝ (S.T u) (S.qL2 hf) := by simp [u]
    _ = inner ℝ (S.condExpStep u) (S.qL2 hf) := h_proj
    _ = inner ℝ ((u : S.PrimalL2) : Lp ℝ 2 μ)
          ((S.qL2 hf : S.InstrumentL2) : Lp ℝ 2 μ) := h_cond
    _ = ∫ ω, (h (S.xOf (S.W ω)) - h' (S.xOf (S.W ω))) *
              f (S.zOf (S.W ω)) ∂μ := h_inner

/-! ## Norm helpers

The simplified rate theorem packages two seminorms:

* the **strong norm** `‖h - h'‖_{strong} := ‖hL2 hh - hL2 hh'‖_{L²(μ)}`,
  i.e. the ambient `Lp` norm of the lifted residual;
* the **weak norm** `‖h - h'‖_{weak} := ‖T (hL2 hh - hL2 hh')‖_{L²(μ)}`,
  i.e. the `Lp` norm after projection.

We expose them on the lifted `Lp ℝ 2 μ` argument (no ambient `MemLp`
witness juggling). -/

/-- For [an NPIV operator system](hyp:_S) and [a random variable in `L²(σ(X))`](hyp:f), [the strong norm is that variable's $L^2$ norm](goal). -/
noncomputable def strongNorm (_S : OperatorSystem Ω μ) (f : _S.PrimalL2) : ℝ :=
  ‖f‖

/-- For [an NPIV operator system](hyp:S) and [a random variable in `L²(σ(X))`](hyp:f), [the weak norm is the `L²(σ(Z))` norm of its projected conditional expectation](goal).

Weak norm associated to `T`: `‖T f‖_{L²(μ)}`. -/
noncomputable def weakNorm (S : OperatorSystem Ω μ) (f : S.PrimalL2) : ℝ :=
  ‖S.T f‖

/-- The projected conditional-expectation norm is bounded by the ambient
`L²` norm.
@isnad1 id=le.0h4v.s11.4568191ddcd4 from=translated src=- shape=436d4967 vocab=1e79635b
-/
lemma weakNorm_le_strongNorm (S : OperatorSystem Ω μ) (f : S.PrimalL2) :
    S.weakNorm f ≤ S.strongNorm f := by
  haveI := S.isFiniteMeasure
  haveI := S.Qbar_L2_hasProj
  calc
    S.weakNorm f = ‖S.Qbar_L2.starProjection (S.condExpStep f)‖ := by
      rw [weakNorm, T]
    _ ≤ ‖S.condExpStep f‖ := S.Qbar_L2.norm_starProjection_apply_le (S.condExpStep f)
    _ ≤ ‖f‖ := by
      simpa [condExpStep] using
        (MeasureTheory.norm_condExpL2_le (E := ℝ) (𝕜 := ℝ) S.m_Z_le
          (f : Lp ℝ 2 μ))
    _ = S.strongNorm f := by
      rw [strongNorm]

/-- Squared strong norm of a lifted `Hbar` member, unfolded as the integral
of the squared representative.
@isnad1 id=eq.1h4v.s7.dc5d7b13092e from=translated src=- shape=a86ed580 vocab=68361ea7
-/
lemma strongNorm_sq_hL2_eq_integral
    (S : OperatorSystem Ω μ) {h : S.𝒳 → ℝ} (hh : h ∈ S.Hbar) :
    (S.strongNorm (S.hL2 hh)) ^ 2 = ∫ ω, (h (S.xOf (S.W ω))) ^ 2 ∂μ := by
  calc
    (S.strongNorm (S.hL2 hh)) ^ 2 = inner ℝ (S.hL2 hh) (S.hL2 hh) := by
      rw [OperatorSystem.strongNorm, real_inner_self_eq_norm_sq]
    _ = ∫ ω, ⟪((S.hL2 hh : S.PrimalL2) : Lp ℝ 2 μ) ω,
        ((S.hL2 hh : S.PrimalL2) : Lp ℝ 2 μ) ω⟫_ℝ ∂μ := by
      change inner ℝ
          ((S.hL2 hh : S.PrimalL2) : Lp ℝ 2 μ)
          ((S.hL2 hh : S.PrimalL2) : Lp ℝ 2 μ) = _
      rw [MeasureTheory.L2.inner_def]
    _ = ∫ ω, (h (S.xOf (S.W ω))) ^ 2 ∂μ := by
      refine integral_congr_ae ?_
      filter_upwards [(S.toHbarL2 h hh).coeFn_toLp] with ω hω
      simp [OperatorSystem.hL2, hω, pow_two]

/-- For [an NPIV operator system](hyp:S), [two primal candidate
functions](hyp:h,h'), and [their membership proofs](hyp:hh,hh'), [the strong
norm of the lifted difference equals the real extended $L^2$ norm of the
pointwise difference](goal).
@isnad1 id=eq.2h5v.s13.40263481017a from=translated src=- shape=7713b73d vocab=7176f897
-/
lemma strongNorm_hL2_sub_eq_eLpNorm_toReal
    (S : OperatorSystem Ω μ)
    {h h' : S.𝒳 → ℝ} (hh : h ∈ S.Hbar) (hh' : h' ∈ S.Hbar) :
    S.strongNorm (S.hL2 hh - S.hL2 hh')
      = (eLpNorm
          (fun ω => h (S.xOf (S.W ω)) - h' (S.xOf (S.W ω))) 2 μ).toReal := by
  rw [OperatorSystem.strongNorm]
  change
    ‖(S.toHbarL2 h hh).toLp _ - (S.toHbarL2 h' hh').toLp _‖ = _
  rw [← MemLp.toLp_sub, Lp.norm_toLp]
  rfl

end OperatorSystem

end NPIV
end Estimation
end Causalean
