/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan

# Factorization lemmas for the evaluation map

This file contains two families of factorization theorems for `evalMap`:

* **Parent factorization** (`evalMap_factors_through_parents`, §5): for an
  observed node `v`, the value `(evalMap s ℓ) v` depends on `ℓ` only through
  the parent-restricted random coordinates. Consumed by `LocalMarkov`.

* **Ancestor factorization** (`evalMap_factors_through_ancestors`, §6):
  existence-of-measurable-`g` upgrade of `ancestralFactorization` (from
  `Evaluation.lean`) to the `(fixed-anc projection, latent-anc projection)`
  form needed by the `CondIndepFun` machinery in `GlobalMarkov`.

## References

* Basic Concepts.tex, Proposition `prop:scm-evalmap`.
* Basic Concepts.tex, Lemma `lem:scm-ancestral-factor`.
-/

module
public import Tengoku.Causalean.Causalean.SCM.Model.Evaluation

/-! # Evaluation Map Factorization

This file proves that values produced by the evaluation map factor through the
appropriate parent or ancestor coordinates. These factorization results provide
the measurable-function inputs needed for local and global Markov arguments in
structural causal models.

## Main definitions and results

* `SCM.evalMap_factors_through_parents` expresses an observed node value as a
  measurable function of the evaluated random parent coordinates.
* `SCM.latentAncestorsOfNode` and `SCM.fixedAncestorsOfNode` collect the latent
  and fixed ancestor coordinates relevant to a single observed node.
* `SCM.evalMap_factors_through_ancestors` upgrades ancestral agreement into a
  measurable factorization through the fixed-ancestor and latent-ancestor
  projections.
-/

@[expose] public section

open Causalean.Graph

open Causalean.Mathlib.MeasureTheory

namespace Causalean

namespace SCM

variable {N : Type*} [DecidableEq N] [Fintype N]
variable {Ω : N → Type*} [∀ n, MeasurableSpace (Ω n)]

open scoped MeasureTheory ProbabilityTheory

-- ============================================================
-- § 5. Parent factorization of `evalMap` at observed nodes
-- ============================================================

/-- **Parent factorization of `evalMap` at observed nodes.** Fix a structural causal model
    `M`, a fixed-value assignment `s`, and a node `v` with [`v` an observed node](hyp:hv).
    Then [there is a measurable function `g` of the assignment restricted to `v`'s random
    parent coordinates such that, for every latent assignment `ℓ`, the evaluated value at `v`
    equals `g` applied to that restriction of the joint evaluation](goal).

    **Parent factorization of `evalMap` at observed nodes.**

    For an observed `v`, the value `(evalMap s ℓ) v` depends on `ℓ` only through
    the parent-restricted random coordinates of `evalMap s ℓ`.  Equivalently, there
    exists a measurable `g` (depending on `s`) such that
    `(evalMap s ℓ) ⟨v, _⟩ = g (valuesProjection _ (evalMap s ℓ))` for all `ℓ`,
    where the projection is to `M.dag.parents v ∩ M.randomVars`.

    Consumed by `GlobalMarkov.full_local_markov` to discharge the structural-equation
    measurability step: `π_{{v}} ∘ evalMap s` is measurable with respect to the
    σ-algebra generated by `π_{Pa(v) ∩ RV} ∘ evalMap s`. -/
theorem evalMap_factors_through_parents (M : Causalean.SCM N Ω)
    (s : FixedValues M) (v : SWIGNode N) (hv : v ∈ M.observed) :
    ∃ g : ValuesOn (M.dag.parents v ∩ M.randomVars) (swigΩ Ω) → swigΩ Ω v,
      Measurable g ∧
      ∀ ℓ : LatentValues M,
        M.evalMap s ℓ ⟨v, Finset.mem_union_left _ hv⟩ =
          g (valuesProjection (Finset.inter_subset_right
                (s₁ := M.dag.parents v) (s₂ := M.randomVars))
              (M.evalMap s ℓ)) := by
  classical
  -- Disjointness helper: a random-root node is not fixed.
  have hfix_disj_unobs : ∀ w : SWIGNode N, w ∈ M.unobserved → w ∉ M.fixed := by
    intro w hu hf
    obtain ⟨n, hn⟩ := M.fixed_is_fixed w hf
    obtain ⟨m, hm⟩ := M.unobserved_is_random w hu
    rw [hn] at hm; cases hm
  -- Build `g`: for each parent `w`, either read `s` (if fixed) or read the
  -- projection `t` (otherwise).  `w ∈ parents v` lands in `fixed ∪ randomVars`
  -- via `dag_edges_classified`.
  refine ⟨fun t =>
      M.structFun ⟨v, hv⟩ (fun w : {w // w ∈ M.dag.parents v} =>
        if hfix : w.val ∈ M.fixed then s ⟨w.val, hfix⟩
        else
          have hedge : M.dag.edge w.val v := M.dag.mem_parents.mp w.property
          have hrand : w.val ∈ M.randomVars := by
            rcases Finset.mem_union.mp
                (M.dag_edges_classified _ _ hedge).1 with h1 | h2
            · rcases Finset.mem_union.mp h1 with hfx | hob
              · exact absurd hfx hfix
              · exact Finset.mem_union_left _ hob
            · exact Finset.mem_union_right _ h2
          t ⟨w.val, Finset.mem_inter.mpr ⟨w.property, hrand⟩⟩),
    ?_, ?_⟩
  · -- Measurability: structFun ∘ (assembly of constants and coord-reads).
    refine (M.structFun_measurable ⟨v, hv⟩).comp ?_
    refine measurable_pi_lambda _ (fun w => ?_)
    by_cases hfix : w.val ∈ M.fixed
    · simp only [dite_eq_left hfix]
      exact measurable_const
    · simp only [dite_eq_right hfix]
      exact measurable_pi_apply _
  · -- Pointwise agreement via `evalMap_observed_unfold`.
    intro ℓ
    rw [evalMap_observed_unfold M s ℓ ⟨v, hv⟩]
    congr 1
    funext w
    by_cases hfix : w.val ∈ M.fixed
    · -- Fixed parent: both sides are `s ⟨w.val, hfix⟩`.  On the unfold side
      --   need `w.val ∉ M.unobserved` to peel the first `dite`.
      have huo : w.val ∉ M.unobserved := fun hu =>
        hfix_disj_unobs _ hu hfix
      simp only [dite_eq_right huo, dite_eq_left hfix]
    · -- Non-fixed: both sides read the random coord at `w`.
      have hedge : M.dag.edge w.val v := M.dag.mem_parents.mp w.property
      have hrand : w.val ∈ M.randomVars := by
        rcases Finset.mem_union.mp (M.dag_edges_classified _ _ hedge).1 with h1 | h2
        · rcases Finset.mem_union.mp h1 with hfx | hob
          · exact absurd hfx hfix
          · exact Finset.mem_union_left _ hob
        · exact Finset.mem_union_right _ h2
      simp only [dite_eq_right hfix]
      by_cases huo : w.val ∈ M.unobserved
      · -- Unobserved parent: unfold side gives `ℓ ⟨w, huo⟩`, right side gives
        --   `evalMap s ℓ ⟨w, _⟩` which collapses to `ℓ ⟨w, huo⟩` via
        --   `evalMap_unobserved`.
        simp only [dite_eq_left huo]
        rw [valuesProjection, evalMap_unobserved M s ℓ _ huo]
      · -- Observed parent: unfold side gives `evalMap s ℓ ⟨w, _⟩`, right side
        --   is the same projection read.
        simp only [dite_eq_right huo]
        rfl

-- ============================================================
-- § 6. Ancestor factorization of `evalMap` at observed nodes
-- ============================================================

/-- For [a finite node population](hyp:N) with [measurable node-value spaces](hyp:Ω), [a structural causal model](hyp:M), and [a node](hyp:v), the [set of latent ancestors of that node](goal) consists exactly of the model's unobserved nodes that are either the node itself or ancestors of it in the directed graph. It is formed [by filtering the unobserved nodes by this condition](step:1).

    The latent ancestors of a node are the unobserved nodes equal to that node
or ancestral to it.

    Latent-or-self ancestors of `v` among `M.unobserved`.

    Finset of all unobserved nodes `u` such that `u = v` or `u` is an ancestor of
    `v` in the inductive sense (`DAG.isAncestor`).  Marked `noncomputable` and
    uses `Classical.decPred` for the filter so the definition does not rely on
    `DAG.decIsAncestor` (whose decidability instance is stable but we intentionally
    decouple here since `evalMap` is already `noncomputable`). -/
noncomputable def latentAncestorsOfNode (M : Causalean.SCM N Ω) (v : SWIGNode N) :
    Finset (SWIGNode N) :=
  letI : DecidablePred (fun u : SWIGNode N => u = v ∨ M.dag.isAncestor u v) :=
    Classical.decPred _
  M.unobserved.filter (fun u => u = v ∨ M.dag.isAncestor u v)

/-- For [a finite node population](hyp:N) with [measurable node-value spaces](hyp:Ω), [a structural causal model](hyp:M), and [a node](hyp:v), the [set of fixed ancestors of that node](goal) consists exactly of the model's fixed nodes that are either the node itself or ancestors of it in the directed graph. It is formed [by filtering the fixed nodes by this condition](step:1).

    The fixed ancestors of a node are the fixed nodes equal to that node or
ancestral to it. -/
noncomputable def fixedAncestorsOfNode (M : Causalean.SCM N Ω) (v : SWIGNode N) :
    Finset (SWIGNode N) :=
  letI : DecidablePred (fun d : SWIGNode N => d = v ∨ M.dag.isAncestor d v) :=
    Classical.decPred _
  M.fixed.filter (fun d => d = v ∨ M.dag.isAncestor d v)

/-- Membership in the latent-ancestor set means being unobserved and equal to
or ancestral to the node. -/
lemma mem_latentAncestorsOfNode (M : Causalean.SCM N Ω) {v u : SWIGNode N} :
    u ∈ M.latentAncestorsOfNode v ↔
      u ∈ M.unobserved ∧ (u = v ∨ M.dag.isAncestor u v) := by
  letI : DecidablePred (fun u : SWIGNode N => u = v ∨ M.dag.isAncestor u v) :=
    Classical.decPred _
  change u ∈ M.unobserved.filter (fun u => u = v ∨ M.dag.isAncestor u v) ↔ _
  exact Finset.mem_filter

/-- Membership in the fixed-ancestor set means being fixed and equal to or ancestral to the node. -/
lemma mem_fixedAncestorsOfNode (M : Causalean.SCM N Ω) {v d : SWIGNode N} :
    d ∈ M.fixedAncestorsOfNode v ↔
      d ∈ M.fixed ∧ (d = v ∨ M.dag.isAncestor d v) := by
  letI : DecidablePred (fun d : SWIGNode N => d = v ∨ M.dag.isAncestor d v) :=
    Classical.decPred _
  change d ∈ M.fixed.filter (fun d => d = v ∨ M.dag.isAncestor d v) ↔ _
  exact Finset.mem_filter

/-- The fixed-ancestor set is contained in the fixed node set. -/
lemma fixedAncestorsOfNode_subset (M : Causalean.SCM N Ω) (v : SWIGNode N) :
    M.fixedAncestorsOfNode v ⊆ M.fixed := by
  intro d hd
  exact ((M.mem_fixedAncestorsOfNode).mp hd).1

/-- The latent-ancestor set is contained in the unobserved node set. -/
lemma latentAncestorsOfNode_subset (M : Causalean.SCM N Ω) (v : SWIGNode N) :
    M.latentAncestorsOfNode v ⊆ M.unobserved := by
  intro u hu
  exact ((M.mem_latentAncestorsOfNode).mp hu).1

/-- **Ancestor factorization (existence form).** Fix a structural causal model `M` and a node
    `v` with [`v` an observed node](hyp:hv). Then [there is a measurable function `g` of the
    fixed-ancestor projection and the latent-ancestor projection of `v` such that, for every
    fixed-value assignment `s` and latent assignment `ℓ`, the evaluated value at `v` equals `g`
    applied to those two projections of `s` and `ℓ`](goal).

    **Ancestor factorization (existence form).**

    For every observed node `v`, there is a measurable function `g` of the
    fixed-ancestor projection of `s` and the latent-ancestor projection of `ℓ`
    that computes `(M.evalMap s ℓ) ⟨v, _⟩`.

    This upgrades the congruence form `ancestralFactorization` (with `T := {v}`)
    into an existence-of-measurable-`g` form usable by `CondIndepFun` /
    `condIndepFun_of_map` machinery in the SCM-based `globalMarkov` proof.

    The `Nonempty (Ω n)` instance is used to build a default extension of the
    ancestor-projection back to full `FixedValues` / `LatentValues` so that `g`
    can be defined by composing `M.evalMap` with the extension map. -/
theorem evalMap_factors_through_ancestors (M : Causalean.SCM N Ω)
    [∀ n, Nonempty (Ω n)]
    (v : SWIGNode N) (hv : v ∈ M.observed) :
    ∃ g : ValuesOn (M.fixedAncestorsOfNode v) (swigΩ Ω) →
          ValuesOn (M.latentAncestorsOfNode v) (swigΩ Ω) → swigΩ Ω v,
      Measurable (Function.uncurry g) ∧
      ∀ (s : FixedValues M) (ℓ : LatentValues M),
        M.evalMap s ℓ ⟨v, Finset.mem_union_left _ hv⟩ =
          g (valuesProjection (M.fixedAncestorsOfNode_subset v) s)
            (valuesProjection (M.latentAncestorsOfNode_subset v) ℓ) := by
  classical
  -- `swigΩ Ω w` is nonempty for every `w` since `Ω n` is.
  have hNEΩ : ∀ w : SWIGNode N, Nonempty (swigΩ Ω w) := by
    intro w; cases w <;> exact inferInstance
  -- Default full assignments.
  let s₀ : FixedValues M := fun d => Classical.arbitrary _
  let ℓ₀ : LatentValues M := fun u => Classical.arbitrary _
  -- Extension maps: read from projection on ancestor coords, default otherwise.
  let extend_s : ValuesOn (M.fixedAncestorsOfNode v) (swigΩ Ω) → FixedValues M :=
    fun sproj d =>
      if h : d.val ∈ M.fixedAncestorsOfNode v then
        sproj ⟨d.val, h⟩
      else
        s₀ d
  let extend_ℓ : ValuesOn (M.latentAncestorsOfNode v) (swigΩ Ω) → LatentValues M :=
    fun ℓproj u =>
      if h : u.val ∈ M.latentAncestorsOfNode v then
        ℓproj ⟨u.val, h⟩
      else
        ℓ₀ u
  have hext_s_meas : Measurable extend_s := by
    refine measurable_pi_lambda _ (fun d => ?_)
    by_cases h : d.val ∈ M.fixedAncestorsOfNode v
    · have : (fun sproj : ValuesOn (M.fixedAncestorsOfNode v) (swigΩ Ω) =>
          extend_s sproj d) = fun sproj => sproj ⟨d.val, h⟩ := by
        funext sproj; simp [extend_s, h]
      rw [this]; exact measurable_pi_apply _
    · have : (fun sproj : ValuesOn (M.fixedAncestorsOfNode v) (swigΩ Ω) =>
          extend_s sproj d) = fun _ => s₀ d := by
        funext sproj; simp [extend_s, h]
      rw [this]; exact measurable_const
  have hext_ℓ_meas : Measurable extend_ℓ := by
    refine measurable_pi_lambda _ (fun u => ?_)
    by_cases h : u.val ∈ M.latentAncestorsOfNode v
    · have : (fun ℓproj : ValuesOn (M.latentAncestorsOfNode v) (swigΩ Ω) =>
          extend_ℓ ℓproj u) = fun ℓproj => ℓproj ⟨u.val, h⟩ := by
        funext ℓproj; simp [extend_ℓ, h]
      rw [this]; exact measurable_pi_apply _
    · have : (fun ℓproj : ValuesOn (M.latentAncestorsOfNode v) (swigΩ Ω) =>
          extend_ℓ ℓproj u) = fun _ => ℓ₀ u := by
        funext ℓproj; simp [extend_ℓ, h]
      rw [this]; exact measurable_const
  refine ⟨fun sproj ℓproj =>
      M.evalMap (extend_s sproj) (extend_ℓ ℓproj) ⟨v, Finset.mem_union_left _ hv⟩,
    ?_, ?_⟩
  · -- Measurability: `evalMap` is jointly measurable; precompose with the
    --   extensions (measurable) and post-project the `v` coordinate.
    have hpair : Measurable (fun p :
        ValuesOn (M.fixedAncestorsOfNode v) (swigΩ Ω) ×
        ValuesOn (M.latentAncestorsOfNode v) (swigΩ Ω) =>
          (extend_s p.1, extend_ℓ p.2)) :=
      Measurable.prodMk (hext_s_meas.comp measurable_fst)
                       (hext_ℓ_meas.comp measurable_snd)
    have huncurry : (fun p :
        ValuesOn (M.fixedAncestorsOfNode v) (swigΩ Ω) ×
        ValuesOn (M.latentAncestorsOfNode v) (swigΩ Ω) =>
          M.evalMap (extend_s p.1) (extend_ℓ p.2)
            ⟨v, Finset.mem_union_left _ hv⟩) =
        (fun w : RandomValues M => w ⟨v, Finset.mem_union_left _ hv⟩) ∘
        (fun p => Function.uncurry M.evalMap (extend_s p.1, extend_ℓ p.2)) := by
      funext p; rfl
    change Measurable (fun p :
        ValuesOn (M.fixedAncestorsOfNode v) (swigΩ Ω) ×
        ValuesOn (M.latentAncestorsOfNode v) (swigΩ Ω) =>
        M.evalMap (extend_s p.1) (extend_ℓ p.2)
          ⟨v, Finset.mem_union_left _ hv⟩)
    rw [huncurry]
    exact (measurable_pi_apply _).comp (M.evalMap_measurable.comp hpair)
  · -- Pointwise agreement via `ancestralFactorization` with `T := {v}`.
    intro s ℓ
    symm
    have hT_sub : ({v} : Finset (SWIGNode N)) ⊆ M.observed :=
      Finset.singleton_subset_iff.mpr hv
    have hv_mem : v ∈ ({v} : Finset (SWIGNode N)) := Finset.mem_singleton.mpr rfl
    refine M.ancestralFactorization ({v} : Finset (SWIGNode N)) ?_ ?_ hv_mem hv
    · -- Agreement on fixed ancestors of {v}.
      intro d hd hAnc
      obtain ⟨v', hv', hOr⟩ := hAnc
      have hv'eq : v' = v := Finset.mem_singleton.mp hv'
      have hOr' : d = v ∨ M.dag.isAncestor d v := hv'eq ▸ hOr
      have hd_anc : d ∈ M.fixedAncestorsOfNode v :=
        (M.mem_fixedAncestorsOfNode).mpr ⟨hd, hOr'⟩
      change extend_s (valuesProjection (M.fixedAncestorsOfNode_subset v) s)
          ⟨d, hd⟩ = s ⟨d, hd⟩
      simp [extend_s, hd_anc, valuesProjection]
    · -- Agreement on latent ancestors of {v}.
      intro u hu hAnc
      obtain ⟨v', hv', hOr⟩ := hAnc
      have hv'eq : v' = v := Finset.mem_singleton.mp hv'
      have hOr' : u = v ∨ M.dag.isAncestor u v := hv'eq ▸ hOr
      have hu_anc : u ∈ M.latentAncestorsOfNode v :=
        (M.mem_latentAncestorsOfNode).mpr ⟨hu, hOr'⟩
      change extend_ℓ (valuesProjection (M.latentAncestorsOfNode_subset v) ℓ)
          ⟨u, hu⟩ = ℓ ⟨u, hu⟩
      simp [extend_ℓ, hu_anc, valuesProjection]

end SCM

end Causalean
