/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan
-/

module
public import Tengoku.Causalean.Causalean.Graph.Induce

/-! # C-Components

This file defines c-components for a Single World Intervention Graph. Two
observed variables are directly confounded when they share an unobserved parent,
and c-components are the connected components generated by that bidirected
confounding relation.

The executable reachability side is `bidirectedBFS` and `cComponentOf`, while
`cComponentSet` is the canonical order-independent component collection. The
main correctness theorem
`mem_bidirectedBFS_iff_reachable` identifies the BFS output with
`bidirectedReachable`; the partition lemmas `cComponentSet_biUnion` and
`cComponentSet_pairwise_disjoint` show that `cComponentSet` covers exactly the
observed variables with disjoint components. The boundary lemmas rule out shared
latent parents across distinct c-components and provide the induced-graph bridge
`induce_cComponentOf_eq_of_shared_unobserved_parent`. -/

@[expose] public section

namespace Causalean.Graph

variable {N : Type*} [DecidableEq N] [Fintype N]

namespace SWIGGraph

variable (G : SWIGGraph N)

/-- For [a single-world intervention graph](hyp:G) and [two split nodes](hyp:v₁,v₂), the [direct-confounding relation](goal) holds exactly when [the nodes are distinct](step:1) and [some unobserved node has a directed edge to each of them](step:2).

    Two distinct variables are **directly confounded** if they share an unobserved parent.

    Two observed variables are directly confounded when some latent root has
    directed edges into both of them; the graph invariant makes those endpoints
    observed automatically. Fixed intervention nodes play no role in this relation. -/
def directlyConfounded (v₁ v₂ : SWIGNode N) : Prop :=
  v₁ ≠ v₂ ∧
  ∃ u ∈ G.unobserved, G.dag.edge u v₁ ∧ G.dag.edge u v₂

/-- For [a finite collection of base variables with decidable equality](hyp:N), [a single-world intervention graph](hyp:G), and [two split nodes](hyp:v₁,v₂), the [decision procedure for direct confounding](goal) determines whether the nodes are distinct and have a common unobserved parent in the graph. -/
instance decDirectlyConfounded (v₁ v₂ : SWIGNode N) :
    Decidable (G.directlyConfounded v₁ v₂) :=
  inferInstanceAs (Decidable (_ ∧ ∃ _, _))

/-- For [a single-world intervention graph](hyp:G) and [a split node](hyp:v), the [bidirected-neighbor set](goal) consists exactly of the graph's observed nodes that are directly confounded with that node. -/
def bidirectedNeighbors (v : SWIGNode N) : Finset (SWIGNode N) :=
  G.observed.filter (fun w => G.directlyConfounded v w)

/-- [Bidirected reachability](goal) in [a single-world intervention graph](hyp:G) on
    [a finite base-variable population](hyp:N) [relates each observed node to
    itself](hyp:refl) and [extends a reachable chain by one direct-confounding
    link](hyp:step). Thus two observed nodes are related exactly when a finite chain of shared
    latent-parent links joins them, including a chain of length zero.

    Bidirected reachability is the reflexive-transitive closure of the
    directly-confounded relation, restricted to observed variables. Two observed
    variables are in the same C-component iff they are bidirected-reachable from
    each other. -/
inductive bidirectedReachable : SWIGNode N → SWIGNode N → Prop
  | refl {v : SWIGNode N} (hv : v ∈ G.observed) : bidirectedReachable v v
  | step {u v w : SWIGNode N} : bidirectedReachable u v → G.directlyConfounded v w →
      bidirectedReachable u w

/-- For [a single-world intervention graph](hyp:G) and [a starting split node](hyp:start), the [breadth-first bidirected-reachability set](goal) is the set reached by repeatedly adding observed nodes directly confounded with the current frontier, starting from the given node when it is observed and otherwise returning the empty set.

Compute the bidirected-reachable set from a single vertex via BFS on the
bidirected projection graph.

The internal search routine iterates bidirected-neighbor expansion from the frontier,
accumulating visited nodes until the fuel bound is exhausted or no new neighbors remain. -/
def bidirectedBFS (start : SWIGNode N) : Finset (SWIGNode N) :=
  let rec go (frontier visited : Finset (SWIGNode N)) (fuel : ℕ) :
      Finset (SWIGNode N) :=
    match fuel with
    | 0 => visited
    | fuel + 1 =>
      let newNeighbors := frontier.biUnion (G.bidirectedNeighbors) \ visited
      if newNeighbors = ∅ then visited
      else go newNeighbors (visited ∪ newNeighbors) fuel
  if start ∈ G.observed then
    go {start} {start} (Fintype.card (SWIGNode N))
  else ∅

/-- For [a single-world intervention graph](hyp:G) and [a split node](hyp:v), the [c-component associated with that node](goal) is its breadth-first bidirected-reachability set.

    The C-component of a given observed variable `v`: the maximal set of observed
    variables connected to `v` via chains of directly-confounded pairs.

    A c-component is a maximal set of observed variables connected by a chain of
    directly-confounded pairs. Fixed intervention nodes play no role in the
    component relation. -/
def cComponentOf (v : SWIGNode N) : Finset (SWIGNode N) := G.bidirectedBFS v

/-- For [a single-world intervention graph](hyp:G), the [canonical set of c-components](goal) is the set of c-components associated with its observed nodes, with duplicate components identified.

    **The set of c-components** as a `Finset` of `Finset`s — the canonical,
    order-independent index for the c-component factorization.  It is the image
    of the observed nodes under `cComponentOf` (each observed node maps to its
    own component; distinct components have distinct images, so duplicates
    collapse). Used as an index set in genuine c-component density factorization results. -/
def cComponentSet : Finset (Finset (SWIGNode N)) :=
  G.observed.image G.cComponentOf

/-! ## Basic properties of the confounding relation and its closure -/

/-- The directly-confounded relation is symmetric: if `v₁` and `v₂` share an
    unobserved parent, then so do `v₂` and `v₁` (the shared parent and the
    observed-ness conditions are symmetric in the two arguments).
@isnad1 id=directly.1h4v.s5.43187f87f1a4 from=translated src=- shape=f55a0adf vocab=c3517a18
-/
theorem directlyConfounded_symm {v₁ v₂ : SWIGNode N}
    (h : G.directlyConfounded v₁ v₂) : G.directlyConfounded v₂ v₁ := by
  obtain ⟨hne, u, hu, e1, e2⟩ := h
  exact ⟨hne.symm, u, hu, e2, e1⟩

/-- Both endpoints of a bidirected-reachability derivation are observed
    (left endpoint).
@isnad1 id=mem.1h4v.s5.f8fe555a895f from=translated src=- shape=8eee227b vocab=da3560b1
-/
theorem bidirectedReachable_observed_left {u v : SWIGNode N}
    (h : G.bidirectedReachable u v) : u ∈ G.observed := by
  induction h with
  | refl hv => exact hv
  | step _ _ ih => exact ih

/-- Both endpoints of a bidirected-reachability derivation are observed
    (right endpoint).
@isnad1 id=mem.1h4v.s5.3b6b301efb71 from=translated src=- shape=6ced5907 vocab=da3560b1
-/
theorem bidirectedReachable_observed_right {u v : SWIGNode N}
    (h : G.bidirectedReachable u v) : v ∈ G.observed := by
  induction h with
  | refl hv => exact hv
  | step _ hconf _ =>
    obtain ⟨_, u, hu, _, huw⟩ := hconf
    exact G.all_children_in_observed u
      (Finset.mem_union_left _ (Finset.mem_union_left _ hu))
      (G.dag.mem_children.mpr huw)

/-- Prepend a directly-confounded step at the head of a reachability chain:
    if `u` and `v` are directly confounded and `v` reaches `w`, then `u`
    reaches `w`. Proved by induction on the `v`-to-`w` derivation.
@isnad1 id=bidirect.2h5v.s5.87d72bfbba30 from=translated src=- shape=ab73b7a3 vocab=5c049f05
-/
theorem bidirectedReachable_head {u v w : SWIGNode N}
    (huv : G.directlyConfounded u v) (hvw : G.bidirectedReachable v w) :
    G.bidirectedReachable u w := by
  induction hvw with
  | refl hv =>
    obtain ⟨hne, x, hx, hux, hxv⟩ := huv
    have huObs : u ∈ G.observed :=
      G.all_children_in_observed x
        (Finset.mem_union_left _ (Finset.mem_union_left _ hx))
        (G.dag.mem_children.mpr hux)
    exact bidirectedReachable.step (bidirectedReachable.refl huObs)
      ⟨hne, x, hx, hux, hxv⟩
  | step _ hconf ih =>
    exact bidirectedReachable.step ih hconf

/-- Bidirected reachability is symmetric.
@isnad1 id=bidirect.1h4v.s5.17c5f06e583d from=translated src=- shape=f55a0adf vocab=2b883b44
-/
theorem bidirectedReachable_symm {u v : SWIGNode N}
    (h : G.bidirectedReachable u v) : G.bidirectedReachable v u := by
  induction h with
  | refl hv => exact bidirectedReachable.refl hv
  | step _ hconf ih =>
    exact bidirectedReachable_head G (G.directlyConfounded_symm hconf) ih

/-- Bidirected reachability is transitive.
@isnad1 id=bidirect.2h5v.s5.b7ea6e018d2a from=translated src=- shape=d1c2c38f vocab=2b883b44
-/
theorem bidirectedReachable_trans {u v w : SWIGNode N}
    (huv : G.bidirectedReachable u v) (hvw : G.bidirectedReachable v w) :
    G.bidirectedReachable u w := by
  induction hvw with
  | refl _ => exact huv
  | step _ hconf ih => exact bidirectedReachable.step ih hconf

/-! ## Structural invariants of the BFS routine -/

/-- The bidirected neighbors of a node are observed.
@isnad1 id=le.0h3v.s5.1d4479a2c091 from=translated src=- shape=154b6303 vocab=cbc5c1cd
-/
theorem bidirectedNeighbors_subset_observed (v : SWIGNode N) :
    G.bidirectedNeighbors v ⊆ G.observed := by
  intro w hw
  exact (Finset.mem_filter.mp hw).1

/-- The visited set only grows: it is contained in the result of `go`.
@isnad1 id=le.0h5v.s5.f1db271ed4db from=translated src=- shape=9bc415ff vocab=0ab6e04b
-/
theorem subset_bidirectedBFS_go (frontier visited : Finset (SWIGNode N))
    (fuel : ℕ) : visited ⊆ bidirectedBFS.go G frontier visited fuel := by
  induction fuel generalizing frontier visited with
  | zero => rw [bidirectedBFS.go]
  | succ n ih =>
    rw [bidirectedBFS.go]
    by_cases h : frontier.biUnion (G.bidirectedNeighbors) \ visited = ∅
    · simp [h]
    · simp only [h, ite_false]
      exact (Finset.subset_union_left).trans (ih _ _)

/-- If the visited set and frontier are within `observed`, so is the result of
    `go`.
@isnad1 id=le.1h5v.s6.09f8efe5c1b7 from=translated src=- shape=97f0487d vocab=506149e3
-/
theorem bidirectedBFS_go_subset_observed (frontier visited : Finset (SWIGNode N))
    (fuel : ℕ) (hvis : visited ⊆ G.observed) :
    bidirectedBFS.go G frontier visited fuel ⊆ G.observed := by
  induction fuel generalizing frontier visited with
  | zero => rw [bidirectedBFS.go]; exact hvis
  | succ n ih =>
    rw [bidirectedBFS.go]
    by_cases h : frontier.biUnion (G.bidirectedNeighbors) \ visited = ∅
    · simpa [h] using hvis
    · simp only [h, ite_false]
      apply ih
      apply Finset.union_subset hvis
      intro w hw
      obtain ⟨hw', _⟩ := Finset.mem_sdiff.mp hw
      obtain ⟨x, _, hx⟩ := Finset.mem_biUnion.mp hw'
      exact G.bidirectedNeighbors_subset_observed x hx

/-- The bidirected BFS from `start` is contained in `observed`.
@isnad1 id=le.0h3v.s5.fd6108330907 from=translated src=- shape=154b6303 vocab=fedbaa8e
-/
theorem bidirectedBFS_subset_observed (start : SWIGNode N) :
    G.bidirectedBFS start ⊆ G.observed := by
  rw [bidirectedBFS]
  by_cases h : start ∈ G.observed
  · simp only [h, ite_true]
    exact G.bidirectedBFS_go_subset_observed _ _ _ (by simpa using h)
  · simp [h]

/-- The start node belongs to its own BFS result (when observed).
@isnad1 id=mem.1h3v.s5.d7cbbd780e60 from=translated src=- shape=b22ee046 vocab=0b42c1ed
-/
theorem mem_bidirectedBFS_self {start : SWIGNode N} (h : start ∈ G.observed) :
    start ∈ G.bidirectedBFS start := by
  rw [bidirectedBFS]
  simp only [h, ite_true]
  exact G.subset_bidirectedBFS_go _ _ _ (by simp)

/-! ## BFS ↔ reachability bridge -/

/-- **Soundness of BFS.** Every node produced by `bidirectedBFS.go` from a
    frontier and visited set all of whose elements are bidirected-reachable from
    `start` is itself bidirected-reachable from `start`. Fully proved by
    induction on the fuel.
@isnad1 id=bidirect.3h7v.s6.f8895cc433d1 from=translated src=- shape=9e2d104e vocab=a56e90d0
-/
theorem bidirectedBFS_go_reachable {start : SWIGNode N} :
    ∀ (fuel : ℕ) (frontier visited : Finset (SWIGNode N)),
      (∀ y ∈ visited, G.bidirectedReachable start y) →
      (∀ y ∈ frontier, G.bidirectedReachable start y) →
      ∀ z ∈ bidirectedBFS.go G frontier visited fuel,
        G.bidirectedReachable start z := by
  intro fuel
  induction fuel with
  | zero =>
    intro frontier visited hv _ z hz
    rw [bidirectedBFS.go] at hz; exact hv z hz
  | succ n ih =>
    intro frontier visited hv hf z hz
    rw [bidirectedBFS.go] at hz
    by_cases h : frontier.biUnion (G.bidirectedNeighbors) \ visited = ∅
    · simp only [h, ite_true] at hz; exact hv z hz
    · simp only [h, ite_false] at hz
      have hnew : ∀ y ∈ frontier.biUnion (G.bidirectedNeighbors) \ visited,
          G.bidirectedReachable start y := by
        intro y hy
        obtain ⟨hy', _⟩ := Finset.mem_sdiff.mp hy
        obtain ⟨q, hq, hqy⟩ := Finset.mem_biUnion.mp hy'
        exact bidirectedReachable.step (hf q hq) ((Finset.mem_filter.mp hqy).2)
      apply ih _ _ _ _ z hz
      · intro y hy
        rcases Finset.mem_union.mp hy with hy | hy
        · exact hv y hy
        · exact hnew y hy
      · exact hnew

/-- **Closure at saturation.** Under the BFS invariants — the visited set is
    observed, and every *already-expanded* visited node (one outside the frontier) has all its
    directly-confounded neighbors in `visited` — and given enough remaining fuel
    (`card observed - card visited ≤ fuel`), the result of `go` is closed under
    the directly-confounded relation: every neighbor of a node in the result is
    again in the result.

    This is the fuel-saturation core of BFS completeness: each non-terminating
    step strictly grows `visited` (bounded by `card observed`), so the loop must
    hit `newNeighbors = ∅` within budget, and at that fixed point the visited
    set is confounding-closed.
@isnad1 id=mem.5h7v.s7.afe66e4a8816 from=translated src=- shape=6f4821ee vocab=d82d9194
-/
theorem bidirectedBFS_go_closed :
    ∀ (fuel : ℕ) (frontier visited : Finset (SWIGNode N)),
      visited ⊆ G.observed →
      (∀ a ∈ visited, a ∉ frontier → ∀ b, G.directlyConfounded a b → b ∈ visited) →
      (G.observed.card - visited.card ≤ fuel) →
      ∀ a ∈ bidirectedBFS.go G frontier visited fuel,
        ∀ b, G.directlyConfounded a b → b ∈ bidirectedBFS.go G frontier visited fuel := by
  intro fuel
  induction fuel with
  | zero =>
    intro frontier visited hvo hexp hbudget a ha b hab
    rw [bidirectedBFS.go] at ha ⊢
    -- fuel = 0: budget forces visited to already cover observed, so frontier
    -- nodes' neighbors are visited too.
    have hcard : G.observed.card ≤ visited.card := by omega
    have hveq : visited = G.observed :=
      Finset.eq_of_subset_of_card_le hvo hcard
    by_cases haf : a ∈ frontier
    · -- a ∈ frontier ⊆ visited = observed; b ∈ observed ⊆ visited.
      obtain ⟨_, u, hu, _, hub⟩ := hab
      have hbo : b ∈ G.observed :=
        G.all_children_in_observed u
          (Finset.mem_union_left _ (Finset.mem_union_left _ hu))
          (G.dag.mem_children.mpr hub)
      rwa [hveq]
    · exact hexp a ha haf b hab
  | succ n ih =>
    intro frontier visited hvo hexp hbudget a ha b hab
    rw [bidirectedBFS.go] at ha ⊢
    set newNeighbors := frontier.biUnion (G.bidirectedNeighbors) \ visited with hnn
    by_cases h : newNeighbors = ∅
    · -- Terminating branch: result = visited, which is confounding-closed.
      simp only [h, ite_true] at ha ⊢
      by_cases haf : a ∈ frontier
      · -- a in frontier: its neighbor b is in biUnion; since newNeighbors = ∅,
        -- b must already be in visited.
        have hbn : b ∈ G.bidirectedNeighbors a := by
          rw [bidirectedNeighbors, Finset.mem_filter]
          obtain ⟨hne, u, hu, hua, hub⟩ := hab
          have hbo : b ∈ G.observed :=
            G.all_children_in_observed u
              (Finset.mem_union_left _ (Finset.mem_union_left _ hu))
              (G.dag.mem_children.mpr hub)
          exact ⟨hbo, ⟨hne, u, hu, hua, hub⟩⟩
        have hbU : b ∈ frontier.biUnion (G.bidirectedNeighbors) :=
          Finset.mem_biUnion.mpr ⟨a, haf, hbn⟩
        by_contra hbv
        have : b ∈ newNeighbors := Finset.mem_sdiff.mpr ⟨hbU, hbv⟩
        rw [h] at this
        exact absurd this (by simp)
      · exact hexp a ha haf b hab
    · -- Recursing branch: apply IH to the grown visited set.
      simp only [h, ite_false] at ha ⊢
      have hUobs : ∀ x ∈ frontier.biUnion (G.bidirectedNeighbors), x ∈ G.observed := by
        intro x hx
        obtain ⟨q, _, hq⟩ := Finset.mem_biUnion.mp hx
        exact G.bidirectedNeighbors_subset_observed q hq
      -- New invariant pieces.
      have hfv' : newNeighbors ⊆ visited ∪ newNeighbors := Finset.subset_union_right
      have hvo' : visited ∪ newNeighbors ⊆ G.observed := by
        apply Finset.union_subset hvo
        intro x hx
        exact hUobs x (Finset.mem_sdiff.mp hx).1
      have hexp' : ∀ x ∈ visited ∪ newNeighbors, x ∉ newNeighbors →
          ∀ c, G.directlyConfounded x c → c ∈ visited ∪ newNeighbors := by
        intro x hx hxnn c hxc
        have hxv : x ∈ visited := by
          rcases Finset.mem_union.mp hx with hxv | hxnew
          · exact hxv
          · exact absurd hxnew hxnn
        by_cases hxf : x ∈ frontier
        · -- x ∈ frontier: c is a neighbor, so c ∈ biUnion, hence c ∈ visited or
          -- c ∈ newNeighbors.
          have hcn : c ∈ G.bidirectedNeighbors x := by
            rw [bidirectedNeighbors, Finset.mem_filter]
            obtain ⟨hne, u, hu, hux, huc⟩ := hxc
            have hco : c ∈ G.observed :=
              G.all_children_in_observed u
                (Finset.mem_union_left _ (Finset.mem_union_left _ hu))
                (G.dag.mem_children.mpr huc)
            exact ⟨hco, ⟨hne, u, hu, hux, huc⟩⟩
          have hcU : c ∈ frontier.biUnion (G.bidirectedNeighbors) :=
            Finset.mem_biUnion.mpr ⟨x, hxf, hcn⟩
          by_cases hcv : c ∈ visited
          · exact Finset.mem_union_left _ hcv
          · exact Finset.mem_union_right _ (Finset.mem_sdiff.mpr ⟨hcU, hcv⟩)
        · exact Finset.mem_union_left _ (hexp x hxv hxf c hxc)
      -- Budget decreases by at least one because newNeighbors is nonempty and
      -- disjoint from visited.
      have hdisj : Disjoint visited newNeighbors :=
        disjoint_sdiff_self_right
      have hcardU : (visited ∪ newNeighbors).card = visited.card + newNeighbors.card :=
        Finset.card_union_of_disjoint hdisj
      have hnnpos : 0 < newNeighbors.card :=
        Finset.card_pos.mpr (Finset.nonempty_of_ne_empty h)
      have hbudget' : G.observed.card - (visited ∪ newNeighbors).card ≤ n := by
        rw [hcardU]; omega
      exact ih newNeighbors (visited ∪ newNeighbors) hvo' hexp' hbudget' a ha b hab

/-- **BFS computes bidirected reachability.** Fix a single-world intervention graph `G` and
[a node `start` that is observed in `G`](hyp:hstart). Then [a node `w` is found by the
breadth-first search from `start` exactly when `w` is bidirected-reachable from `start` —
connected to it by a chain of directly-confounded (shared-unobserved-parent) pairs](goal).

    The proof combines soundness of every BFS expansion step with the closure
    invariant of the saturated visited set. The reverse direction inducts on the
    bidirected-reachability derivation after showing that the bounded BFS loop
    has reached a set closed under directly-confounded neighbors.
@isnad1 id=iff.1h4v.s6.77840729422d from=translated src=- shape=a8d7bb0d vocab=1ce0b8e3
-/
theorem mem_bidirectedBFS_iff_reachable {start w : SWIGNode N}
    (hstart : start ∈ G.observed) :
    w ∈ G.bidirectedBFS start ↔ G.bidirectedReachable start w := by
  constructor
  · -- Soundness: fully proved.
    intro hw
    rw [bidirectedBFS] at hw
    simp only [hstart, ite_true] at hw
    refine G.bidirectedBFS_go_reachable _ _ _ ?_ ?_ w hw
    · intro y hy
      rw [Finset.mem_singleton.mp hy]
      exact bidirectedReachable.refl hstart
    · intro y hy
      rw [Finset.mem_singleton.mp hy]
      exact bidirectedReachable.refl hstart
  · -- Completeness: the BFS result is confounding-closed (saturation), and it
    -- contains `start`; induct on the reachability derivation.
    intro hreach
    rw [bidirectedBFS]
    simp only [hstart, ite_true]
    -- The initial state satisfies the closure invariant with sufficient fuel.
    have hclosed := G.bidirectedBFS_go_closed (Fintype.card (SWIGNode N))
      {start} {start} (by simpa using hstart)
      (by intro a ha haf; exact absurd ha haf)
      (by
        have h1 : G.observed.card ≤ Fintype.card (SWIGNode N) :=
          (Finset.card_le_univ G.observed).trans_eq (Fintype.card_eq.mpr ⟨Equiv.refl _⟩).symm
        simp only [Finset.card_singleton]
        omega)
    have hself : start ∈ bidirectedBFS.go G {start} {start} (Fintype.card (SWIGNode N)) :=
      G.subset_bidirectedBFS_go _ _ _ (Finset.mem_singleton_self start)
    induction hreach with
    | refl _ => exact hself
    | step _ hconf ih => exact hclosed _ ih _ hconf

/-! ## The c-component partition -/

/-- The c-component of `v` is contained in the observed nodes.
@isnad1 id=le.0h3v.s5.b228641c6462 from=translated src=- shape=154b6303 vocab=e1dc428a
-/
theorem cComponentOf_subset_observed (v : SWIGNode N) :
    G.cComponentOf v ⊆ G.observed :=
  G.bidirectedBFS_subset_observed v

/-- An observed node belongs to its own c-component.
@isnad1 id=mem.1h3v.s5.2ab432a55789 from=translated src=- shape=b22ee046 vocab=3fed056c
-/
theorem mem_cComponentOf_self {v : SWIGNode N} (hv : v ∈ G.observed) :
    v ∈ G.cComponentOf v :=
  G.mem_bidirectedBFS_self hv

/-- Every c-component (in the canonical set) is contained in the observed
    nodes.
@isnad1 id=le.1h3v.s6.9f41ef17c8bb from=translated src=- shape=45639298 vocab=768ce856
-/
theorem cComponentSet_subset_observed :
    ∀ C ∈ G.cComponentSet, C ⊆ G.observed := by
  intro C hC
  rw [cComponentSet, Finset.mem_image] at hC
  obtain ⟨v, _, rfl⟩ := hC
  exact G.cComponentOf_subset_observed v

/-- [The c-components cover exactly the observed nodes: their union recovers the set of
observed nodes exactly](goal).
@isnad1 id=eq.0h2v.s5.5d71189bae7b from=translated src=- shape=b1b4d321 vocab=c999e251
-/
theorem cComponentSet_biUnion :
    G.cComponentSet.biUnion id = G.observed := by
  apply Finset.Subset.antisymm
  · intro w hw
    rw [Finset.mem_biUnion] at hw
    obtain ⟨C, hC, hwC⟩ := hw
    exact G.cComponentSet_subset_observed C hC (id_eq C ▸ hwC)
  · intro v hv
    rw [Finset.mem_biUnion]
    refine ⟨G.cComponentOf v, ?_, ?_⟩
    · rw [cComponentSet, Finset.mem_image]
      exact ⟨v, hv, rfl⟩
    · exact id_eq _ ▸ G.mem_cComponentOf_self hv

/-- Membership in a c-component is exactly bidirected reachability from its seed. For
[a node `v` that is observed in `G`](hyp:hv), [a node `w` belongs to the c-component seeded
at `v` exactly when `w` is bidirected-reachable from `v`](goal).
@isnad1 id=iff.1h4v.s6.bdad49f15477 from=translated src=- shape=a8d7bb0d vocab=116cb378
-/
theorem mem_cComponentOf_iff_reachable {v w : SWIGNode N} (hv : v ∈ G.observed) :
    w ∈ G.cComponentOf v ↔ G.bidirectedReachable v w :=
  G.mem_bidirectedBFS_iff_reachable hv

/-- Two c-components seeded by reachable observed nodes are equal.
@isnad1 id=eq.1h4v.s5.26848f163051 from=translated src=- shape=a50536c6 vocab=078c06d9
-/
theorem cComponentOf_eq_of_reachable {v w : SWIGNode N}
    (h : G.bidirectedReachable v w) :
    G.cComponentOf v = G.cComponentOf w := by
  have hv := G.bidirectedReachable_observed_left h
  have hw := G.bidirectedReachable_observed_right h
  apply Finset.Subset.antisymm
  · intro x hx
    rw [G.mem_cComponentOf_iff_reachable hw]
    rw [G.mem_cComponentOf_iff_reachable hv] at hx
    exact G.bidirectedReachable_trans (G.bidirectedReachable_symm h) hx
  · intro x hx
    rw [G.mem_cComponentOf_iff_reachable hv]
    rw [G.mem_cComponentOf_iff_reachable hw] at hx
    exact G.bidirectedReachable_trans h hx

/-- A node in a listed c-component has that component as its computed
c-component.
@isnad1 id=eq.2h4v.s6.3528b1253be5 from=translated src=- shape=414d07dd vocab=24de6497
-/
theorem cComponentOf_eq_of_mem_cComponentSet
    {C : Finset (SWIGNode N)} (hC : C ∈ G.cComponentSet)
    {v : SWIGNode N} (hvC : v ∈ C) :
    G.cComponentOf v = C := by
  classical
  rw [cComponentSet, Finset.mem_image] at hC
  obtain ⟨s, hsObs, rfl⟩ := hC
  exact (G.cComponentOf_eq_of_reachable
    ((G.mem_cComponentOf_iff_reachable hsObs).mp hvC)).symm

/-- A node outside a c-component is not directly confounded with a node inside it.

This is the boundary property of c-components: adding a shared-latent-parent
edge from an inside observed node to an outside observed node would make the
outside node bidirected-reachable from the component seed, hence a member of
the same c-component.
@isnad1 id=not.3h5v.s6.c4280b0dd589 from=translated src=- shape=3b9312b2 vocab=86da1b4c
-/
theorem not_directlyConfounded_of_mem_cComponentSet_of_not_mem
    {C : Finset (SWIGNode N)} (hC : C ∈ G.cComponentSet)
    {v w : SWIGNode N} (hvC : v ∈ C) (hwNotC : w ∉ C) :
    ¬ G.directlyConfounded v w := by
  intro hconf
  rw [cComponentSet, Finset.mem_image] at hC
  obtain ⟨s, hsObs, rfl⟩ := hC
  have hsv : G.bidirectedReachable s v :=
    (G.mem_cComponentOf_iff_reachable hsObs).mp hvC
  have hsw : G.bidirectedReachable s w :=
    bidirectedReachable.step hsv hconf
  exact hwNotC ((G.mem_cComponentOf_iff_reachable hsObs).mpr hsw)

/-- No latent root can be a shared parent of a c-component node and a node
outside that c-component.

This is the concrete shared-parent form of
`not_directlyConfounded_of_mem_cComponentSet_of_not_mem`.
@isnad1 id=false.6h6v.s7.5dfa9079f20f from=translated src=- shape=69487995 vocab=d77d77f1
-/
theorem no_shared_unobserved_parent_of_mem_cComponentSet_of_not_mem
    {C : Finset (SWIGNode N)} (hC : C ∈ G.cComponentSet)
    {v w u : SWIGNode N} (hvC : v ∈ C) (hwNotC : w ∉ C) (hu : u ∈ G.unobserved)
    (huv : G.dag.edge u v) (huw : G.dag.edge u w) : False := by
  have hvw : v ≠ w := by
    intro h
    exact hwNotC (h ▸ hvC)
  exact (G.not_directlyConfounded_of_mem_cComponentSet_of_not_mem
      hC hvC hwNotC)
    ⟨hvw, u, hu, huv, huw⟩

/-- If a latent node has edges into two observed nodes retained by an induced
graph, those observed nodes seed the same induced c-component.
@isnad1 id=eq.5h6v.s7.98f8b42d5a85 from=translated src=- shape=859881cf vocab=34573b35
-/
theorem induce_cComponentOf_eq_of_shared_unobserved_parent
    (R : Finset (SWIGNode N)) {u v w : SWIGNode N}
    (hu : u ∈ G.unobserved)
    (hvR : v ∈ R) (hwR : w ∈ R)
    (huv : G.dag.edge u v) (huw : G.dag.edge u w) :
    (G.induce R).cComponentOf v = (G.induce R).cComponentOf w := by
  classical
  have hvObs : v ∈ G.observed :=
    G.all_children_in_observed u
      (Finset.mem_union_left _ (Finset.mem_union_left _ hu))
      (G.dag.mem_children.mpr huv)
  have hwObs : w ∈ G.observed :=
    G.all_children_in_observed u
      (Finset.mem_union_left _ (Finset.mem_union_left _ hu))
      (G.dag.mem_children.mpr huw)
  by_cases hvw : v = w
  · subst hvw
    rfl
  have hvInd : v ∈ (G.induce R).observed := by
    simp [SWIGGraph.induce, hvR, hvObs]
  have hwInd : w ∈ (G.induce R).observed := by
    simp [SWIGGraph.induce, hwR, hwObs]
  have huInd : u ∈ (G.induce R).unobserved := by
    change u ∈ G.unobserved.filter (fun u => ∃ z ∈ R ∩ G.observed, G.dag.edge u z)
    exact Finset.mem_filter.mpr ⟨hu, v, Finset.mem_inter.mpr ⟨hvR, hvObs⟩, huv⟩
  have huvInd : (G.induce R).dag.edge u v := by
    rw [SWIGGraph.induce]
    rw [SWIGGraph.inducedDag_edge_iff]
    exact ⟨huv, Finset.mem_union_right _ huInd, by simp [hvR, hvObs]⟩
  have huwInd : (G.induce R).dag.edge u w := by
    rw [SWIGGraph.induce]
    rw [SWIGGraph.inducedDag_edge_iff]
    exact ⟨huw, Finset.mem_union_right _ huInd, by simp [hwR, hwObs]⟩
  have hconf : (G.induce R).directlyConfounded v w :=
    ⟨hvw, u, huInd, huvInd, huwInd⟩
  exact (G.induce R).cComponentOf_eq_of_reachable
    (SWIGGraph.bidirectedReachable.step
      (SWIGGraph.bidirectedReachable.refl hvInd) hconf)

/-- [Distinct c-components are pairwise disjoint: no observed node belongs to two different
c-components](goal).
@isnad1 id=pairwise.0h2v.s5.fcf13baf4ae0 from=translated src=- shape=4c24e841 vocab=0c976fa1
-/
theorem cComponentSet_pairwise_disjoint :
    (G.cComponentSet : Set (Finset (SWIGNode N))).PairwiseDisjoint id := by
  intro C hC D hD hCD
  rw [Finset.mem_coe, cComponentSet, Finset.mem_image] at hC hD
  obtain ⟨v, hv, rfl⟩ := hC
  obtain ⟨w, hw, rfl⟩ := hD
  -- If the components intersect at some `x`, the seeds are mutually reachable,
  -- hence the components are equal — contradicting `hCD`.
  rw [Function.onFun, id_eq, id_eq, Finset.disjoint_left]
  intro x hxv hxw
  apply hCD
  rw [G.mem_cComponentOf_iff_reachable hv] at hxv
  rw [G.mem_cComponentOf_iff_reachable hw] at hxw
  -- `v` reaches `x` and `w` reaches `x`, so `v` reaches `w`.
  exact G.cComponentOf_eq_of_reachable
    (G.bidirectedReachable_trans hxv (G.bidirectedReachable_symm hxw))

end SWIGGraph

end Causalean.Graph
