/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan

# Conditional-expectation lemmas under `CondIndepFun`

* `condExp_sup_comap_eq_of_condIndep` — drop-of-conditioning: if `g ⟂ f | m`,
  conditioning `h ∘ g` on `m ⊔ σ(f)` equals conditioning on `m` alone.
* `condExp_mul_of_condIndep` — product factorization: `μ[(u∘f)(v∘g)|m] =ᵐ μ[u∘f|m]·μ[v∘g|m]`.
* `condIndepFun_weak_union_of_prodMk` — weak union via `prodMk`: `W ⟂ (V,A)|m ⟹ W ⟂ V|(m⊔σA)`.
* `condIndepFun_prodMk_of_measurable_left` — extension by an `m`-measurable function.
* `condIndepFun_contraction_of_prodMk` — contraction via a product right side.
-/

module

public import Tengoku.Causalean.Causalean.Mathlib.MeasureTheory.FinsetValues
public import Tengoku.Causalean.Causalean.Mathlib.Probability.Independence.Conditional.CondExp_Part1
public import Tengoku

/-! # Conditional Expectations Under Conditional Independence

This file proves conditional-expectation identities implied by conditional
independence, including drop-of-conditioning, product factorization, weak union, and
contraction. These measure-theoretic facts give a reusable algebra for conditional
independence under enlarged conditioning σ-algebras and paired coordinates.

The central exported lemmas are `condExp_sup_comap_eq_of_condIndep_comap` and
`condExp_sup_comap_eq_of_condIndep` for removing irrelevant conditioning
variables, `condExp_mul_of_condIndep` for factoring a product's conditional
expectation, `condIndepFun_weak_union_of_prodMk` for weak union,
`condIndepFun_prodMk_of_measurable_left` for adjoining an `m`-measurable
coordinate, and `condIndepFun_contraction_of_prodMk` for semigraphoid
contraction. -/

public section

open Causalean.Mathlib.MeasureTheory

namespace Causalean.Mathlib.Probability.Independence.Conditional
open _root_.MeasureTheory

open scoped MeasureTheory ProbabilityTheory
/-- **Weak union for conditional independence.** For [a sub-σ-algebra `m` coarser than the ambient
σ-algebra](hyp:hm) and [measurable maps `W`, `V`, and `A`](hyp:hW,hV,hA), if [`W` is conditionally
independent of the pair `(V, A)` given `m`](hyp:hCI), then [`W` is conditionally independent of `V`
given the enlarged σ-algebra `m` joined with the σ-algebra generated by `A`](goal).

The proof reduces to the conditional-expectation indicator characterization:
condition first on `m ⊔ σ(V,A)`, pull out the V-indicator, drop the extra
conditioning from the W-indicator using `condExp_sup_comap_eq_of_condIndep`,
and tower back to `m ⊔ σ(A)`. -/
theorem condIndepFun_weak_union_of_prodMk
    {Ω α β γ : Type*} [MeasurableSpace α] [MeasurableSpace β] [MeasurableSpace γ]
    {m mΩ : MeasurableSpace Ω} (hm : m ≤ mΩ)
    [StandardBorelSpace Ω]
    {μ : MeasureTheory.Measure Ω} [MeasureTheory.IsFiniteMeasure μ]
    {W : Ω → α} {V : Ω → β} {A : Ω → γ}
    (hW : Measurable W) (hV : Measurable V) (hA : Measurable A)
    (hCI : ProbabilityTheory.CondIndepFun m hm W (fun ω => (V ω, A ω)) μ) :
    ProbabilityTheory.CondIndepFun (m ⊔ MeasurableSpace.comap A inferInstance)
      (sup_le hm hA.comap_le) W V μ := by
  let mA : MeasurableSpace Ω := m ⊔ MeasurableSpace.comap A inferInstance
  let pair : Ω → β × γ := fun ω => (V ω, A ω)
  let mVA : MeasurableSpace Ω := m ⊔ MeasurableSpace.comap pair inferInstance
  have hpair : @Measurable Ω (β × γ) mΩ _ pair := hV.prod hA
  have hmVA : mVA ≤ mΩ := by
    dsimp [mVA]
    exact sup_le hm hpair.comap_le
  have hpair_mVA : @Measurable Ω (β × γ) mVA _ pair := by
    exact Measurable.of_comap_le le_sup_right
  have hV_mVA : @Measurable Ω β mVA _ V := by
    exact measurable_fst.comp hpair_mVA
  have hA_pair :
      @Measurable Ω γ (MeasurableSpace.comap pair inferInstance) _ A := by
    exact measurable_snd.comp (Measurable.of_comap_le le_rfl)
  have hmA_le_mVA : mA ≤ mVA := by
    dsimp [mA, mVA]
    exact sup_le le_sup_left (le_trans hA_pair.comap_le le_sup_right)
  have hCI_A : ProbabilityTheory.CondIndepFun m hm W A μ := by
    simpa [Function.comp_def] using
      (hCI.comp measurable_id measurable_snd)
  rw [ProbabilityTheory.condIndepFun_iff_condExp_inter_preimage_eq_mul hW hV]
  intro s t hs ht
  let S : Set Ω := W ⁻¹' s
  let T : Set Ω := V ⁻¹' t
  let oneS : Ω → ℝ := S.indicator (fun _ => (1 : ℝ))
  let oneT : Ω → ℝ := T.indicator (fun _ => (1 : ℝ))
  have hS_meas : @MeasurableSet Ω mΩ S := hW hs
  have hT_meas : @MeasurableSet Ω mΩ T := hV ht
  have hS_int : MeasureTheory.Integrable oneS μ := by
    refine (MeasureTheory.integrable_indicator_iff hS_meas).2 ?_
    exact MeasureTheory.integrableOn_const
  have hT_int : MeasureTheory.Integrable oneT μ := by
    refine (MeasureTheory.integrable_indicator_iff hT_meas).2 ?_
    exact MeasureTheory.integrableOn_const
  have hST_int : MeasureTheory.Integrable (oneS * oneT) μ := by
    have hST_set_int :
        MeasureTheory.Integrable ((S ∩ T).indicator (fun _ : Ω => (1 : ℝ))) μ := by
      refine (MeasureTheory.integrable_indicator_iff (hS_meas.inter hT_meas)).2 ?_
      exact MeasureTheory.integrableOn_const
    exact hST_set_int.congr (MeasureTheory.ae_of_all μ fun ω => by
      by_cases hωS : ω ∈ S <;> by_cases hωT : ω ∈ T <;> simp [oneS, oneT, hωS, hωT])
  have hT_mVA :
      @MeasureTheory.StronglyMeasurable Ω ℝ _ mVA oneT := by
    exact MeasureTheory.stronglyMeasurable_const.indicator (hV_mVA ht)
  have hdrop_mVA :
      μ[oneS | mVA] =ᵐ[μ] μ[oneS | m] := by
    have hs_ind_meas :
        Measurable (s.indicator (fun _ : α => (1 : ℝ))) := by fun_prop
    have hone : oneS = fun ω => s.indicator (fun _ : α => (1 : ℝ)) (W ω) := by
      funext ω
      by_cases hω : W ω ∈ s <;> simp [oneS, S, hω]
    rw [hone]
    simpa [mVA, pair] using
      (condExp_sup_comap_eq_of_condIndep hm hpair hW hCI
        (h := s.indicator (fun _ : α => (1 : ℝ))) hs_ind_meas hS_int)
  have hdrop_mA :
      μ[oneS | mA] =ᵐ[μ] μ[oneS | m] := by
    have hs_ind_meas :
        Measurable (s.indicator (fun _ : α => (1 : ℝ))) := by fun_prop
    have hone : oneS = fun ω => s.indicator (fun _ : α => (1 : ℝ)) (W ω) := by
      funext ω
      by_cases hω : W ω ∈ s <;> simp [oneS, S, hω]
    rw [hone]
    simpa [mA] using
      (condExp_sup_comap_eq_of_condIndep hm hA hW hCI_A
        (h := s.indicator (fun _ : α => (1 : ℝ))) hs_ind_meas hS_int)
  have htower :
      μ[oneS * oneT | mA] =ᵐ[μ] μ[μ[oneS * oneT | mVA] | mA] := by
    exact (MeasureTheory.condExp_condExp_of_le
      (f := oneS * oneT) (m₁ := mA) (m₂ := mVA) (m₀ := mΩ)
      hmA_le_mVA hmVA).symm
  have hinner :
      μ[oneS * oneT | mVA] =ᵐ[μ] μ[oneS | mVA] * oneT := by
    exact MeasureTheory.condExp_mul_of_stronglyMeasurable_right (m := mVA)
      (f := oneS) (g := oneT) hT_mVA hST_int hS_int
  have hinner_drop :
      μ[oneS * oneT | mVA] =ᵐ[μ] μ[oneS | m] * oneT :=
    hinner.trans (hdrop_mVA.mul (Filter.EventuallyEq.rfl))
  have hinner_outer :
      μ[μ[oneS * oneT | mVA] | mA]
        =ᵐ[μ] μ[μ[oneS | m] * oneT | mA] :=
    MeasureTheory.condExp_congr_ae hinner_drop
  have hprod_int :
      MeasureTheory.Integrable (μ[oneS | m] * oneT) μ := by
    exact (MeasureTheory.integrable_condExp (m := mVA)
      (f := oneS * oneT) (μ := μ)).congr hinner_drop
  have hceS_mA :
      @MeasureTheory.StronglyMeasurable Ω ℝ _ mA (μ[oneS | m]) := by
    exact MeasureTheory.stronglyMeasurable_condExp.mono le_sup_left
  have hpull :
      μ[μ[oneS | m] * oneT | mA]
        =ᵐ[μ] μ[oneS | m] * μ[oneT | mA] := by
    exact MeasureTheory.condExp_mul_of_stronglyMeasurable_left (m := mA)
      (f := μ[oneS | m]) (g := oneT) hceS_mA hprod_int hT_int
  have hsets :
      μ⟦W ⁻¹' s ∩ V ⁻¹' t | mA⟧
        =ᵐ[μ] μ[oneS * oneT | mA] := by
    rw [show W ⁻¹' s ∩ V ⁻¹' t = S ∩ T by rfl]
    rw [show (fun _ : Ω => (1 : ℝ)) = 1 from rfl, Set.inter_indicator_one]
    rfl
  calc
    μ⟦W ⁻¹' s ∩ V ⁻¹' t | mA⟧
        =ᵐ[μ] μ[oneS * oneT | mA] := hsets
    _ =ᵐ[μ] μ[μ[oneS * oneT | mVA] | mA] := htower
    _ =ᵐ[μ] μ[μ[oneS | m] * oneT | mA] := hinner_outer
    _ =ᵐ[μ] μ[oneS | m] * μ[oneT | mA] := hpull
    _ =ᵐ[μ] μ[oneS | mA] * μ[oneT | mA] := by
      exact hdrop_mA.symm.mul (Filter.EventuallyEq.rfl)
    _ =ᵐ[μ] μ⟦W ⁻¹' s | mA⟧ * μ⟦V ⁻¹' t | mA⟧ := by
      rfl

/-- **Extension of `CondIndepFun` by an `m`-measurable function**.

If `W ⟂ Z | m` and `X` is `m`-measurable, then `(W, X) ⟂ Z | m`.

Proof uses `condIndepFun_iff_condExp_inter_preimage_eq_mul` to reduce to the
indicator product identity for measurable rectangles, pulls out the
`m`-measurable indicator `1_{X⁻¹(B_X)}` on both sides, applies `_hCI` on the
W-Z part, and extends from the π-system of rectangles via `CondIndepSets.condIndep'`. -/
theorem condIndepFun_prodMk_of_measurable_left
    {Ω α β γ : Type*} [MeasurableSpace α] [MeasurableSpace β] [MeasurableSpace γ]
    {m mΩ : MeasurableSpace Ω} (hm : m ≤ mΩ)
    [StandardBorelSpace Ω]
    {μ : MeasureTheory.Measure Ω} [MeasureTheory.IsFiniteMeasure μ]
    {W : Ω → α} {X : Ω → β} {Z : Ω → γ}
    (_hW : Measurable W) (_hZ : Measurable Z) (_hX_m : Measurable[m] X)
    (_hCI : ProbabilityTheory.CondIndepFun m hm W Z μ) :
    ProbabilityTheory.CondIndepFun m hm (fun ω => (W ω, X ω)) Z μ := by
  let pair : Ω → α × β := fun ω => (W ω, X ω)
  let rects : Set (Set (α × β)) :=
    Set.image2 (· ×ˢ ·) {s : Set α | MeasurableSet s} {t : Set β | MeasurableSet t}
  let zsets : Set (Set γ) := {t : Set γ | MeasurableSet t}
  let pPair : Set (Set Ω) :=
    {q | ∃ s : Set α, MeasurableSet s ∧
      ∃ u : Set β, MeasurableSet u ∧ pair ⁻¹' (s ×ˢ u) = q}
  let pZ : Set (Set Ω) := {q | ∃ r : Set γ, r ∈ zsets ∧ Z ⁻¹' r = q}
  have hpair_meas : Measurable pair := _hW.prod (_hX_m.mono hm le_rfl)
  have hpPair_pi : IsPiSystem pPair := by
    simpa [pPair] using (isPiSystem_prod (α := α) (β := β)).comap pair
  have hpZ_pi : IsPiSystem pZ := by
    simpa [pZ, zsets] using (MeasurableSpace.isPiSystem_measurableSet (α := γ)).comap Z
  have hpPair_meas : ∀ s ∈ pPair, MeasurableSet s := by
    rintro _ ⟨s, hs, u, hu, rfl⟩
    exact hpair_meas (hs.prod hu)
  have hpZ_meas : ∀ s ∈ pZ, MeasurableSet s := by
    rintro _ ⟨r, hr, rfl⟩
    exact _hZ (by simpa [zsets] using hr)
  have hrect : ProbabilityTheory.CondIndepSets m hm pPair pZ μ := by
    rw [ProbabilityTheory.condIndepSets_iff m hm pPair pZ hpPair_meas hpZ_meas μ]
    intro t1 t2 ht1 ht2
    rcases ht1 with ⟨s, hs_meas, u, hu_meas, rfl⟩
    rcases ht2 with ⟨v, hv, rfl⟩
    have hv_meas : MeasurableSet v := by simpa [zsets] using hv
    let A : Set Ω := W ⁻¹' s
    let B : Set Ω := X ⁻¹' u
    let C : Set Ω := Z ⁻¹' v
    have hB_m : MeasurableSet[m] B := _hX_m hu_meas
    have hB_sm : StronglyMeasurable[m] (B.indicator (fun _ : Ω => (1 : ℝ))) :=
      MeasureTheory.stronglyMeasurable_const.indicator hB_m
    have hB_bound : ∀ᵐ ω ∂μ, ‖B.indicator (fun _ : Ω => (1 : ℝ)) ω‖ ≤
        (1 : ℝ) := by
      exact MeasureTheory.ae_of_all μ fun ω => by
        rw [Set.indicator]
        split_ifs <;> simp
    have hAC_int :
        MeasureTheory.Integrable ((A ∩ C).indicator (fun _ : Ω => (1 : ℝ))) μ := by
      refine (MeasureTheory.integrable_indicator_iff ?_).2 MeasureTheory.integrableOn_const
      exact (_hW hs_meas).inter (_hZ hv_meas)
    have hA_int :
        MeasureTheory.Integrable (A.indicator (fun _ : Ω => (1 : ℝ))) μ := by
      refine (MeasureTheory.integrable_indicator_iff ?_).2 MeasureTheory.integrableOn_const
      exact _hW hs_meas
    have hpull_AC :
        μ[B.indicator (fun _ : Ω => (1 : ℝ)) *
            (A ∩ C).indicator (fun _ : Ω => (1 : ℝ)) | m]
          =ᵐ[μ] B.indicator (fun _ : Ω => (1 : ℝ)) *
            μ[(A ∩ C).indicator (fun _ : Ω => (1 : ℝ)) | m] :=
      MeasureTheory.condExp_stronglyMeasurable_mul_of_bound hm hB_sm hAC_int 1 hB_bound
    have hpull_A :
        μ[B.indicator (fun _ : Ω => (1 : ℝ)) *
            A.indicator (fun _ : Ω => (1 : ℝ)) | m]
          =ᵐ[μ] B.indicator (fun _ : Ω => (1 : ℝ)) *
            μ[A.indicator (fun _ : Ω => (1 : ℝ)) | m] :=
      MeasureTheory.condExp_stronglyMeasurable_mul_of_bound hm hB_sm hA_int 1 hB_bound
    have hCIeq :=
      (ProbabilityTheory.condIndepFun_iff_condExp_inter_preimage_eq_mul _hW _hZ).mp
        _hCI s v hs_meas hv_meas
    have hleft :
        μ⟦((A ∩ B) ∩ C) | m⟧
          =ᵐ[μ] μ[B.indicator (fun _ : Ω => (1 : ℝ)) *
            (A ∩ C).indicator (fun _ : Ω => (1 : ℝ)) | m] := by
      rw [show ((A ∩ B) ∩ C) = B ∩ (A ∩ C) by
        ext ω
        simp [and_left_comm, and_assoc]]
      rw [show (fun _ : Ω => (1 : ℝ)) = 1 from rfl, Set.inter_indicator_one]
    have hpair :
        μ⟦(A ∩ B) | m⟧
          =ᵐ[μ] μ[B.indicator (fun _ : Ω => (1 : ℝ)) *
            A.indicator (fun _ : Ω => (1 : ℝ)) | m] := by
      rw [show (A ∩ B) = B ∩ A by
        ext ω
        simp [and_comm]]
      rw [show (fun _ : Ω => (1 : ℝ)) = 1 from rfl, Set.inter_indicator_one]
    calc
      μ⟦pair ⁻¹' (s ×ˢ u) ∩ Z ⁻¹' v | m⟧
          =ᵐ[μ] μ⟦((A ∩ B) ∩ C) | m⟧ := by
            rfl
      _ =ᵐ[μ] μ[B.indicator (fun _ : Ω => (1 : ℝ)) *
            (A ∩ C).indicator (fun _ : Ω => (1 : ℝ)) | m] := hleft
      _ =ᵐ[μ] B.indicator (fun _ : Ω => (1 : ℝ)) *
            μ[(A ∩ C).indicator (fun _ : Ω => (1 : ℝ)) | m] := hpull_AC
      _ =ᵐ[μ] B.indicator (fun _ : Ω => (1 : ℝ)) * (μ⟦A | m⟧ * μ⟦C | m⟧) := by
        exact hCIeq.mono fun ω hω => by simp [A, C, hω]
      _ =ᵐ[μ] (B.indicator (fun _ : Ω => (1 : ℝ)) * μ⟦A | m⟧) * μ⟦C | m⟧ := by
        exact MeasureTheory.ae_of_all μ fun ω => by
          simp only [Pi.mul_apply]
          ring
      _ =ᵐ[μ] μ[B.indicator (fun _ : Ω => (1 : ℝ)) *
            A.indicator (fun _ : Ω => (1 : ℝ)) | m] * μ⟦C | m⟧ := by
        exact hpull_A.symm.mul (Filter.EventuallyEq.rfl)
      _ =ᵐ[μ] μ⟦A ∩ B | m⟧ * μ⟦C | m⟧ := by
        exact hpair.symm.mul (Filter.EventuallyEq.rfl)
      _ =ᵐ[μ] μ⟦pair ⁻¹' (s ×ˢ u) | m⟧ * μ⟦Z ⁻¹' v | m⟧ := by
        rfl
  rw [ProbabilityTheory.condIndepFun_iff_condIndep]
  have hpPair_eq : pPair = (fun r : Set (α × β) => pair ⁻¹' r) '' rects := by
    ext q
    constructor
    · rintro ⟨s, hs, u, hu, hq⟩
      exact ⟨s ×ˢ u, ⟨s, hs, u, hu, rfl⟩, hq⟩
    · rintro ⟨r, ⟨s, hs, u, hu, rfl⟩, hq⟩
      exact ⟨s, hs, u, hu, hq⟩
  have hgenPair : (inferInstance : MeasurableSpace (α × β)).comap pair =
      MeasurableSpace.generateFrom pPair := by
    rw [hpPair_eq, ← generateFrom_prod, MeasurableSpace.comap_generateFrom]
  have hgenZ : (inferInstance : MeasurableSpace γ).comap Z =
      MeasurableSpace.generateFrom pZ := by
    rw [show (inferInstance : MeasurableSpace γ) = MeasurableSpace.generateFrom zsets by
      exact (MeasurableSpace.generateFrom_measurableSet (α := γ)).symm]
    rw [MeasurableSpace.comap_generateFrom]
    rfl
  rw [hgenPair, hgenZ]
  exact ProbabilityTheory.CondIndepSets.condIndep' hpPair_meas hpZ_meas hpPair_pi hpZ_pi hrect

/-- **Contraction for conditional independence via a product right side.** For [a sub-σ-algebra `m`
coarser than the ambient σ-algebra](hyp:hm) and [measurable maps `X`, `Y`, and `W`](hyp:hX,hY,hW),
if [`X` is conditionally independent of `Y` given the enlarged σ-algebra `m` joined with the
σ-algebra generated by `W`](hyp:h1) and [`X` is conditionally independent of `W` given `m`](hyp:h2),
then [`X` is conditionally independent of the pair `(Y, W)` given `m`](goal).

This is the generic semigraphoid contraction step packaged for downstream projection wrappers. -/
theorem condIndepFun_contraction_of_prodMk
    {Ω α β γ : Type*} [MeasurableSpace α] [MeasurableSpace β] [MeasurableSpace γ]
    {m mΩ : MeasurableSpace Ω} (hm : m ≤ mΩ)
    [StandardBorelSpace Ω]
    {μ : MeasureTheory.Measure Ω} [MeasureTheory.IsFiniteMeasure μ]
    {X : Ω → α} {Y : Ω → β} {W : Ω → γ}
    (hX : Measurable X) (hY : Measurable Y) (hW : Measurable W)
    (h1 : ProbabilityTheory.CondIndepFun
      (m ⊔ MeasurableSpace.comap W inferInstance)
      (sup_le hm hW.comap_le) X Y μ)
    (h2 : ProbabilityTheory.CondIndepFun m hm X W μ) :
    ProbabilityTheory.CondIndepFun m hm X (fun ω => (Y ω, W ω)) μ := by
  let pair : Ω → β × γ := fun ω => (Y ω, W ω)
  let xsets : Set (Set Ω) := {q | ∃ s : Set α, MeasurableSet s ∧ X ⁻¹' s = q}
  let pairsets : Set (Set Ω) :=
    {q | ∃ t : Set β, MeasurableSet t ∧
      ∃ u : Set γ, MeasurableSet u ∧ pair ⁻¹' (t ×ˢ u) = q}
  have hpair_meas : Measurable pair := by fun_prop
  have hpX_pi : IsPiSystem xsets := by
    simpa [xsets] using (MeasurableSpace.isPiSystem_measurableSet (α := α)).comap X
  have hpPair_pi : IsPiSystem pairsets := by
    simpa [pairsets] using (isPiSystem_prod (α := β) (β := γ)).comap pair
  have hpX_meas : ∀ s ∈ xsets, MeasurableSet s := by
    rintro _ ⟨s, hs, rfl⟩
    exact hX hs
  have hpPair_meas : ∀ s ∈ pairsets, MeasurableSet s := by
    rintro _ ⟨t, ht, u, hu, rfl⟩
    exact hpair_meas (ht.prod hu)
  have hrect : ProbabilityTheory.CondIndepSets m hm xsets pairsets μ := by
    rw [ProbabilityTheory.condIndepSets_iff m hm xsets pairsets hpX_meas hpPair_meas μ]
    intro t1 t2 ht1 ht2
    rcases ht1 with ⟨s, hs_meas, rfl⟩
    rcases ht2 with ⟨t, ht_meas, u, hu_meas, rfl⟩
    let A : Set Ω := X ⁻¹' s
    let B : Set Ω := Y ⁻¹' t
    let C : Set Ω := W ⁻¹' u
    let oneA : Ω → ℝ := A.indicator (fun _ => (1 : ℝ))
    let oneB : Ω → ℝ := B.indicator (fun _ => (1 : ℝ))
    let oneC : Ω → ℝ := C.indicator (fun _ => (1 : ℝ))
    let mW : MeasurableSpace Ω := m ⊔ MeasurableSpace.comap W inferInstance
    have hA_meas : @MeasurableSet Ω mΩ A := hX hs_meas
    have hB_meas : @MeasurableSet Ω mΩ B := hY ht_meas
    have hC_meas : @MeasurableSet Ω mΩ C := hW hu_meas
    have hmW : mW ≤ mΩ := by
      dsimp [mW]
      exact sup_le hm hW.comap_le
    have hm_le_mW : m ≤ mW := by
      dsimp [mW]
      exact le_sup_left
    have hC_mW : @MeasurableSet Ω mW C := by
      dsimp [mW, C]
      exact Measurable.of_comap_le le_sup_right hu_meas
    have hC_sm : @MeasureTheory.StronglyMeasurable Ω ℝ _ mW oneC :=
      MeasureTheory.stronglyMeasurable_const.indicator hC_mW
    have hceA_m : @MeasureTheory.StronglyMeasurable Ω ℝ _ m (μ[oneA | m]) :=
      MeasureTheory.stronglyMeasurable_condExp
    have hceA_m_mW : @MeasureTheory.StronglyMeasurable Ω ℝ _ mW (μ[oneA | m]) :=
      hceA_m.mono hm_le_mW
    have hA_int : MeasureTheory.Integrable oneA μ := by
      refine (MeasureTheory.integrable_indicator_iff hA_meas).2 ?_
      exact MeasureTheory.integrableOn_const
    have hB_int : MeasureTheory.Integrable oneB μ := by
      refine (MeasureTheory.integrable_indicator_iff hB_meas).2 ?_
      exact MeasureTheory.integrableOn_const
    have hC_int : MeasureTheory.Integrable oneC μ := by
      refine (MeasureTheory.integrable_indicator_iff hC_meas).2 ?_
      exact MeasureTheory.integrableOn_const
    have hAB_int : MeasureTheory.Integrable (oneA * oneB) μ := by
      refine ((MeasureTheory.integrable_indicator_iff (hA_meas.inter hB_meas)).2
        (MeasureTheory.integrableOn_const (μ := μ) (s := A ∩ B) (C := (1 : ℝ)))).congr ?_
      exact MeasureTheory.ae_of_all μ fun ω => by
        by_cases hωA : ω ∈ A <;> by_cases hωB : ω ∈ B <;> simp [oneA, oneB, hωA, hωB]
    have hBC_int : MeasureTheory.Integrable (oneB * oneC) μ := by
      refine ((MeasureTheory.integrable_indicator_iff (hB_meas.inter hC_meas)).2
        (MeasureTheory.integrableOn_const (μ := μ) (s := B ∩ C) (C := (1 : ℝ)))).congr ?_
      exact MeasureTheory.ae_of_all μ fun ω => by
        by_cases hωB : ω ∈ B <;> by_cases hωC : ω ∈ C <;> simp [oneB, oneC, hωB, hωC]
    have hABC_int : MeasureTheory.Integrable ((oneA * oneB) * oneC) μ := by
      refine ((MeasureTheory.integrable_indicator_iff ((hA_meas.inter hB_meas).inter hC_meas)).2
        (MeasureTheory.integrableOn_const (μ := μ) (s := (A ∩ B) ∩ C) (C := (1 : ℝ)))).congr ?_
      exact MeasureTheory.ae_of_all μ fun ω => by
        by_cases hωA : ω ∈ A <;> by_cases hωB : ω ∈ B <;> by_cases hωC : ω ∈ C <;>
          simp [oneA, oneB, oneC, hωA, hωB, hωC]
    have hCI1 :=
      (ProbabilityTheory.condIndepFun_iff_condExp_inter_preimage_eq_mul hX hY).mp
        h1 s t hs_meas ht_meas
    have hCI2 :=
      (ProbabilityTheory.condIndepFun_iff_condExp_inter_preimage_eq_mul hX hW).mp
        h2 s u hs_meas hu_meas
    have hdropA :
        μ[oneA | mW] =ᵐ[μ] μ[oneA | m] := by
      have hs_ind_meas : Measurable (s.indicator (fun _ : α => (1 : ℝ))) := by fun_prop
      have hone : oneA = fun ω => s.indicator (fun _ : α => (1 : ℝ)) (X ω) := by
        funext ω
        by_cases hω : X ω ∈ s <;> simp [oneA, A, hω]
      rw [hone]
      simpa [mW] using
        (condExp_sup_comap_eq_of_condIndep hm hW hX h2
          (h := s.indicator (fun _ : α => (1 : ℝ))) hs_ind_meas hA_int)
    have hpullC_AB :
        μ[(oneA * oneB) * oneC | mW] =ᵐ[μ] μ[oneA * oneB | mW] * oneC := by
      exact MeasureTheory.condExp_mul_of_stronglyMeasurable_right (m := mW)
        (f := oneA * oneB) (g := oneC) hC_sm hABC_int hAB_int
    have hpullC_B :
        μ[oneB * oneC | mW] =ᵐ[μ] μ[oneB | mW] * oneC := by
      exact MeasureTheory.condExp_mul_of_stronglyMeasurable_right (m := mW)
        (f := oneB) (g := oneC) hC_sm hBC_int hB_int
    have hAB_mW :
        μ[oneA * oneB | mW] =ᵐ[μ] μ[oneA | mW] * μ[oneB | mW] := by
      have hsets :
          μ⟦X ⁻¹' s ∩ Y ⁻¹' t | mW⟧ =ᵐ[μ] μ[oneA * oneB | mW] := by
        rw [show X ⁻¹' s ∩ Y ⁻¹' t = A ∩ B by rfl]
        rw [show (fun _ : Ω => (1 : ℝ)) = 1 from rfl, Set.inter_indicator_one]
        rfl
      exact hsets.symm.trans hCI1
    have hAB_mW_drop :
        μ[oneA * oneB | mW] =ᵐ[μ] μ[oneA | m] * μ[oneB | mW] :=
      hAB_mW.trans (hdropA.mul (Filter.EventuallyEq.rfl))
    have hABC_tower :
        μ[(oneA * oneB) * oneC | m] =ᵐ[μ]
          μ[μ[(oneA * oneB) * oneC | mW] | m] := by
      exact (MeasureTheory.condExp_condExp_of_le
        (f := (oneA * oneB) * oneC) (m₁ := m) (m₂ := mW) (m₀ := mΩ)
        hm_le_mW hmW).symm
    have hinner_ABC :
        μ[μ[(oneA * oneB) * oneC | mW] | m] =ᵐ[μ]
          μ[(μ[oneA | m] * μ[oneB | mW]) * oneC | m] := by
      exact MeasureTheory.condExp_congr_ae (hpullC_AB.trans
        (hAB_mW_drop.mul (Filter.EventuallyEq.rfl)))
    have hpullA :
        μ[(μ[oneA | m] * μ[oneB | mW]) * oneC | m] =ᵐ[μ]
          μ[oneA | m] * μ[μ[oneB | mW] * oneC | m] := by
      have hint :
          MeasureTheory.Integrable ((μ[oneA | m] * μ[oneB | mW]) * oneC) μ := by
        exact (MeasureTheory.integrable_condExp (m := mW)
          (f := (oneA * oneB) * oneC) (μ := μ)).congr
            (hpullC_AB.trans (hAB_mW_drop.mul (Filter.EventuallyEq.rfl)))
      have hint_assoc :
          MeasureTheory.Integrable (μ[oneA | m] * (μ[oneB | mW] * oneC)) μ :=
        hint.congr (MeasureTheory.ae_of_all μ fun ω => by ring_nf)
      have hB_mW_C_int :
          MeasureTheory.Integrable (μ[oneB | mW] * oneC) μ :=
        (MeasureTheory.integrable_condExp (m := mW) (f := oneB * oneC) (μ := μ)).congr
          hpullC_B
      calc
        μ[(μ[oneA | m] * μ[oneB | mW]) * oneC | m]
            =ᵐ[μ] μ[μ[oneA | m] * (μ[oneB | mW] * oneC) | m] := by
              refine MeasureTheory.condExp_congr_ae ?_
              exact MeasureTheory.ae_of_all μ fun ω => by ring_nf
        _ =ᵐ[μ] μ[oneA | m] * μ[μ[oneB | mW] * oneC | m] :=
          MeasureTheory.condExp_mul_of_stronglyMeasurable_left (m := m)
            (f := μ[oneA | m]) (g := μ[oneB | mW] * oneC) hceA_m hint_assoc
            hB_mW_C_int
    have hBC_tower :
        μ[oneB * oneC | m] =ᵐ[μ] μ[μ[oneB * oneC | mW] | m] := by
      exact (MeasureTheory.condExp_condExp_of_le
        (f := oneB * oneC) (m₁ := m) (m₂ := mW) (m₀ := mΩ)
        hm_le_mW hmW).symm
    have hBC_inner :
        μ[μ[oneB * oneC | mW] | m] =ᵐ[μ] μ[μ[oneB | mW] * oneC | m] :=
      MeasureTheory.condExp_congr_ae hpullC_B
    have hleft_sets :
        μ⟦X ⁻¹' s ∩ pair ⁻¹' (t ×ˢ u) | m⟧
          =ᵐ[μ] μ[(oneA * oneB) * oneC | m] := by
      rw [show X ⁻¹' s ∩ pair ⁻¹' (t ×ˢ u) = (A ∩ B) ∩ C by
        ext ω
        simp [A, B, C, pair, and_assoc]]
      rw [show (fun _ : Ω => (1 : ℝ)) = 1 from rfl, Set.inter_indicator_one]
      refine MeasureTheory.condExp_congr_ae ?_
      exact MeasureTheory.ae_of_all μ fun ω => by
        by_cases hωA : ω ∈ A <;> by_cases hωB : ω ∈ B <;> by_cases hωC : ω ∈ C <;>
          simp [oneA, oneB, oneC, hωA, hωB, hωC]
    have hpair_sets :
        μ⟦pair ⁻¹' (t ×ˢ u) | m⟧ =ᵐ[μ] μ[oneB * oneC | m] := by
      rw [show pair ⁻¹' (t ×ˢ u) = B ∩ C by
        ext ω
        simp [B, C, pair]]
      rw [show (fun _ : Ω => (1 : ℝ)) = 1 from rfl, Set.inter_indicator_one]
      rfl
    calc
      μ⟦X ⁻¹' s ∩ pair ⁻¹' (t ×ˢ u) | m⟧
          =ᵐ[μ] μ[(oneA * oneB) * oneC | m] := hleft_sets
      _ =ᵐ[μ] μ[μ[(oneA * oneB) * oneC | mW] | m] := hABC_tower
      _ =ᵐ[μ] μ[(μ[oneA | m] * μ[oneB | mW]) * oneC | m] := hinner_ABC
      _ =ᵐ[μ] μ[oneA | m] * μ[μ[oneB | mW] * oneC | m] := hpullA
      _ =ᵐ[μ] μ[oneA | m] * μ[μ[oneB * oneC | mW] | m] := by
        exact (Filter.EventuallyEq.rfl).mul (MeasureTheory.condExp_congr_ae hpullC_B.symm)
      _ =ᵐ[μ] μ[oneA | m] * μ[oneB * oneC | m] := by
        exact (Filter.EventuallyEq.rfl).mul hBC_tower.symm
      _ =ᵐ[μ] μ⟦X ⁻¹' s | m⟧ * μ⟦pair ⁻¹' (t ×ˢ u) | m⟧ := by
        exact (Filter.EventuallyEq.rfl).mul hpair_sets.symm
  rw [ProbabilityTheory.condIndepFun_iff_condIndep]
  have hpX_eq : xsets = (fun r : Set α => X ⁻¹' r) '' {s : Set α | MeasurableSet s} := by
    ext q
    constructor
    · rintro ⟨s, hs, hq⟩
      exact ⟨s, hs, hq⟩
    · rintro ⟨s, hs, hq⟩
      exact ⟨s, hs, hq⟩
  have hpPair_eq :
      pairsets = (fun r : Set (β × γ) => pair ⁻¹' r) ''
        Set.image2 (· ×ˢ ·) {t : Set β | MeasurableSet t} {u : Set γ | MeasurableSet u} := by
    ext q
    constructor
    · rintro ⟨t, ht, u, hu, hq⟩
      exact ⟨t ×ˢ u, ⟨t, ht, u, hu, rfl⟩, hq⟩
    · rintro ⟨r, ⟨t, ht, u, hu, rfl⟩, hq⟩
      exact ⟨t, ht, u, hu, hq⟩
  have hgenX : (inferInstance : MeasurableSpace α).comap X =
      MeasurableSpace.generateFrom xsets := by
    rw [show (inferInstance : MeasurableSpace α) =
      MeasurableSpace.generateFrom {s : Set α | MeasurableSet s} by
        exact (MeasurableSpace.generateFrom_measurableSet (α := α)).symm]
    rw [MeasurableSpace.comap_generateFrom]
    rfl
  have hgenPair : (inferInstance : MeasurableSpace (β × γ)).comap pair =
      MeasurableSpace.generateFrom pairsets := by
    rw [hpPair_eq, ← generateFrom_prod, MeasurableSpace.comap_generateFrom]
  rw [hgenX, hgenPair]
  exact ProbabilityTheory.CondIndepSets.condIndep' hpX_meas hpPair_meas hpX_pi hpPair_pi hrect

/-- For [coordinate sets `X`, `Y`, `W`, `Z`, and `I`](hyp:X,Y,W,Z,I),
[a decidable index type](hyp:M), [measurable value spaces](hyp:Ω),
[inclusions of the four blocks in `I`](hyp:hX,hY,hW,hZ), [a finite measure `μ`](hyp:μ),
[the first conditional independence](hyp:h1), and [the second one](hyp:h2),
[contraction holds for the coordinate projections](goal). -/
theorem condIndep_valuesProjection_contraction
    {M : Type*} [DecidableEq M]
    {I X Y W Z : Finset M}
    {Ω : M → Type*} [∀ n, MeasurableSpace (Ω n)]
    [StandardBorelSpace (ValuesOn I Ω)]
    (hX : X ⊆ I) (hY : Y ⊆ I) (hW : W ⊆ I)
    (hZ : Z ⊆ I)
    {μ : MeasureTheory.Measure (ValuesOn I Ω)} [MeasureTheory.IsFiniteMeasure μ]
    (h1 :
      ProbabilityTheory.CondIndepFun
        (MeasurableSpace.comap
          (valuesProjection (Ω := Ω) (Finset.union_subset hZ hW)) inferInstance)
        (comap_valuesProjection_le (Ω' := Ω) (Finset.union_subset hZ hW))
        (valuesProjection (Ω := Ω) hX)
        (valuesProjection (Ω := Ω) hY)
        μ)
    (h2 :
      ProbabilityTheory.CondIndepFun
        (MeasurableSpace.comap (valuesProjection (Ω := Ω) hZ) inferInstance)
        (comap_valuesProjection_le (Ω' := Ω) hZ)
        (valuesProjection (Ω := Ω) hX)
        (valuesProjection (Ω := Ω) hW)
        μ) :
    ProbabilityTheory.CondIndepFun
      (MeasurableSpace.comap (valuesProjection (Ω := Ω) hZ) inferInstance)
      (comap_valuesProjection_le (Ω' := Ω) hZ)
      (valuesProjection (Ω := Ω) hX)
      (valuesProjection (Ω := Ω) (Finset.union_subset hY hW))
      μ := by
  let hYW : (Y ∪ W) ⊆ I := Finset.union_subset hY hW
  let hZW : (Z ∪ W) ⊆ I := Finset.union_subset hZ hW
  have hσ :
      MeasurableSpace.comap (valuesProjection (Ω := Ω) hZW) inferInstance =
        MeasurableSpace.comap (valuesProjection (Ω := Ω) hZ) inferInstance ⊔
          MeasurableSpace.comap (valuesProjection (Ω := Ω) hW) inferInstance :=
    comap_valuesProjection_union_eq_sup (Ω' := Ω) hZ hW
  have h1' :
      ProbabilityTheory.CondIndepFun
        (MeasurableSpace.comap (valuesProjection (Ω := Ω) hZ) inferInstance ⊔
          MeasurableSpace.comap (valuesProjection (Ω := Ω) hW) inferInstance)
        (sup_le (comap_valuesProjection_le (Ω' := Ω) hZ)
          (comap_valuesProjection_le (Ω' := Ω) hW))
        (valuesProjection (Ω := Ω) hX)
        (valuesProjection (Ω := Ω) hY)
        μ := by
    simpa [hσ] using h1
  have hpair :
      ProbabilityTheory.CondIndepFun
        (MeasurableSpace.comap (valuesProjection (Ω := Ω) hZ) inferInstance)
        (comap_valuesProjection_le (Ω' := Ω) hZ)
        (valuesProjection (Ω := Ω) hX)
        (fun ξ : ValuesOn I Ω =>
          (valuesProjection (Ω := Ω) hY ξ, valuesProjection (Ω := Ω) hW ξ))
        μ :=
    condIndepFun_contraction_of_prodMk
      (m := MeasurableSpace.comap (valuesProjection (Ω := Ω) hZ) inferInstance)
      (mΩ := inferInstance)
      (μ := μ)
      (comap_valuesProjection_le (Ω' := Ω) hZ)
      (measurable_valuesProjection (Ω' := Ω) hX)
      (measurable_valuesProjection (Ω' := Ω) hY)
      (measurable_valuesProjection (Ω' := Ω) hW)
      h1' h2
  have hassembled :
      ProbabilityTheory.CondIndepFun
        (MeasurableSpace.comap (valuesProjection (Ω := Ω) hZ) inferInstance)
        (comap_valuesProjection_le (Ω' := Ω) hZ)
        (valuesProjection (Ω := Ω) hX)
        (fun ξ : ValuesOn I Ω =>
          valuesUnionMk (Ω := Ω) (valuesProjection (Ω := Ω) hY ξ)
            (valuesProjection (Ω := Ω) hW ξ))
        μ :=
    hpair.comp measurable_id (measurable_valuesUnionMk (Ω := Ω))
  simpa [Function.comp_def, valuesUnionMk_projection_comp (Ω' := Ω) hY hW]
    using hassembled

end Causalean.Mathlib.Probability.Independence.Conditional
