module
public import Tengoku.Causalean.Causalean.Mathlib.Probability.Independence.Basic
public import Tengoku.Causalean.Causalean.Mathlib.Probability.Independence.Conditional.CondExp_Part2
public import Tengoku.Causalean.Causalean.Mathlib.Probability.Independence.Conditional.Transport.AeRetraction
public import Tengoku

/-!
# Leave-one residual centering under finite product laws

This module packages the product law of an independent side variable and a finite
iid record array.  It proves that a one-record residual conditionally centered on
its covariate remains centered after adjoining the side variable and every other
record, and derives integrable leave-one pullout and distinct-coordinate
orthogonality identities.
-/

@[expose] public section

open MeasureTheory ProbabilityTheory
open Causalean.Mathlib.Probability.Independence
open Causalean.Mathlib.Probability.Independence.Conditional.Transport

noncomputable section

namespace Causalean.Mathlib.Probability.Independence.Conditional.FiniteProductResidual

variable {ι A Z C : Type*}
variable [MeasurableSpace A] [MeasurableSpace Z] [MeasurableSpace C]

/-- The [side law](hyp:ρ) and [record law](hyp:μ) determine [the joint law of an
independent side variable and a finite iid record array](goal), [given by their product
with the finite record product law](step:1). -/
def productLaw [Fintype ι] (ρ : Measure A) (μ : Measure Z) : Measure (A × (ι → Z)) :=
  ρ.prod (Measure.pi (fun _ : ι => μ))

/-- [Probability side and record laws](hyp:ρ,μ) make [their joint product law](goal)
a probability law, [by the probability-measure instances for products and finite product
measures](step:1). -/
instance instIsProbabilityMeasureProductLaw [Fintype ι] (ρ : Measure A) (μ : Measure Z)
    [IsProbabilityMeasure ρ] [IsProbabilityMeasure μ] :
    IsProbabilityMeasure (productLaw (ι := ι) ρ μ) := by
  unfold productLaw
  infer_instance

/-- For [a selected coordinate](hyp:i) and [a side-variable-and-record-array
realization](hyp:az), [the remaining-information map](goal) retains the side variable
and every record other than the selected one, [by projecting that realization](step:1). -/
def otherInfo (i : ι) (az : A × (ι → Z)) : A × ({j : ι // j ≠ i} → Z) :=
  (az.1, fun j => az.2 j.1)

/-- [A covariate map](hyp:X), [selected coordinate](hyp:i), and
[a side-variable-and-record-array realization](hyp:az) determine [the leave-one
information map](goal), which retains the side variable, the selected covariate, and
all other complete records, [by projecting that realization](step:1). -/
def leaveOneInfo (X : Z → C) (i : ι) (az : A × (ι → Z)) :
    A × C × ({j : ι // j ≠ i} → Z) :=
  (az.1, X (az.2 i), fun j => az.2 j.1)

/-- [A covariate map](hyp:X) and [a side-variable-and-record-array realization](hyp:az)
determine [the full covariate-information map](goal), which retains the side variable
and every record's covariate, [by applying the covariate map coordinatewise](step:1). -/
def covariateInfo (X : Z → C) (az : A × (ι → Z)) : A × (ι → C) :=
  (az.1, fun k => X (az.2 k))

/-- For [a selected coordinate](hyp:i), [the remaining-information map is
measurable](goal). -/
@[fun_prop]
theorem measurable_otherInfo (i : ι) : Measurable (otherInfo (A := A) (Z := Z) i) := by
  exact measurable_fst.prodMk (measurable_pi_lambda _ fun (j : {j : ι // j ≠ i}) =>
    (measurable_pi_apply j.1).comp measurable_snd)

/-- [A measurable covariate map](hyp:hX) makes [the leave-one information at the
selected coordinate](hyp:i) [measurable](goal). -/
@[fun_prop]
theorem measurable_leaveOneInfo {X : Z → C} (hX : Measurable X) (i : ι) :
    Measurable (leaveOneInfo (A := A) X i) := by
  exact measurable_fst.prodMk ((hX.comp ((measurable_pi_apply i).comp measurable_snd)).prodMk
    (measurable_pi_lambda _ fun (j : {j : ι // j ≠ i}) =>
      (measurable_pi_apply j.1).comp measurable_snd))

/-- [A measurable covariate map](hyp:hX) makes [the full covariate-information map
measurable](goal). -/
@[fun_prop]
theorem measurable_covariateInfo {X : Z → C} (hX : Measurable X) :
    Measurable (covariateInfo (ι := ι) (A := A) X) := by
  exact measurable_fst.prodMk (measurable_pi_lambda _ fun (k : ι) =>
    hX.comp ((measurable_pi_apply k).comp measurable_snd))

/-- For [a covariate map](hyp:X) and [selected coordinate](hyp:i), [the σ-algebra
generated by leave-one information is the join of the selected covariate σ-algebra
and the remaining-information σ-algebra](goal). -/
theorem comap_leaveOneInfo (X : Z → C) (i : ι) :
    MeasurableSpace.comap (leaveOneInfo (A := A) X i) inferInstance =
      MeasurableSpace.comap (fun az : A × (ι → Z) => X (az.2 i)) inferInstance ⊔
        MeasurableSpace.comap (otherInfo (A := A) (Z := Z) i) inferInstance := by
  unfold leaveOneInfo otherInfo
  simp only [inferInstance, Prod.instMeasurableSpace, MeasurableSpace.comap_prodMk]
  exact sup_left_comm _ _ _

/-- [A covariate map](hyp:X), [a selected coordinate](hyp:i), and [a distinct
off-coordinate record](hyp:j,hji) make [that record measurable from the selected
leave-one information](goal). -/
@[fun_prop]
theorem measurable_otherRecord_comap_leaveOne (X : Z → C) (i j : ι) (hji : j ≠ i) :
    @Measurable (A × (ι → Z)) Z
      (MeasurableSpace.comap (leaveOneInfo X i) inferInstance) inferInstance
      (fun az => az.2 j) := by
  have h : @Measurable (A × (ι → Z)) (A × C × ({j : ι // j ≠ i} → Z))
      (MeasurableSpace.comap (leaveOneInfo X i) inferInstance) inferInstance
      (leaveOneInfo X i) := Measurable.of_comap_le le_rfl
  exact (measurable_pi_apply (⟨j, hji⟩ : {j : ι // j ≠ i})).comp
    (measurable_snd.comp (measurable_snd.comp h))

/-- [A measurable covariate map](hyp:hX) and [a selected coordinate](hyp:i) make
[the full covariate-information map measurable from leave-one information](goal). -/
@[fun_prop]
theorem measurable_covariateInfo_comap_leaveOne {X : Z → C} (hX : Measurable X) (i : ι) :
    @Measurable (A × (ι → Z)) (A × (ι → C))
      (MeasurableSpace.comap (leaveOneInfo X i) inferInstance) inferInstance
      (covariateInfo X) := by
  have h : @Measurable (A × (ι → Z)) (A × C × ({j : ι // j ≠ i} → Z))
      (MeasurableSpace.comap (leaveOneInfo X i) inferInstance) inferInstance
      (leaveOneInfo X i) := Measurable.of_comap_le le_rfl
  classical
  let : MeasurableSpace (A × (ι → Z)) :=
    MeasurableSpace.comap (leaveOneInfo X i) inferInstance
  unfold covariateInfo
  refine (measurable_fst.comp h).prodMk (measurable_pi_lambda _ fun (k : ι) => ?_)
  by_cases hki : k = i
  · subst k
    exact measurable_fst.comp (measurable_snd.comp h)
  · exact hX.comp (measurable_otherRecord_comap_leaveOne X i k hki)

/-- [Probability side and record laws](hyp:ρ,μ) make [projection to a selected
record](hyp:i) [preserve the one-record law](goal). -/
theorem measurePreserving_selectedRecord [Fintype ι] (ρ : Measure A) (μ : Measure Z)
    [IsProbabilityMeasure ρ] [IsProbabilityMeasure μ] (i : ι) :
    MeasurePreserving (fun az : A × (ι → Z) => az.2 i) (productLaw ρ μ) μ := by
  exact (measurePreserving_eval (fun _ : ι => μ) i).comp measurePreserving_snd

/-- [Probability side and record laws](hyp:ρ,μ) make [the selected record](hyp:i)
[independent of the side variable together with every other record](goal). -/
theorem indepFun_selectedRecord_otherInfo
    {ι A Z : Type*} [Fintype ι]
    [MeasurableSpace A] [MeasurableSpace Z]
    (ρ : Measure A) (μ : Measure Z) [IsProbabilityMeasure ρ] [IsProbabilityMeasure μ]
    (i : ι) :
    IndepFun (fun az : A × (ι → Z) => az.2 i) (otherInfo i) (productLaw ρ μ) := by
  classical
  let P : Measure (ι → Z) := Measure.pi (fun _ : ι => μ)
  let rest : (ι → Z) → ({j : ι // j ≠ i} → Z) := fun x j => x j.1
  have hrest : Measurable rest :=
    measurable_pi_lambda _ fun j => measurable_pi_apply j.1
  have hcoords : iIndepFun (fun j (x : ι → Z) => x j) P :=
    iIndepFun_pi (X := fun _ (z : Z) => z) (fun _ => aemeasurable_id)
  have hblocks : IndepFun (fun x : ι → Z => x i) rest P := by
    have h := hcoords.indepFun_finset {i} (Finset.univ.erase i)
      (by simp) (fun j => measurable_pi_apply j)
    exact h.comp (measurable_pi_apply (⟨i, by simp⟩ : {j : ι // j ∈ ({i} : Finset ι)}))
      (measurable_pi_lambda _ fun (j : {j : ι // j ≠ i}) =>
        measurable_pi_apply (⟨j.1, by simp [j.2]⟩ : {j : ι // j ∈ Finset.univ.erase i}))
  let ν := P.map rest
  have : IsProbabilityMeasure ν := Measure.isProbabilityMeasure_map hrest.aemeasurable
  have hpair : MeasurePreserving (fun x : ι → Z => (x i, rest x)) P (μ.prod ν) := by
    refine ⟨(measurable_pi_apply i).prodMk hrest, ?_⟩
    rw [hblocks.map_prod_eq_prod_map_map (measurable_pi_apply i).aemeasurable
      hrest.aemeasurable, (measurePreserving_eval (fun _ : ι => μ) i).map_eq]
  have hside := (MeasurePreserving.id ρ).prod hpair
  have hunassoc := (measurePreserving_prodAssoc ρ μ ν).symm MeasurableEquiv.prodAssoc
  have hswap := (Measure.measurePreserving_swap (μ := ρ) (ν := μ)).prod
    (MeasurePreserving.id ν)
  have hassoc := measurePreserving_prodAssoc μ ρ ν
  have hjoint : MeasurePreserving
      (fun az : A × (ι → Z) => (az.2 i, otherInfo i az))
      (productLaw ρ μ) (μ.prod (ρ.prod ν)) :=
    hassoc.comp (hswap.comp (hunassoc.comp hside))
  have hselected : MeasurePreserving (fun az : A × (ι → Z) => az.2 i)
      (productLaw ρ μ) μ := measurePreserving_fst.comp hjoint
  have hother : MeasurePreserving (otherInfo i) (productLaw ρ μ) (ρ.prod ν) :=
    measurePreserving_snd.comp hjoint
  apply (indepFun_iff_map_prod_eq_prod_map_map
    ((measurable_pi_apply i).comp measurable_snd).aemeasurable
    (measurable_otherInfo i).aemeasurable).2
  exact hjoint.map_eq.trans
    (congrArg₂ Measure.prod hselected.map_eq.symm hother.map_eq.symm)

/-- [Measurable record and additional-information maps](hyp:hY,hW) that are
[independent](hyp:hYW), together with [a measurable covariate map](hyp:hX), [a
measurable residual](hyp:hr), and [integrability of the pulled-back residual](hyp:hrY),
imply [that adjoining the additional information leaves the residual's covariate
conditional mean unchanged](goal). -/
theorem condExp_adjoin_independent_eq
    {Ω Z C B : Type*} [MeasurableSpace Ω] [StandardBorelSpace Ω]
    [MeasurableSpace Z] [MeasurableSpace C] [MeasurableSpace B]
    {P : Measure Ω} [IsProbabilityMeasure P]
    {Y : Ω → Z} {W : Ω → B} {X : Z → C} {r : Z → ℝ}
    (hY : Measurable Y) (hW : Measurable W)
    (hYW : IndepFun Y W P) (hX : Measurable X) (hr : Measurable r)
    (hrY : Integrable (fun ω => r (Y ω)) P) :
    P[fun ω => r (Y ω) |
      MeasurableSpace.comap (X ∘ Y) inferInstance ⊔ MeasurableSpace.comap W inferInstance]
      =ᵐ[P] P[fun ω => r (Y ω) | MeasurableSpace.comap (X ∘ Y) inferInstance] := by
  have hrY_meas : Measurable (r ∘ Y) := hr.comp hY
  have hXY_meas : Measurable (X ∘ Y) := hX.comp hY
  have hpair : IndepFun (fun ω => (r (Y ω), X (Y ω))) W P :=
    hYW.comp (φ := fun z => (r z, X z)) (ψ := id) (hr.prod hX) measurable_id
  have hbot := condIndepFun_bot_of_indepFun hW
    (hrY_meas.prod hXY_meas) hpair.symm
  have hCI : CondIndepFun (MeasurableSpace.comap (X ∘ Y) inferInstance)
      hXY_meas.comap_le W (r ∘ Y) P := by
    simpa only [bot_sup_eq] using
      (condIndepFun_weak_union_of_prodMk (m := ⊥) bot_le
        hW hrY_meas hXY_meas hbot)
  exact condExp_sup_comap_eq_of_condIndep hXY_meas.comap_le
    hW hrY_meas hCI.symm (h := id) measurable_id hrY

variable [Fintype ι]
variable [StandardBorelSpace A] [StandardBorelSpace Z]
variable (ρ : Measure A) (μ : Measure Z) [IsProbabilityMeasure ρ] [IsProbabilityMeasure μ]
variable {X : Z → C} {r : Z → ℝ}

/-- [A measurable covariate map and residual](hyp:hX,hr), [integrability of the
residual](hyp:hir), [one-record conditional centering](hyp:hzero), [probability side
and record laws](hyp:ρ,μ), and [a selected coordinate](hyp:i) imply [zero conditional
mean of that residual given the selected covariate, the side variable, and all other
records](goal). -/
theorem condExp_residual_eq_zero_of_leaveOne
    (hX : Measurable X) (hr : Measurable r) (hir : Integrable r μ)
    (hzero : μ[r | MeasurableSpace.comap X inferInstance] =ᵐ[μ] 0) (i : ι) :
    (productLaw ρ μ)[fun az => r (az.2 i) |
      MeasurableSpace.comap (leaveOneInfo X i) inferInstance] =ᵐ[productLaw ρ μ] 0 := by
  classical
  have hp := measurePreserving_selectedRecord ρ μ i
  have hi : Integrable (fun az : A × (ι → Z) => r (az.2 i)) (productLaw ρ μ) :=
    hp.integrable_comp_of_integrable hir
  have hd := condExp_adjoin_independent_eq hp.measurable (measurable_otherInfo i)
    (indepFun_selectedRecord_otherInfo ρ μ i) hX hr hi
  have ht := condExp_comp_of_map_eq (fun az : A × (ι → Z) => az.2 i) hp.measurable
    hp.map_eq (MeasurableSpace.comap X inferInstance) hX.comap_le hir
  have hz : (fun az : A × (ι → Z) =>
      (μ[r | MeasurableSpace.comap X inferInstance]) (az.2 i))
        =ᵐ[productLaw ρ μ] 0 := by
    filter_upwards [hp.quasiMeasurePreserving.ae_eq_comp hzero] with az hza
    exact hza
  rw [comap_leaveOneInfo]
  apply hd.trans
  have ht' : (productLaw ρ μ)[fun az => r (az.2 i) |
      MeasurableSpace.comap (X ∘ fun az : A × (ι → Z) => az.2 i) inferInstance]
      =ᵐ[productLaw ρ μ] fun az => (μ[r | MeasurableSpace.comap X inferInstance]) (az.2 i) := by
    simpa only [MeasurableSpace.comap_comp, Function.comp_def] using ht
  exact ht'.trans hz

/-- [A measurable covariate map and residual](hyp:hX,hr), [integrability of the
residual](hyp:hir), [one-record conditional centering](hyp:hzero), [probability side
and record laws](hyp:ρ,μ), [a selected coordinate](hyp:i), [a leave-one almost-everywhere
strongly measurable coefficient](hyp:c,hc), and [integrability of its residual
product](hyp:hcr) imply [that the coefficient-residual integral is zero](goal). -/
theorem integral_mul_residual_eq_zero_of_leaveOne
    (hX : Measurable X) (hr : Measurable r) (hir : Integrable r μ)
    (hzero : μ[r | MeasurableSpace.comap X inferInstance] =ᵐ[μ] 0)
    (i : ι) (c : A × (ι → Z) → ℝ)
    (hc : AEStronglyMeasurable[MeasurableSpace.comap (leaveOneInfo X i) inferInstance]
      c (productLaw ρ μ))
    (hcr : Integrable (fun az => c az * r (az.2 i)) (productLaw ρ μ)) :
    ∫ az, c az * r (az.2 i) ∂productLaw ρ μ = 0 := by
  have hm := (measurable_leaveOneInfo (A := A) hX i).comap_le
  have hi : Integrable (fun az : A × (ι → Z) => r (az.2 i)) (productLaw ρ μ) :=
    (measurePreserving_selectedRecord ρ μ i).integrable_comp_of_integrable hir
  have hp := condExp_mul_of_aestronglyMeasurable_left hc hcr hi
  have hfun : c * (fun az => r (az.2 i)) = (fun az => c az * r (az.2 i)) := by
    funext az
    exact Pi.mul_apply c _ az
  rw [hfun] at hp
  have hz := condExp_residual_eq_zero_of_leaveOne ρ μ hX hr hir hzero i
  have hpz : (productLaw ρ μ)[fun az => c az * r (az.2 i) |
      MeasurableSpace.comap (leaveOneInfo X i) inferInstance] =ᵐ[productLaw ρ μ] 0 := by
    filter_upwards [hp, hz] with az hpa hza
    simpa only [Pi.mul_apply, hza, Pi.zero_apply, mul_zero] using hpa
  calc
    ∫ az, c az * r (az.2 i) ∂productLaw ρ μ =
        ∫ az, ((productLaw ρ μ)[fun az => c az * r (az.2 i) |
          MeasurableSpace.comap (leaveOneInfo X i) inferInstance]) az ∂productLaw ρ μ :=
      (integral_condExp hm).symm
    _ = ∫ _, (0 : ℝ) ∂productLaw ρ μ := integral_congr_ae hpz
    _ = 0 := integral_zero _ _

/-- [A measurable covariate map and residual](hyp:hX,hr), [integrability of the
residual](hyp:hir), [one-record conditional centering](hyp:hzero), [probability side
and record laws](hyp:ρ,μ), [a selected coordinate](hyp:i), [a measurable covariate
coefficient](hyp:b,hb), and [integrability of its residual product](hyp:hbr) imply
[that the covariate-weighted residual integral is zero](goal). -/
theorem integral_covariate_mul_residual_eq_zero
    (hX : Measurable X) (hr : Measurable r) (hir : Integrable r μ)
    (hzero : μ[r | MeasurableSpace.comap X inferInstance] =ᵐ[μ] 0)
    (i : ι) (b : A × (ι → C) → ℝ) (hb : Measurable b)
    (hbr : Integrable (fun az => b (covariateInfo X az) * r (az.2 i)) (productLaw ρ μ)) :
    ∫ az, b (covariateInfo X az) * r (az.2 i) ∂productLaw ρ μ = 0 := by
  apply integral_mul_residual_eq_zero_of_leaveOne ρ μ hX hr hir hzero i _ _ hbr
  exact (hb.comp (measurable_covariateInfo_comap_leaveOne hX i))
    |>.stronglyMeasurable.aestronglyMeasurable

/-- [A measurable covariate map and residual](hyp:hX,hr), [integrability of the
residual](hyp:hir), [one-record conditional centering](hyp:hzero), [probability side
and record laws](hyp:ρ,μ), [distinct coordinates](hyp:i,j,hij), [a measurable covariate
coefficient](hyp:b,hb), and [integrability of the triple product](hyp:hbrr) imply
[that the covariate-weighted product of the two residuals has zero integral](goal). -/
theorem integral_covariate_mul_residual_mul_residual_eq_zero
    (hX : Measurable X) (hr : Measurable r) (hir : Integrable r μ)
    (hzero : μ[r | MeasurableSpace.comap X inferInstance] =ᵐ[μ] 0)
    (i j : ι) (hij : i ≠ j) (b : A × (ι → C) → ℝ) (hb : Measurable b)
    (hbrr : Integrable
      (fun az => b (covariateInfo X az) * r (az.2 i) * r (az.2 j)) (productLaw ρ μ)) :
    ∫ az, b (covariateInfo X az) * r (az.2 i) * r (az.2 j) ∂productLaw ρ μ = 0 := by
  have hc : AEStronglyMeasurable[MeasurableSpace.comap (leaveOneInfo X i) inferInstance]
      (fun az => b (covariateInfo X az) * r (az.2 j)) (productLaw ρ μ) :=
    ((hb.comp (measurable_covariateInfo_comap_leaveOne hX i)).mul
      (hr.comp (measurable_otherRecord_comap_leaveOne X i j (Ne.symm hij))))
      |>.stronglyMeasurable.aestronglyMeasurable
  have hprod : Integrable
      (fun az => (b (covariateInfo X az) * r (az.2 j)) * r (az.2 i)) (productLaw ρ μ) := by
    simpa only [mul_right_comm] using hbrr
  simpa only [mul_right_comm] using
    integral_mul_residual_eq_zero_of_leaveOne ρ μ hX hr hir hzero i _ hc hprod

end Causalean.Mathlib.Probability.Independence.Conditional.FiniteProductResidual
