module
public import Tengoku.Causalean.Causalean.Graph.Density.FiniteDAG.Main

/-!
# Coordinate blocks for ordered finite-DAG arguments

This module packages an arbitrary numeric topological ranking, its predecessor set, and the
measurability facts for the coordinate maps used by the ordered local Markov theorem.
-/

@[expose] public section

open MeasureTheory

noncomputable section

namespace Causalean.Graph.FiniteDensity

open Causalean.Mathlib.MeasureTheory.FiniteCoordinate

variable {V : Type*} [DecidableEq V] [Fintype V]
variable {X : V → Type*} [∀ i, MeasurableSpace (X i)]

/-- A [finite DAG](hyp:G) is equipped with [a numeric position for each vertex](hyp:rank),
[distinct positions for distinct vertices](hyp:injective_rank), and [strictly increasing positions
along every directed edge](hyp:edge_lt). -/
structure TopologicalRanking (G : Causalean.Graph.DAG V) where
  /-- The numeric position of a vertex. -/
  rank : V → ℕ
  /-- Distinct vertices have distinct positions. -/
  injective_rank : Function.Injective rank
  /-- Every directed edge points from a smaller position to a larger position. -/
  edge_lt : ∀ {u v : V}, G.edge u v → rank u < rank v

/-- A [finite DAG](hyp:G) has [the canonical topological ranking supplied by its DAG API](goal). -/
def canonicalTopologicalRanking (G : Causalean.Graph.DAG V) : TopologicalRanking G where
  rank := G.topoOrder
  injective_rank := G.topoOrder_injective
  edge_lt := G.topoOrder_lt _ _

/-- A [topological ranking](hyp:τ) and [vertex](hyp:i) determine [the finite set of vertices
strictly preceding that vertex](goal). -/
def predecessors {G : Causalean.Graph.DAG V} (τ : TopologicalRanking G) (i : V) : Finset V :=
  Finset.univ.filter (fun j ↦ τ.rank j < τ.rank i)

/-- A [topological ranking](hyp:τ) places [every parent of a vertex](hyp:i) [among its
predecessors](goal). -/
theorem parents_subset_predecessors {G : Causalean.Graph.DAG V}
    (τ : TopologicalRanking G) (i : V) :
    G.parents i ⊆ predecessors τ i := by
  intro j hj
  rw [predecessors, Finset.mem_filter]
  exact ⟨Finset.mem_univ j, τ.edge_lt (G.mem_parents.mp hj)⟩

/-- A [vertex](hyp:i) does [not belong to its strict predecessor set](goal). -/
theorem not_mem_predecessors {G : Causalean.Graph.DAG V}
    (τ : TopologicalRanking G) (i : V) :
    i ∉ predecessors τ i := by
  simp [predecessors]

/-- The [predecessor set](hyp:τ,i) of a vertex in a [topologically ranked DAG](hyp:G) [contains
all parents of each of its members](goal). -/
theorem parentClosed_predecessors {G : Causalean.Graph.DAG V}
    (τ : TopologicalRanking G) (i : V) :
    ParentClosed G (predecessors τ i) := by
  intro j hj k hk
  rw [predecessors, Finset.mem_filter] at hj ⊢
  exact ⟨Finset.mem_univ k, lt_trans (τ.edge_lt (G.mem_parents.mp hk)) hj.2⟩

/-- Reading a [single coordinate](hyp:i) from a finite product [is measurable](goal). -/
@[fun_prop]
theorem measurable_orderedCoordinate (i : V) :
    Measurable (fun x : ∀ j, X j ↦ x i) := by
  exact measurable_pi_apply i

/-- Projecting onto the [predecessors outside a conditioning set](hyp:τ,i,A) [is
measurable](goal). -/
@[fun_prop]
theorem measurable_predecessorResidualProjection {G : Causalean.Graph.DAG V}
    (τ : TopologicalRanking G) (i : V) (A : Finset V) :
    Measurable (coordinateProjection (X := X) (predecessors τ i \ A)) := by
  exact measurable_coordinateProjection _

/-- The σ-algebra generated by projection onto a [conditioning coordinate block](hyp:A) [is
no finer than the ambient product σ-algebra](goal). -/
theorem coordinateConditioning_comap_le (A : Finset V) :
    MeasurableSpace.comap (coordinateProjection (X := X) A) inferInstance ≤
      (inferInstance : MeasurableSpace (∀ j, X j)) := by
  exact (measurable_coordinateProjection A).comap_le

end Causalean.Graph.FiniteDensity
