/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan
-/

module
public import Tengoku.Causalean.Causalean.Discovery.LinearDisentanglement.Quantitative.Definitions
public import Tengoku

/-!
# Two-coordinate deformations for collinear congruence families

This module defines the paper-independent objects used to deform a simultaneous
congruence representation along an affine-collinear pair of diagonal shifts.  The
deformation first mixes the two selected rows and then rescales them so that a
unit-diagonal normalization is retained.
-/

@[expose] public section

noncomputable section

open scoped Matrix

namespace Causalean.Discovery.LinearDisentanglement.SimultaneousCongruence

open Causalean.Discovery.LinearDisentanglement.Quantitative

/-- A concrete certificate that the selected two-coordinate shift cloud is contained in
the affine line `u x + v y = c`, with a nonzero normal vector. -/
structure AffineLineCertificate {d : ℕ} {E : Type*} (s : E → Fin d → ℝ)
    (i j : Fin d) where
  /-- First component of the line's normal vector. -/
  u : ℝ
  /-- Second component of the line's normal vector. -/
  v : ℝ
  /-- Affine offset of the line. -/
  c : ℝ
  /-- The normal vector is nonzero. -/
  normal_ne : u ≠ 0 ∨ v ≠ 0
  /-- Every selected shift pair lies on the certified affine line. -/
  equation : ∀ e, u * s e i + v * s e j = c

/-- [The elementary two-row shear](goal) traces the observationally ambiguous direction associated
with [selected coordinates `i,j`](hyp:i,j), [line normal `u,v` and deformation `t`](hyp:u,v,t) in
[dimension `d`](hyp:d). It perturbs only the selected pair, or their common diagonal if they
coincide. -/
def pairShear {d : ℕ} (i j : Fin d) (u v t : ℝ) : SqMatrix d :=
  1 + Matrix.single i j (t * v) + Matrix.single j i (t * u)

/-- [The first normalization denominator](goal) is the row-scale correction that keeps the first
selected diagonal entry fixed after shearing [reference matrix `B`](hyp:B) at [coordinates
`i,j`](hyp:i,j), with [coefficient `v` and magnitude `t`](hyp:v,t) in [dimension `d`](hyp:d). -/
def firstNormalizationDenom {d : ℕ} (B : SqMatrix d) (i j : Fin d)
    (v t : ℝ) : ℝ :=
  1 + t * v * B j i

/-- [The second normalization denominator](goal) is the row-scale correction that keeps the second
selected diagonal entry fixed after shearing [reference matrix `B`](hyp:B) at [coordinates
`i,j`](hyp:i,j), with [coefficient `u` and magnitude `t`](hyp:u,t) in [dimension `d`](hyp:d). -/
def secondNormalizationDenom {d : ℕ} (B : SqMatrix d) (i j : Fin d)
    (u t : ℝ) : ℝ :=
  1 + t * u * B i j

/-- [The pair row normalizer](goal) compensates row scaling after deforming [selected coordinates
`i,j`](hyp:i,j) of [reference matrix `B`](hyp:B), using [line normal `u,v` and magnitude
`t`](hyp:u,v,t) in [dimension `d`](hyp:d). It rescales only the selected rows; zero denominators
use the library's zero reciprocal convention. -/
def pairRowNormalizer {d : ℕ} (B : SqMatrix d) (i j : Fin d)
    (u v t : ℝ) : SqMatrix d :=
  Matrix.diagonal fun k ↦
    if k = i then (firstNormalizationDenom B i j v t)⁻¹
    else if k = j then (secondNormalizationDenom B i j u t)⁻¹
    else 1

/-- [The normalized two-coordinate deformation](goal) combines a shear with row rescaling, moving
along the ambiguity generated by [coordinates `i,j`](hyp:i,j) and [line normal `u,v` at magnitude
`t`](hyp:u,v,t) for [reference matrix `B`](hyp:B) in [dimension `d`](hyp:d). -/
def normalizedPairDeformation {d : ℕ} (B : SqMatrix d) (i j : Fin d)
    (u v t : ℝ) : SqMatrix d :=
  pairRowNormalizer B i j u v t * pairShear i j u v t

/-- [The deformed diagonalizer](goal) applies the normalized ambiguity direction to [reference
diagonalizer `B`](hyp:B), mixing [coordinates `i,j`](hyp:i,j) according to [line normal `u,v` and
magnitude `t`](hyp:u,v,t) in [dimension `d`](hyp:d). -/
def deformedDiagonalizer {d : ℕ} (B : SqMatrix d) (i j : Fin d)
    (u v t : ℝ) : SqMatrix d :=
  normalizedPairDeformation B i j u v t * B

/-- [Pair-cycle admissibility](goal) rules out the singular two-coordinate feedback cycle in
[matrix `B`](hyp:B): the opposite entries at [coordinates `i,j`](hyp:i,j) must not multiply to
one in [dimension `d`](hyp:d). -/
def PairCycleAdmissible {d : ℕ} (B : SqMatrix d) (i j : Fin d) : Prop :=
  B i j * B j i ≠ 1

/-- [The common shift cross term](goal) is the off-diagonal contribution shared by all environments
after deforming [reference matrix `B`](hyp:B) at [coordinates `i,j`](hyp:i,j), determined by
[line normal, offset, and magnitude `u,v,c,t`](hyp:u,v,c,t) in [dimension `d`](hyp:d). -/
def commonShiftCrossTerm {d : ℕ} (B : SqMatrix d) (i j : Fin d)
    (u v c t : ℝ) : ℝ :=
  (firstNormalizationDenom B i j v t)⁻¹ *
    (secondNormalizationDenom B i j u t)⁻¹ * (t * c)

/-- [The symmetric selected-pair matrix](goal) places [value `x`](hyp:x) in both orientations of
[coordinates `i,j`](hyp:i,j) in [dimension `d`](hyp:d), isolating the common cross term created
by a pair deformation. -/
def pairSymmetricOffDiagonal {d : ℕ} (i j : Fin d) (x : ℝ) : SqMatrix d :=
  Matrix.single i j x + Matrix.single j i x

/-- [The deformed invariant matrix](goal) absorbs the environment-independent cross term so the
represented covariance family can remain unchanged. From [reference diagonalizer and invariant
matrix](hyp:B,Ω), [selected coordinates](hyp:i,j), and [line data and magnitude](hyp:u,v,c,t) in
[dimension `d`](hyp:d), it [first forms the normalized pair deformation](step:1), then transforms
the invariant and adds the common symmetric term. -/
def deformedInvariant {d : ℕ} (B Ω : SqMatrix d) (i j : Fin d)
    (u v c t : ℝ) : SqMatrix d :=
  let T := normalizedPairDeformation B i j u v t
  T * Ω * T.transpose +
    pairSymmetricOffDiagonal i j (commonShiftCrossTerm B i j u v c t)

/-- [The deformed shift](goal) records the new environment-specific diagonal after transforming
[original shift `s`](hyp:s) through [reference diagonalizer `B`](hyp:B) at [coordinates
`i,j`](hyp:i,j), with [line normal `u,v` and magnitude `t`](hyp:u,v,t) in [dimension
`d`](hyp:d); it [first forms the normalized pair deformation](step:1). -/
def deformedShift {d : ℕ} (B : SqMatrix d) (i j : Fin d)
    (u v t : ℝ) (s : Fin d → ℝ) : Fin d → ℝ :=
  fun k ↦
    let T := normalizedPairDeformation B i j u v t
    (T * Matrix.diagonal s * T.transpose) k k

/-- [The represented covariance matrix](goal) maps [an invariant and diagonalizer](hyp:Ω,B)
plus [an environment-specific diagonal shift](hyp:s) back to observed coordinates in [dimension
`d`](hyp:d). An invertible diagonalizer is required for the intended interpretation; the library's
singular inverse convention returns zero otherwise. -/
def representedCovariance {d : ℕ} (B Ω : SqMatrix d) (s : Fin d → ℝ) : SqMatrix d :=
  B⁻¹ * (Ω + Matrix.diagonal s) * (B⁻¹).transpose

/-- [A covariance family is represented](goal) when every [environment in `E`](hyp:E) shares
[diagonalizer `B` and invariant component `Ω`](hyp:B,Ω) while varying only through [shift family
`s`](hyp:s), reproducing [covariances `Sigma`](hyp:Sigma) in [dimension `d`](hyp:d).
Invertibility is deliberately separate; a singular diagonalizer represents only the zero family. -/
def RepresentsCovarianceFamily {d : ℕ} {E : Type*} (Sigma : E → SqMatrix d)
    (B Ω : SqMatrix d) (s : E → Fin d → ℝ) : Prop :=
  ∀ e, Sigma e = representedCovariance B Ω (s e)

end Causalean.Discovery.LinearDisentanglement.SimultaneousCongruence
