/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan
-/

module
public import Tengoku.Causalean.Causalean.Graph.DSep.Ancestral

/-! # Ordered-local semi-graphoid definitions

This file defines `DAG.OrderedLocalSG`, the triples generated from a DAG's ordered-local
basis by symmetry, decomposition, weak union, and contraction. It also provides the
ambient-set containment theorem and the ancestral-cardinality and topological-height
measures used by the later peel induction.
-/

@[expose] public section

namespace Causalean.Graph

variable {V : Type*} [DecidableEq V] [Fintype V]

namespace DAG

variable (G : DAG V)

-- ============================================================
-- § 1. The ordered-local semi-graphoid closure
-- ============================================================

/-- For [a finite vertex population with decidable equality](hyp:V), [a directed acyclic
graph on that population](hyp:G), and [an ambient set of random vertices](hyp:R), the
[ordered-local semi-graphoid closure](goal) contains precisely the triples of finite vertex
sets generated by [the empty-set rule](hyp:nil), [the ordered-local basis](hyp:basis),
[symmetry](hyp:symm), [decomposition](hyp:decomp), [weak union](hyp:weakUnion), and
[contraction](hyp:contract).

    The basis constructor `basis` is the ordered/local Markov statement: a node `v`
    is independent of any block `P` of its non-descendants (with its random parents
    removed) given its random parents `parents v ∩ R`. The remaining constructors are
    exactly the four semi-graphoid axioms; there is intentionally no graphoid
    `intersection` constructor. `nil` records the trivial independence of the empty
    source set from anything.

    This is the combinatorial skeleton that, once interpreted under the joint
    distribution, yields the global Markov property. -/
inductive OrderedLocalSG (G : DAG V) (R : Finset V) :
    Finset V → Finset V → Finset V → Prop
  | nil (Y Z : Finset V) (hY : Y ⊆ R) (hZ : Z ⊆ R) : OrderedLocalSG G R ∅ Y Z
  | basis (v : V) (hv : v ∈ R) (P : Finset V)
      (hP : P ⊆ R) (hND : P ⊆ G.nonDescendants v) (hPa : G.parents v ∩ R ⊆ P) :
      OrderedLocalSG G R {v} (P \ (G.parents v ∩ R)) (G.parents v ∩ R)
  | symm {X Y Z : Finset V} : OrderedLocalSG G R X Y Z → OrderedLocalSG G R Y X Z
  | decomp {X Y W Z : Finset V} :
      OrderedLocalSG G R X (Y ∪ W) Z → OrderedLocalSG G R X Y Z
  | weakUnion {X Y W Z : Finset V} :
      OrderedLocalSG G R X (Y ∪ W) Z → OrderedLocalSG G R X Y (Z ∪ W)
  | contract {X Y W Z : Finset V} :
      OrderedLocalSG G R X Y (Z ∪ W) → OrderedLocalSG G R X W Z →
      OrderedLocalSG G R X (Y ∪ W) Z

/-- For [a finite directed acyclic graph, an ambient random set, and three query
sets](hyp:V,G,R,X,Y,Z), if [the query triple is derivable from the ordered-local
semi-graphoid rules](hyp:h), then [each query set is contained in the ambient random set](goal).

Every triple appearing in an ordered-local derivation has all three sets
    contained in the ambient random set `R`. Used by the SCM interpretation to
    recover the `⊆ randomVars` side-conditions of `FullCondIndep`. -/
theorem OrderedLocalSG.subset_random {G : DAG V} {R X Y Z : Finset V}
    (h : G.OrderedLocalSG R X Y Z) : X ⊆ R ∧ Y ⊆ R ∧ Z ⊆ R := by
  induction h with
  | nil Y Z hY hZ => exact ⟨Finset.empty_subset _, hY, hZ⟩
  | basis v hv P hP hND hPa =>
      refine ⟨Finset.singleton_subset_iff.mpr hv, ?_, Finset.inter_subset_right⟩
      exact (Finset.sdiff_subset).trans hP
  | symm _ ih => exact ⟨ih.2.1, ih.1, ih.2.2⟩
  | decomp _ ih =>
      exact ⟨ih.1, (Finset.subset_union_left).trans ih.2.1, ih.2.2⟩
  | weakUnion _ ih =>
      refine ⟨ih.1, (Finset.subset_union_left).trans ih.2.1, ?_⟩
      exact Finset.union_subset ih.2.2 ((Finset.subset_union_right).trans ih.2.1)
  | contract _ _ ih1 ih2 =>
      exact ⟨ih1.1, Finset.union_subset ih1.2.1 ih2.2.1, ih2.2.2⟩

-- ============================================================
-- § 2. Topological-maximum selection in an ancestral set
-- ============================================================

/-- For [a finite directed acyclic graph](hyp:V,G) and [two endpoint sets plus random
and fixed conditioning sets](hyp:X,Y,Zr,Zf), the [lexicographic peel measure](goal) pairs
[the size of the query's ancestral closure](step:1) with the topological height of its
random conditioning set.

When the topologically maximal query node moves out of the random conditioning set, the
first component stays equal while the second strictly decreases; every newly conditioned
node is topologically below the removed maximum. -/
noncomputable def peelMeasure (G : DAG V) (X Y Zr Zf : Finset V) : ℕ × ℕ :=
  ((G.ancestralSet (X ∪ Y ∪ Zr ∪ Zf)).card, Zr.sup (fun v => G.topoOrder v + 1))

-- ============================================================
-- § 2′. Topological-maximum selection in an ancestral set
-- ============================================================

/-- In [a finite directed acyclic graph](hyp:V,G), a [vertex in a seed set's ancestral
closure](hyp:Q,n,hn) that [maximizes topological order there](hyp:hmax) [belongs to the
seed set itself](goal). -/
theorem topoMax_mem_seed {Q : Finset V} {n : V}
    (hn : n ∈ G.ancestralSet Q)
    (hmax : ∀ m ∈ G.ancestralSet Q, G.topoOrder m ≤ G.topoOrder n) :
    n ∈ Q := by
  simp only [ancestralSet, Finset.mem_union, ancestorsSet, Finset.mem_filter,
    Finset.mem_univ, true_and] at hn
  rcases hn with hnQ | ⟨w, hwQ, haw⟩
  · exact hnQ
  · -- `n` is a strict ancestor of `w ∈ Q`; but `w ∈ ancestralSet Q`, so
    -- `topoOrder w ≤ topoOrder n < topoOrder w`, contradiction.
    exfalso
    have hwAnc : w ∈ G.ancestralSet Q :=
      G.subset_ancestralSet Q (by exact hwQ)
    have h1 : G.topoOrder w ≤ G.topoOrder n := hmax w hwAnc
    have h2 : G.topoOrder n < G.topoOrder w := G.isAncestor_topoOrder_lt haw
    omega

/-- In [a finite directed acyclic graph](hyp:V,G), if [one set lies inside another
set's ancestral closure](hyp:Q,Q',h), then [the first set's ancestral closure remains
inside the second set's ancestral closure](goal). -/
theorem ancestralSet_subset_of_subset_ancestralSet {Q Q' : Finset V}
    (h : Q' ⊆ G.ancestralSet Q) : G.ancestralSet Q' ⊆ G.ancestralSet Q := by
  intro u hu
  simp only [ancestralSet, Finset.mem_union, ancestorsSet, Finset.mem_filter,
    Finset.mem_univ, true_and] at hu ⊢
  rcases hu with huQ' | ⟨q', hq'Q', haq'⟩
  · have := h huQ'
    simpa only [ancestralSet, Finset.mem_union, ancestorsSet, Finset.mem_filter,
      Finset.mem_univ, true_and] using this
  · have hq' := h hq'Q'
    simp only [ancestralSet, Finset.mem_union, ancestorsSet, Finset.mem_filter,
      Finset.mem_univ, true_and] at hq'
    rcases hq' with hq'Q | ⟨q, hqQ, haq'q⟩
    · exact Or.inr ⟨q', hq'Q, haq'⟩
    · exact Or.inr ⟨q, hqQ, G.isAncestor_trans haq' haq'q⟩

/-- In [a finite directed acyclic graph](hyp:V,G), let [a selected vertex lie in a
seed's ancestral closure](hyp:Q,n,hnAnc) and [maximize topological order there](hyp:hmax).
If [a new seed lies in that closure](hyp:Q',hQ'sub) but [omits that vertex](hyp:hnQ'),
then [the new seed's ancestral closure has strictly smaller cardinality](goal). -/
theorem ancestralSet_card_lt_of_peel {Q Q' : Finset V} {n : V}
    (hnAnc : n ∈ G.ancestralSet Q)
    (hmax : ∀ m ∈ G.ancestralSet Q, G.topoOrder m ≤ G.topoOrder n)
    (hQ'sub : Q' ⊆ G.ancestralSet Q) (hnQ' : n ∉ Q') :
    (G.ancestralSet Q').card < (G.ancestralSet Q).card := by
  apply Finset.card_lt_card
  rw [Finset.ssubset_iff_of_subset (G.ancestralSet_subset_of_subset_ancestralSet hQ'sub)]
  refine ⟨n, hnAnc, ?_⟩
  intro hnAnc'
  -- `n ∈ ancestralSet Q'` means either `n ∈ Q'` or `n` is a strict ancestor of some
  -- `q' ∈ Q' ⊆ ancestralSet Q`; the hypotheses rule out both cases.
  simp only [ancestralSet, Finset.mem_union, ancestorsSet, Finset.mem_filter,
    Finset.mem_univ, true_and] at hnAnc'
  rcases hnAnc' with hnQ'' | ⟨q', hq'Q', haq'⟩
  · exact hnQ' hnQ''
  · have hq'Anc : q' ∈ G.ancestralSet Q := hQ'sub hq'Q'
    have h1 : G.topoOrder q' ≤ G.topoOrder n := hmax q' hq'Anc
    have h2 : G.topoOrder n < G.topoOrder q' := G.isAncestor_topoOrder_lt haq'
    omega

/-- In [a finite directed acyclic graph](hyp:V,G), let [a selected vertex maximize
topological order in a seed's ancestral closure](hyp:Q,n,hmax) and [belong to a random
conditioning set](hyp:Zr,hnZr). If [a replacement set lies in the closure](hyp:S,hSsub)
but [omits the selected vertex](hyp:hnS), then [its topological height is strictly
smaller than that of the random conditioning set](goal). -/
theorem sup_topoOrder_lt_of_peel {Q Zr S : Finset V} {n : V}
    (hmax : ∀ m ∈ G.ancestralSet Q, G.topoOrder m ≤ G.topoOrder n)
    (hnZr : n ∈ Zr) (hSsub : S ⊆ G.ancestralSet Q) (hnS : n ∉ S) :
    (S.sup (fun v => G.topoOrder v + 1)) < (Zr.sup (fun v => G.topoOrder v + 1)) := by
  have hZr_ge : G.topoOrder n + 1 ≤ Zr.sup (fun v => G.topoOrder v + 1) :=
    Finset.le_sup (f := fun v => G.topoOrder v + 1) hnZr
  have hS_le : S.sup (fun v => G.topoOrder v + 1) ≤ G.topoOrder n := by
    rw [Finset.sup_le_iff]
    intro s hs
    have hsAnc : s ∈ G.ancestralSet Q := hSsub hs
    have hle : G.topoOrder s ≤ G.topoOrder n := hmax s hsAnc
    have hne : s ≠ n := fun h => hnS (h ▸ hs)
    have : G.topoOrder s ≠ G.topoOrder n := fun h => hne (G.topoOrder_injective h)
    omega
  omega

end DAG

end Causalean.Graph
