/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan
-/

module
public import Tengoku.Causalean.Causalean.Stat.CLT.Martingale.Main
public import Tengoku

/-!
# Independent triangular-array central limit theorems

This module specializes the martingale triangular-array CLT to rowwise
independent, non-identically distributed real arrays.  The natural past
filtration makes each centered increment a martingale difference; independence
also turns conditional variances and conditional Lindeberg terms into their
unconditional counterparts.

For rows consisting of identically distributed draws, use
`iidRowSumLaw_tendsto_gaussian` or `iidRowNormalizedSumLaw_tendsto_gaussian` from
`Causalean.Stat.CLT.Lindeberg`; those theorems expose the usual iid-sample API directly.
-/

@[expose] public section

namespace Causalean.Stat

open Filter MeasureTheory ProbabilityTheory Topology

variable {Ω : ℕ → Type*} {mΩ : (n : ℕ) → MeasurableSpace (Ω n)}
  {μ : (n : ℕ) → Measure (Ω n)}

/-- For [a sequence of random variables](hyp:X) that is [strongly measurable at every
index](hyp:hX), the [past filtration](goal) at time `k` is generated by the variables with indices
strictly below `k`. -/
def pastFiltration {S : Type*} [MeasurableSpace S] (X : ℕ → S → ℝ)
    (hX : ∀ k, StronglyMeasurable (X k)) :
    Filtration ℕ (inferInstance : MeasurableSpace S) where
  seq k := ⨆ j ∈ {j | j < k},
    MeasurableSpace.comap (X j) (inferInstance : MeasurableSpace ℝ)
  mono' i j hij := by
    apply iSup₂_le
    intro k hk
    exact le_iSup_of_le k (le_iSup_of_le (lt_of_lt_of_le hk hij) le_rfl)
  le' k := by
    apply iSup₂_le
    intro j hj
    exact (hX j).measurable.comap_le

/-- A [strongly measurable sequence](hyp:hX) that is [independent](hyp:hIndep) has its
[coordinate at an indicated index](hyp:k) [independent of its strict past](goal). -/
theorem indep_past_of_iIndepFun {S : Type*} [MeasurableSpace S] {X : ℕ → S → ℝ}
    {ν : Measure S} (hX : ∀ k, StronglyMeasurable (X k))
    (hIndep : iIndepFun X ν) (k : ℕ) :
    Indep (MeasurableSpace.comap (X k) (inferInstance : MeasurableSpace ℝ))
      (pastFiltration X hX k) ν := by
  unfold pastFiltration
  have hdisj : Disjoint ({k} : Set ℕ) {j | j < k} := by
    simp
  simpa using indep_iSup_of_disjoint
    (fun j => (hX j).measurable.comap_le) hIndep hdisj

/-- For [strongly measurable coordinates](hyp:hX) under [rowwise independence](hyp:hIndep), at
[an indicated index](hyp:k), [the conditional expectation given the strict past equals the
unconditional mean](goal). -/
theorem condExp_past_ae_eq_of_iIndepFun
    {S : Type*} [MeasurableSpace S] {ν : Measure S} [IsProbabilityMeasure ν]
    {X : ℕ → S → ℝ}
    (hX : ∀ k, StronglyMeasurable (X k)) (hIndep : iIndepFun X ν) (k : ℕ) :
    ν[X k | pastFiltration X hX k] =ᵐ[ν] fun _ => ν[X k] := by
  exact condExp_indep_eq (hX k).measurable.comap_le (Filtration.le _ _)
    (comap_measurable (X k)).stronglyMeasurable (indep_past_of_iIndepFun hX hIndep k)

/-- For [strongly measurable coordinates](hyp:hX) under [independence](hyp:hIndep), and [a
transform](hyp:g) that is [measurable](hyp:hg), at [an indicated index](hyp:k), [the conditional
expectation of the transformed coordinate given its strict past is its unconditional
expectation](goal). -/
theorem condExp_comp_past_ae_eq_of_iIndepFun
    {S : Type*} [MeasurableSpace S] {ν : Measure S} [IsProbabilityMeasure ν]
    {X : ℕ → S → ℝ} (hX : ∀ k, StronglyMeasurable (X k))
    (hIndep : iIndepFun X ν) (g : ℝ → ℝ) (hg : Measurable g) (k : ℕ) :
    ν[fun ω => g (X k ω) | pastFiltration X hX k] =ᵐ[ν]
      fun _ => ∫ ω, g (X k ω) ∂ν := by
  have hind := indep_past_of_iIndepFun hX hIndep k
  have hcomp : MeasurableSpace.comap (fun ω => g (X k ω))
      (inferInstance : MeasurableSpace ℝ) ≤
      MeasurableSpace.comap (X k) (inferInstance : MeasurableSpace ℝ) := by
    exact (hg.comp (comap_measurable (X k))).comap_le
  exact condExp_indep_eq (hg.comp (hX k).measurable).comap_le (Filtration.le _ _)
    (comap_measurable (fun ω => g (X k ω))).stronglyMeasurable
    (indep_of_indep_of_le_left hind hcomp)

/-- A rowwise independent, centered, square-integrable triangular array over [row sample
spaces](hyp:Ω) and [row laws](hyp:μ) records [row lengths](hyp:rowLength),
[increments](hyp:increment), [strong measurability](hyp:measurable),
[second moments](hyp:squareIntegrable), [centering](hyp:mean_zero), and [independence within
each row](hyp:independent). -/
structure IndependentTriangularArray (Ω : ℕ → Type*)
    [mΩ : (n : ℕ) → MeasurableSpace (Ω n)] (μ : (n : ℕ) → Measure (Ω n)) where
  /-- Number of active increments in a row. -/
  rowLength : ℕ → ℕ
  /-- The row increments. -/
  increment : (n k : ℕ) → Ω n → ℝ
  /-- Every increment is strongly measurable. -/
  measurable : ∀ n k, StronglyMeasurable (increment n k)
  /-- Every active increment is square-integrable. -/
  squareIntegrable : ∀ n k, k < rowLength n → MemLp (increment n k) 2 (μ n)
  /-- Every active increment is centered. -/
  mean_zero : ∀ n k, k < rowLength n → ∫ ω, increment n k ω ∂(μ n) = 0
  /-- Each row is an independent family over every natural index `k`, including indices at or
  beyond `rowLength n`. To encode a finite row, pad inactive coordinates with the constant zero
  random variable. -/
  independent : ∀ n, iIndepFun (increment n) (μ n)

namespace IndependentTriangularArray

/-- The [independent array](hyp:A) equipped with its natural strict-past filtration is a
[martingale-difference array](goal). -/
noncomputable def toMartingale [∀ n, IsProbabilityMeasure (μ n)]
    (A : IndependentTriangularArray Ω μ) : MartingaleDifferenceArray Ω μ where
  rowLength := A.rowLength
  increment := A.increment
  filtration n := pastFiltration (A.increment n) (A.measurable n)
  adapted n k hk := by
    apply Measurable.stronglyMeasurable
    apply Measurable.of_comap_le
    exact le_iSup_of_le k (le_iSup_of_le (Nat.lt_succ_self k) le_rfl)
  squareIntegrable := A.squareIntegrable
  condExp_zero n k hk := by
    refine (condExp_past_ae_eq_of_iIndepFun (A.measurable n) (A.independent n) k).trans ?_
    filter_upwards with ω
    simp only [A.mean_zero n k hk, Pi.zero_apply]

/-- For [an independent array](hyp:A) and [a row](hyp:n), the [unconditional variance sum](goal)
is the sum of the row's second moments. -/
noncomputable def varianceSum (A : IndependentTriangularArray Ω μ) (n : ℕ) : ℝ :=
  ∑ k ∈ Finset.range (A.rowLength n), ∫ ω, (A.increment n k ω) ^ 2 ∂(μ n)

/-- For [an independent array](hyp:A), [a truncation threshold](hyp:ε), and [a row](hyp:n), the
[unconditional Lindeberg sum](goal) adds that row's truncated second moments. -/
noncomputable def lindebergSum (A : IndependentTriangularArray Ω μ)
    (ε : ℝ) (n : ℕ) : ℝ :=
  ∑ k ∈ Finset.range (A.rowLength n),
    ∫ ω, if ε < |A.increment n k ω| then (A.increment n k ω) ^ 2 else 0 ∂(μ n)

/-- For [an independent array](hyp:A), [a moment increment](hyp:δ), and [a row](hyp:n), the
[`2 + δ` unconditional moment sum](goal) adds that row's absolute moments. -/
noncomputable def lyapunovSum (A : IndependentTriangularArray Ω μ)
    (δ : ℝ) (n : ℕ) : ℝ :=
  ∑ k ∈ Finset.range (A.rowLength n),
    ∫ ω, |A.increment n k ω| ^ (2 + δ) ∂(μ n)

/-- For [an independent array](hyp:A) and [a row](hyp:n), [predictable quadratic variation equals
the unconditional variance sum almost everywhere](goal). -/
theorem predictableQuadraticVariation_ae_eq [∀ n, IsProbabilityMeasure (μ n)]
    (A : IndependentTriangularArray Ω μ) (n : ℕ) :
    A.toMartingale.predictableQuadraticVariation n =ᵐ[μ n]
      fun _ => A.varianceSum n := by
  have hterm : ∀ k,
      (μ n)[fun ω => (A.increment n k ω) ^ 2 |
          pastFiltration (A.increment n) (A.measurable n) k] =ᵐ[μ n]
        fun _ => ∫ ω, (A.increment n k ω) ^ 2 ∂(μ n) := by
    intro k
    apply condExp_comp_past_ae_eq_of_iIndepFun
      (A.measurable n) (A.independent n) (fun x => x ^ 2)
    fun_prop
  filter_upwards [ae_all_iff.2 hterm] with ω hω
  unfold MartingaleDifferenceArray.predictableQuadraticVariation varianceSum
  simp only [toMartingale]
  rw [Finset.sum_apply]
  apply Finset.sum_congr rfl
  intro k hk
  exact hω k

/-- For [an independent array](hyp:A), [a threshold](hyp:ε), and [a row](hyp:n), [the conditional
Lindeberg sum equals the unconditional Lindeberg sum almost everywhere](goal). -/
theorem conditionalLindeberg_ae_eq [∀ n, IsProbabilityMeasure (μ n)]
    (A : IndependentTriangularArray Ω μ) (ε : ℝ) (n : ℕ) :
    A.toMartingale.conditionalLindeberg ε n =ᵐ[μ n]
      fun _ => A.lindebergSum ε n := by
  have hterm : ∀ k,
      (μ n)[fun ω => if ε < |A.increment n k ω| then
          (A.increment n k ω) ^ 2 else 0 |
          pastFiltration (A.increment n) (A.measurable n) k] =ᵐ[μ n]
        fun _ => ∫ ω, if ε < |A.increment n k ω| then
          (A.increment n k ω) ^ 2 else 0 ∂(μ n) := by
    intro k
    apply condExp_comp_past_ae_eq_of_iIndepFun
      (A.measurable n) (A.independent n)
        (fun x => if ε < |x| then x ^ 2 else 0)
    exact Measurable.ite (measurableSet_lt measurable_const measurable_abs)
      (measurable_id.pow_const 2) measurable_const
  filter_upwards [ae_all_iff.2 hterm] with ω hω
  unfold MartingaleDifferenceArray.conditionalLindeberg
    MartingaleDifferenceArray.lindebergTerm lindebergSum
  simp only [toMartingale]
  rw [Finset.sum_apply]
  apply Finset.sum_congr rfl
  intro k hk
  exact hω k

/-- **Lindeberg--Feller CLT for independent triangular arrays.** For [a rowwise
independent centered square-integrable array](hyp:A), if [the row variance sums converge
to one](hyp:hVariance) and [the unconditional Lindeberg sums vanish at every positive
threshold](hyp:hLindeberg), then [the row sums converge in distribution to the standard
Gaussian law](goal).

This is Billingsley, Theorem 27.2 (also van der Vaart, Proposition 2.27), obtained from
`martingaleArrayCLT` because independence makes conditional moments unconditional. -/
theorem lindebergFeller_clt [∀ n, IsProbabilityMeasure (μ n)]
    (A : IndependentTriangularArray Ω μ)
    (hVariance : Tendsto A.varianceSum atTop (𝓝 1))
    (hLindeberg : ∀ ε : ℝ, 0 < ε → Tendsto (A.lindebergSum ε) atTop (𝓝 0)) :
    Modes.TendstoInLaw μ A.toMartingale.rowSum atTop (gaussianReal 0 1) := by
  have hVarProb : Modes.TendstoInProbability μ
      A.toMartingale.predictableQuadraticVariation atTop (fun _ _ => 1) :=
    predictableQuadraticVariation_tendstoInProbability_of_ae_eq
      A.toMartingale A.varianceSum A.predictableQuadraticVariation_ae_eq hVariance
  have hLinProb : ∀ ε : ℝ, 0 < ε →
      Modes.TendstoInProbability μ (A.toMartingale.conditionalLindeberg ε)
        atTop (fun _ _ => 0) := by
    intro ε hε
    rw [Modes.tendstoInProbability_iff_norm]
    simp only [Real.norm_eq_abs]
    intro η hη
    have habs : Tendsto (fun n => |A.lindebergSum ε n|) atTop (𝓝 0) := by
      simpa using (hLindeberg ε hε).abs
    have hev : ∀ᶠ n in atTop, |A.lindebergSum ε n| < η :=
      (tendsto_order.1 habs).2 η hη
    apply tendsto_nhds_of_eventually_eq
    filter_upwards [hev] with n hn
    apply measure_eq_zero_iff_ae_notMem.mpr
    filter_upwards [A.conditionalLindeberg_ae_eq ε n] with ω hω
    rw [hω]
    simpa using not_le_of_gt hn
  exact martingaleArrayCLT A.toMartingale hVarProb hLinProb

/-- **Lyapunov `2 + δ` CLT for independent triangular arrays.** For [a rowwise
independent centered square-integrable array](hyp:A), [a positive moment surplus](hyp:hδ),
[integrability of every active `2 + δ` moment](hyp:hMoment), [variance
normalization](hyp:hVariance), and [vanishing `2 + δ` moment sums](hyp:hLyapunov),
[the row sums converge in distribution to the standard Gaussian law](goal).

The proof derives the Lindeberg condition from
`x² 1{|x|>ε} ≤ ε⁻ᵟ |x|²⁺ᵟ` and invokes `lindebergFeller_clt`. -/
theorem lyapunov_clt [∀ n, IsProbabilityMeasure (μ n)]
    (A : IndependentTriangularArray Ω μ) {δ : ℝ} (hδ : 0 < δ)
    (hMoment : ∀ n k, k < A.rowLength n →
      Integrable (fun ω => |A.increment n k ω| ^ (2 + δ)) (μ n))
    (hVariance : Tendsto A.varianceSum atTop (𝓝 1))
    (hLyapunov : Tendsto (A.lyapunovSum δ) atTop (𝓝 0)) :
    Modes.TendstoInLaw μ A.toMartingale.rowSum atTop (gaussianReal 0 1) := by
  apply A.lindebergFeller_clt hVariance
  intro ε hε
  have hnonneg : ∀ n, 0 ≤ A.lindebergSum ε n := by
    intro n
    unfold lindebergSum
    apply Finset.sum_nonneg
    intro k hk
    apply integral_nonneg
    intro ω
    change 0 ≤ if ε < |A.increment n k ω| then (A.increment n k ω) ^ 2 else 0
    split_ifs
    · positivity
    · exact le_rfl
  have hbound : ∀ n, A.lindebergSum ε n ≤ ε ^ (-δ) * A.lyapunovSum δ n := by
    intro n
    unfold lindebergSum lyapunovSum
    rw [Finset.mul_sum]
    apply Finset.sum_le_sum
    intro k hk
    have hk' : k < A.rowLength n := Finset.mem_range.mp hk
    have hsquare : Integrable (fun ω => (A.increment n k ω) ^ 2) (μ n) :=
      (memLp_two_iff_integrable_sq (A.squareIntegrable n k hk').aestronglyMeasurable).mp
        (A.squareIntegrable n k hk')
    have hset : NullMeasurableSet {ω | ε < |A.increment n k ω|} (μ n) :=
      aestronglyMeasurable_const.nullMeasurableSet_lt
        (A.squareIntegrable n k hk').aestronglyMeasurable.norm
    have htrunc : Integrable (fun ω => if ε < |A.increment n k ω| then
        (A.increment n k ω) ^ 2 else 0) (μ n) := by
      apply (hsquare.indicator₀ hset).congr
      filter_upwards with ω
      by_cases hω : ε < |A.increment n k ω| <;> simp [Set.indicator, hω]
    rw [← integral_const_mul]
    apply integral_mono_ae htrunc ((hMoment n k hk').const_mul _)
    filter_upwards with ω
    by_cases hω : ε < |A.increment n k ω|
    · simp only [ite_eq_left hω]
      have hxpos : 0 < |A.increment n k ω| := lt_trans hε hω
      have hp := Real.rpow_le_rpow (le_of_lt hε) (le_of_lt hω) (le_of_lt hδ)
      have hepos : 0 < ε ^ δ := Real.rpow_pos_of_pos hε δ
      rw [Real.rpow_add hxpos, Real.rpow_neg (le_of_lt hε)]
      have hcancel : (ε ^ δ)⁻¹ * ε ^ δ = 1 := inv_mul_cancel₀ hepos.ne'
      calc
        (A.increment n k ω) ^ 2 =
            (ε ^ δ)⁻¹ * ε ^ δ * (A.increment n k ω) ^ 2 := by
              rw [hcancel, one_mul]
        _ ≤ (ε ^ δ)⁻¹ * |A.increment n k ω| ^ δ *
            (A.increment n k ω) ^ 2 := by gcongr
        _ = (ε ^ δ)⁻¹ *
            (|A.increment n k ω| ^ (2 : ℝ) * |A.increment n k ω| ^ δ) := by
              rw [Real.rpow_two, sq_abs]
              ring
    · simp only [ite_eq_right hω]
      positivity
  exact squeeze_zero hnonneg hbound (by
    simpa using (hLyapunov.const_mul (ε ^ (-δ))))

end IndependentTriangularArray

end Causalean.Stat
