import Tengoku.FltRegular.FltRegular.CaseII.AuxLemmas
import Tengoku.FltRegular.FltRegular.MayAssume.Lemmas
import Tengoku.FltRegular.FltRegular.NumberTheory.Cyclotomic.MoreLemmas
import Tengoku.FltRegular.FltRegular.NumberTheory.CyclotomicRing
import Tengoku.FltRegular.FltRegular.NumberTheory.KummersLemma.Field
import Tengoku.FltRegular.FltRegular.NumberTheory.RegularPrimes
import Tengoku.FltRegular.FltRegular.NumberTheory.SystemOfUnits
import Tengoku.FltRegular.FltRegular.NumberTheory.Unramified
import Tengoku.FltRegular.FltRegular.SmallNumbers.Cyclotomic
import Tengoku.FltRegular.FltRegular.SmallNumbers.OrderOf
import Tengoku.FltRegular.FltRegular.SmallNumbers.PID
import Tengoku.FltRegular.FltRegular.SmallNumbers.Seven.Seven
