module
public import Tengoku.Causalean.Causalean.Mathlib.AlgebraicGeometry.Dimension.PolynomialMap.ZariskiClosure
public import Tengoku

/-!
# Polynomial maps and their coordinate algebras

This module fixes the concrete conventions used by the affine polynomial-image
dimension bridge. It uses the neutral affine Zariski closure substrate.
-/

@[expose] public section

namespace Causalean.Mathlib.AlgebraicGeometry.PolynomialImageDimension

noncomputable section

/-- For [two index sets](hyp:ι,κ) and [a family of complex polynomials, one for each output coordinate](hyp:f), [the polynomial coordinate map](goal) sends every complex-valued assignment to the input indices to the complex-valued assignment whose output-coordinate value is the corresponding polynomial evaluated at that assignment. -/
def polynomialCoordinateMap {ι κ : Type*} (f : κ → MvPolynomial ι ℂ) :
    (ι → ℂ) → (κ → ℂ) :=
  fun x k => MvPolynomial.eval x (f k)

/-- For [two index sets](hyp:ι,κ) and [a family of complex polynomials, one for each output coordinate](hyp:f), [the polynomial pullback](goal) is the complex-algebra homomorphism that replaces every output-coordinate variable in a polynomial relation by its corresponding coordinate polynomial. -/
def polynomialPullback {ι κ : Type*} (f : κ → MvPolynomial ι ℂ) :
    MvPolynomial κ ℂ →ₐ[ℂ] MvPolynomial ι ℂ :=
  MvPolynomial.aeval f

/-- For [two index sets](hyp:ι,κ) and [a family of complex coordinate polynomials](hyp:f), [the coordinate subalgebra](goal) is the complex subalgebra of the polynomial ring in the input coordinates generated by that family. -/
abbrev polynomialCoordinateSubalgebra {ι κ : Type*}
    (f : κ → MvPolynomial ι ℂ) : Subalgebra ℂ (MvPolynomial ι ℂ) :=
  (polynomialPullback f).range

/-- For [two index sets](hyp:ι,κ) and [a family of complex coordinate polynomials](hyp:f), [the polynomial image closure](goal) is the smallest complex affine algebraic set containing every output vector obtained by evaluating those polynomials at a complex-valued input vector. -/
abbrev polynomialImageClosure {ι κ : Type*} (f : κ → MvPolynomial ι ℂ) :
    Set (κ → ℂ) :=
  affineZariskiClosure (Set.range (polynomialCoordinateMap f))

/-- For [index types `ι`, `κ`](hyp:ι,κ), [a polynomial parameterization `f`](hyp:f), [a point
`x`](hyp:x), and [a polynomial `P`](hyp:P), [substituting the coordinate polynomials `f` into
`P` and evaluating at `x` agrees with evaluating `P` directly at the point obtained by
evaluating `f`'s coordinates at `x`](goal). -/
lemma eval_polynomialPullback {ι κ : Type*} (f : κ → MvPolynomial ι ℂ)
    (x : ι → ℂ) (P : MvPolynomial κ ℂ) :
    MvPolynomial.eval x (polynomialPullback f P) =
      MvPolynomial.eval (polynomialCoordinateMap f x) P := by
  change MvPolynomial.eval x (MvPolynomial.eval₂ MvPolynomial.C f P) = _
  rw [MvPolynomial.eval_eval₂]
  rw [show (MvPolynomial.eval x).comp MvPolynomial.C = RingHom.id ℂ by
    ext c
    simp]
  rfl

end

end Causalean.Mathlib.AlgebraicGeometry.PolynomialImageDimension
