/-
Copyright (c) 2026 Jiyuan Tan. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Jiyuan Tan

# Cell-level potential outcomes for a panel

This file defines the core potential-outcome object for panel regression.  The
structure `PanelPOSystem` bundles:

* observed cells `R ⊆ I × T` with positive normalized weights;
* a treatment-path-valued random variable `D : Ω → TreatmentPath I T A`;
* an observed-cell exposure mapping `e` and baseline `e0`;
* potential outcomes `Y r e ω : ℝ` and observed outcomes `Yobs r ω` for
  each observed cell `r ∈ R`.

It also defines:

* `observedExposure r hr ω = e r hr (D ω)` — the realized exposure at an
  observed cell;
* `DSigmaAlg` — the σ-algebra `σ(D)` generated by the treatment path;
* `m0 r hr ω = E[Y r hr (e0 r hr) | σ(D)](ω)` — the baseline conditional
  mean;
* `tau r hr e ω = E[Y r hr e − Y r hr (e0 r hr) | σ(D)](ω)` — the
  cell-level exposure response.
-/

module
public import Tengoku.Causalean.Causalean.Panel.Cells
public import Tengoku.Causalean.Causalean.Panel.PO.Exposure
public import Tengoku

/-! # Cell-level panel potential outcomes

This file provides the potential-outcomes foundation for a finite panel: weighted observed unit-period cells, a random treatment path, cell-specific exposures and baseline exposures, potential outcomes, and factual outcomes. It also defines realized exposure and outcome, the σ-algebra generated by the treatment path, and the conditional baseline and exposure-response functions used by the panel-regression layer. -/

@[expose] public section

namespace Causalean
namespace Panel

open MeasureTheory

/-- A panel potential-outcomes system pairs finite unit and time index sets with
[a finite collection of observed unit-period cells carrying positive normalized
weights](hyp:cells), a treatment-path-valued random variable [D](hyp:D) that is
[measurable in every unit-period coordinate](hyp:D_meas), a cell-specific exposure
mapping [e](hyp:e) together with a baseline exposure [e0](hyp:e0), a family of
potential outcomes [Y](hyp:Y) at each cell and exposure that is
[measurable](hyp:Y_meas) and [integrable](hyp:Y_integrable), and a family of
factual observed outcomes [Yobs](hyp:Yobs) stored independently of the
potential-outcome schedule that is likewise
[measurable and integrable](hyp:Yobs_meas,Yobs_integrable). -/
structure PanelPOSystem where
  /-- Unit index type. -/
  I : Type*
  /-- Time index type. -/
  T : Type*
  [fintypeI : Fintype I]
  [fintypeT : Fintype T]
  [decI : DecidableEq I]
  [decT : DecidableEq T]
  /-- Observed unit-period cells with positive normalized weights. -/
  cells : Cells I T
  /-- Action type for treatment assignments. -/
  A : Type*
  /-- Observed-cell-indexed exposure set `E_r`. -/
  E : (r : I × T) → r ∈ cells.observed → Type*
  /-- Each observed-cell exposure set carries a measurable structure. -/
  [measE : ∀ r hr, MeasurableSpace (E r hr)]
  /-- Exposure mapping `e_r : (I → T → A) → E_r` for observed cells. -/
  e : ∀ r hr, TreatmentPath I T A → E r hr
  /-- Baseline exposure `e_r^0 ∈ E_r` for observed cells. -/
  e0 : ∀ r hr, E r hr
  /-- Sample space. -/
  Ω : Type*
  [measΩ : MeasurableSpace Ω]
  [measA : MeasurableSpace A]
  /-- Probability measure. -/
  μ : Measure Ω
  [probμ : IsProbabilityMeasure μ]
  /-- Treatment path random variable `D : Ω → I → T → A`. -/
  D : Ω → TreatmentPath I T A
  /-- `D` is measurable as a map into the function space.  Encoded
  cellwise: each `(D ·) i t : Ω → A` is measurable. -/
  D_meas : ∀ i t, Measurable (fun ω => D ω i t)
  /-- Cell-level potential outcome family `Y r e : Ω → ℝ` on observed cells. -/
  Y : (r : I × T) → (hr : r ∈ cells.observed) → E r hr → Ω → ℝ
  /-- Each potential outcome is measurable. -/
  Y_meas : ∀ r hr e, Measurable (Y r hr e)
  /-- Each potential outcome is integrable. -/
  Y_integrable : ∀ r hr e, Integrable (Y r hr e) μ
  /-- Factual observed outcome family on observed cells. -/
  Yobs : (r : I × T) → r ∈ cells.observed → Ω → ℝ
  /-- Each factual observed outcome is measurable. -/
  Yobs_meas : ∀ r hr, Measurable (Yobs r hr)
  /-- Each factual observed outcome is integrable. -/
  Yobs_integrable : ∀ r hr, Integrable (Yobs r hr) μ

attribute [instance] PanelPOSystem.fintypeI PanelPOSystem.fintypeT
  PanelPOSystem.decI PanelPOSystem.decT PanelPOSystem.measE
  PanelPOSystem.measΩ PanelPOSystem.measA PanelPOSystem.probμ

-- The regularity fields are the leaf atoms every panel side condition bottoms out in;
-- registering them lets `fun_prop` discharge those goals without naming the projection.
attribute [fun_prop] PanelPOSystem.D_meas PanelPOSystem.Y_meas
  PanelPOSystem.Y_integrable PanelPOSystem.Yobs_meas PanelPOSystem.Yobs_integrable

namespace PanelPOSystem

variable (P : PanelPOSystem)

/-- For [a panel potential-outcomes system](hyp:P), [an observed unit-period cell](hyp:r,hr),
and [a sample point](hyp:ω), the [realized exposure](goal) is the cell's exposure mapping applied
to the treatment path realized at that sample point. -/
def observedExposure (r : P.I × P.T) (hr : r ∈ P.cells.observed) (ω : P.Ω) :
    P.E r hr :=
  P.e r hr (P.D ω)

/-- For [a panel potential-outcomes system](hyp:P), [an observed unit-period cell](hyp:r,hr),
and [a sample point](hyp:ω), the [factual observed outcome](goal) is the outcome stored for that
cell and sample point.

It is stored independently from the potential-outcome schedule; the
consistency assumption relates it to the potential outcome at the realized exposure. -/
def observedY (r : P.I × P.T) (hr : r ∈ P.cells.observed) (ω : P.Ω) : ℝ :=
  P.Yobs r hr ω

/-- For [a panel potential-outcomes system](hyp:P), the [treatment-path σ-algebra](goal) is the
smallest σ-algebra on the sample space that makes the treatment assigned to every unit in every
period measurable.

This is the "information of the assignment vector" — the σ-algebra in `\bbE[· | D]`
of Definition 2.4. -/
def DSigmaAlg : MeasurableSpace P.Ω :=
  ⨆ (i : P.I) (t : P.T), MeasurableSpace.comap (fun ω => P.D ω i t) inferInstance

/-- [The σ-algebra generated by the treatment path `D`, `σ(D)`, is a sub-σ-algebra of the
ambient σ-algebra on the outcome space `Ω`](goal). -/
lemma DSigmaAlg_le : P.DSigmaAlg ≤ (inferInstance : MeasurableSpace P.Ω) := by
  rw [DSigmaAlg]
  exact iSup_le (fun i =>
    iSup_le (fun t => measurable_iff_comap_le.mp (P.D_meas i t)))

/-- For [a panel potential-outcomes system](hyp:P) and [an observed unit-period cell](hyp:r,hr),
the [baseline conditional mean](goal), evaluated at each sample point, is the conditional
expectation of that cell's potential outcome under its baseline exposure given the treatment-path
σ-algebra. -/
noncomputable def m0 (r : P.I × P.T) (hr : r ∈ P.cells.observed) : P.Ω → ℝ :=
  MeasureTheory.condExp P.DSigmaAlg P.μ (P.Y r hr (P.e0 r hr))

/-- For [a panel potential-outcomes system](hyp:P), [an observed unit-period cell](hyp:r,hr),
and [an exposure available at that cell](hyp:e), the [cell-level exposure response](goal),
evaluated at each sample point, is the conditional expectation given the treatment-path
σ-algebra of the potential outcome under that exposure minus the potential outcome under the
cell's baseline exposure. -/
noncomputable def tau (r : P.I × P.T) (hr : r ∈ P.cells.observed)
    (e : P.E r hr) : P.Ω → ℝ :=
  MeasureTheory.condExp P.DSigmaAlg P.μ
    (fun ω => P.Y r hr e ω - P.Y r hr (P.e0 r hr) ω)

/-- For [a panel potential-outcomes system](hyp:P), [an observed unit-period cell](hyp:r,hr),
and [a sample point](hyp:ω), the [realized exposure response](goal) is that cell's exposure
response at the exposure induced by the treatment path realized at the sample point. -/
noncomputable def realizedTau (r : P.I × P.T) (hr : r ∈ P.cells.observed)
    (ω : P.Ω) : ℝ :=
  P.tau r hr (P.observedExposure r hr ω) ω

end PanelPOSystem

end Panel
end Causalean
