/-
Copyright (c) 2026 Samuel Schlesinger. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Samuel Schlesinger
-/
module

public import Tengoku.Complexitylib.Complexitylib.Circuits.Frontier.Boundary.Linear

/-!
# Joint linear information at a frontier

Let `U` and `V` be the spaces of linear observations available from the two sides.
Their intersection is shared information. If observations `P ≤ U` and `Q ≤ V`
are already exposed on the frontier, encode them together with that intersection.
The modular identity below avoids charging the same information twice.

For a code generated by rows `L_j`, take `U = span L_past`, `V = span L_future`,
and `P,Q` the visible rows on their respective sides. The rank formula then reads
`rank L_(past ∪ visible) + rank L_(future ∪ visible) - rank L`.
The affine-interface compiler instantiation is proved in the research note;
these declarations check the underlying subspace identity and dimension formula.
-/

@[expose] public section

namespace Complexity.Frontier.LinearBoundary

open Module

variable {F W : Type*} [Field F] [AddCommGroup W] [Module F W]
  (U V P Q : Submodule F W)

/-- Shared information and exposed observations form one subspace, not independent codes. -/
theorem joint_eq (hP : P ≤ U) (hQ : Q ≤ V) :
    (U ⊓ V) ⊔ (P ⊔ Q) = (U ⊔ Q) ⊓ (V ⊔ P) := by
  symm
  calc (U ⊔ Q) ⊓ (V ⊔ P)
      = (U ⊔ Q) ⊓ V ⊔ P := (inf_sup_assoc_of_le V (hP.trans le_sup_left)).symm
    _ = (Q ⊔ (U ⊓ V)) ⊔ P := by
      rw [sup_comm U Q, sup_inf_assoc_of_le U hQ]
    _ = _ := by ac_rfl

/-- The joint code can be smaller than the sum of the separate boundary and syndrome ranks. -/
theorem finrank_joint [FiniteDimensional F W] (hP : P ≤ U) (hQ : Q ≤ V) :
    finrank F ((U ⊓ V) ⊔ (P ⊔ Q) : Submodule F W) =
      finrank F (U ⊔ Q : Submodule F W) + finrank F (V ⊔ P : Submodule F W) -
        finrank F (U ⊔ V : Submodule F W) := by
  have hsup : (U ⊔ Q) ⊔ (V ⊔ P) = U ⊔ V := by
    apply le_antisymm
    · exact sup_le (sup_le le_sup_left (hQ.trans le_sup_right))
        (sup_le le_sup_right (hP.trans le_sup_left))
    · exact sup_le (le_sup_left.trans le_sup_left) (le_sup_left.trans le_sup_right)
  have h := Submodule.finrank_sup_add_finrank_inf_eq (U ⊔ Q) (V ⊔ P)
  rw [hsup] at h
  rw [joint_eq U V P Q hP hQ]
  lia

end Complexity.Frontier.LinearBoundary
